#pragma once

enum TControlID
{
	ID_CUSTOM_BASE = 30000,

	ID_BUTTON_TEST,
	ID_IMAGEHOLDER_TEST,
	ID_BUTTON_OPERATION_UPLOAD,
	ID_BUTTON_OPERATION_RECENT_UPLOADS,
	ID_BUTTON_OPERATION_CREDENTIALS,
	ID_BUTTON_OPERATION_EXIT,
	ID_IMAGEHOLDER_OPERATIONS_LOGO,
	ID_TEXTBOX_CREDENTIALS_NAME,
	ID_TEXTBOX_CREDENTIALS_PASSWORD,
	ID_IMAGEHOLDER_TEXTBOX_CREDENTIALS_NAME_FRAME,
	ID_IMAGEHOLDER_TEXTBOX_CREDENTIALS_PASS_FRAME,
	ID_LABEL_CREDENTIALS_NAME,
	ID_LABEL_CREDENTIALS_PASSWORD,
	ID_IMAGEHOLDER_SPLASH_IMAGE,
	ID_IMGLISTBOX_RECENT_UPLOADS

};
