//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Next2Friends.Soap2Bin.Interaction.AskService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.next2friends.com/", ConfigurationName="AskService.AskServiceSoap")]
    public interface AskServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.next2friends.com/SubmitQuestion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Next2Friends.Soap2Bin.Interaction.AskService.AskQuestionConfirm SubmitQuestion(string nickname, string password, string questionText, int numberOfPhotos, int responseType, string[] customResponses, int durationType, bool isPrivate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.next2friends.com/AttachPhoto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void AttachPhoto(string nickname, string password, string askQuestionID, int indexOrder, string photoBase64String);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.next2friends.com/CompleteQuestion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void CompleteQuestion(string nickname, string password, string askQuestionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.next2friends.com/GetQuestion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Next2Friends.Soap2Bin.Interaction.AskService.AskQuestion GetQuestion(string nickname, string password, int questionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.next2friends.com/GetQuestionIDs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int[] GetQuestionIDs(string nickname, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.next2friends.com/GetQuestions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        AskQuestion[] GetQuestions(string nickname, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.next2friends.com/GetResponse", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Next2Friends.Soap2Bin.Interaction.AskService.AskResponse GetResponse(string nickname, string password, int questionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.next2friends.com/SkipQuestion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void SkipQuestion(string nickname, string password, int questionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.next2friends.com/VoteForQuestion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void VoteForQuestion(string nickname, string password, int questionID, int result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.next2friends.com/")]
    public partial class AskQuestionConfirm : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string advertURLField;
        
        private string advertImageField;
        
        private string askQuestionIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AdvertURL {
            get {
                return this.advertURLField;
            }
            set {
                this.advertURLField = value;
                this.RaisePropertyChanged("AdvertURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AdvertImage {
            get {
                return this.advertImageField;
            }
            set {
                this.advertImageField = value;
                this.RaisePropertyChanged("AdvertImage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AskQuestionID {
            get {
                return this.askQuestionIDField;
            }
            set {
                this.askQuestionIDField = value;
                this.RaisePropertyChanged("AskQuestionID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.next2friends.com/")]
    public partial class AskResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int askQuestionIDField;
        
        private string questionField;
        
        private string photoBase64BinaryField;
        
        private int[] responseValuesField;
        
        private double averageField;
        
        private int responseTypeField;
        
        private string[] customResponsesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int AskQuestionID {
            get {
                return this.askQuestionIDField;
            }
            set {
                this.askQuestionIDField = value;
                this.RaisePropertyChanged("AskQuestionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Question {
            get {
                return this.questionField;
            }
            set {
                this.questionField = value;
                this.RaisePropertyChanged("Question");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PhotoBase64Binary {
            get {
                return this.photoBase64BinaryField;
            }
            set {
                this.photoBase64BinaryField = value;
                this.RaisePropertyChanged("PhotoBase64Binary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public int[] ResponseValues {
            get {
                return this.responseValuesField;
            }
            set {
                this.responseValuesField = value;
                this.RaisePropertyChanged("ResponseValues");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double Average {
            get {
                return this.averageField;
            }
            set {
                this.averageField = value;
                this.RaisePropertyChanged("Average");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int ResponseType {
            get {
                return this.responseTypeField;
            }
            set {
                this.responseTypeField = value;
                this.RaisePropertyChanged("ResponseType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public string[] CustomResponses {
            get {
                return this.customResponsesField;
            }
            set {
                this.customResponsesField = value;
                this.RaisePropertyChanged("CustomResponses");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.next2friends.com/")]
    public partial class AskQuestion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string questionField;
        
        private string dTCreatedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Question {
            get {
                return this.questionField;
            }
            set {
                this.questionField = value;
                this.RaisePropertyChanged("Question");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DTCreated {
            get {
                return this.dTCreatedField;
            }
            set {
                this.dTCreatedField = value;
                this.RaisePropertyChanged("DTCreated");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface AskServiceSoapChannel : Next2Friends.Soap2Bin.Interaction.AskService.AskServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class AskServiceSoapClient : System.ServiceModel.ClientBase<Next2Friends.Soap2Bin.Interaction.AskService.AskServiceSoap>, Next2Friends.Soap2Bin.Interaction.AskService.AskServiceSoap {
        
        public AskServiceSoapClient() {
        }
        
        public AskServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AskServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AskServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AskServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Next2Friends.Soap2Bin.Interaction.AskService.AskQuestionConfirm SubmitQuestion(string nickname, string password, string questionText, int numberOfPhotos, int responseType, string[] customResponses, int durationType, bool isPrivate) {
            return base.Channel.SubmitQuestion(nickname, password, questionText, numberOfPhotos, responseType, customResponses, durationType, isPrivate);
        }
        
        public void AttachPhoto(string nickname, string password, string askQuestionID, int indexOrder, string photoBase64String) {
            base.Channel.AttachPhoto(nickname, password, askQuestionID, indexOrder, photoBase64String);
        }
        
        public void CompleteQuestion(string nickname, string password, string askQuestionID) {
            base.Channel.CompleteQuestion(nickname, password, askQuestionID);
        }
        
        public Next2Friends.Soap2Bin.Interaction.AskService.AskQuestion GetQuestion(string nickname, string password, int questionID) {
            return base.Channel.GetQuestion(nickname, password, questionID);
        }
        
        public int[] GetQuestionIDs(string nickname, string password) {
            return base.Channel.GetQuestionIDs(nickname, password);
        }
        
        public AskQuestion[] GetQuestions(string nickname, string password) {
            return base.Channel.GetQuestions(nickname, password);
        }
        
        public Next2Friends.Soap2Bin.Interaction.AskService.AskResponse GetResponse(string nickname, string password, int questionID) {
            return base.Channel.GetResponse(nickname, password, questionID);
        }
        
        public void SkipQuestion(string nickname, string password, int questionID) {
            base.Channel.SkipQuestion(nickname, password, questionID);
        }
        
        public void VoteForQuestion(string nickname, string password, int questionID, int result) {
            base.Channel.VoteForQuestion(nickname, password, questionID, result);
        }
    }
}
