//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Standard3D.rc
//
#define IDS_STBAR_FIVETH                1
#define IDS_TOOLTIP_FIVETH              2
#define IDS_STBAR_SIXTH                 3
#define IDS_TOOLTIP_SIXTH               4
#define IDS_CENTER                      5
#define IDS_RADIUS                      6
#define IDS_BOX_ENTER_BASE_PNT          7
#define IDS_ERROR_ZERO_RAD              8
#define IDS_FIRST_AXE_PNT               9
#define IDS_SECOND_AXE_PNT              10
#define IDS_BOX_X_SIZE                  11
#define IDS_ERROR_ZERO_LENGTH           12
#define IDS_RADIUS_1                    13
#define IDS_RADIUS_2                    14
#define IDS_BOX_Y_SIZE                  15
#define IDS_ERROR_ZERO_BOTH_RADS        16
#define IDS_NORMAL                      17
#define IDS_TOR_TOLZCHINA               18
#define IDS_ERROR_ZERO_TOLZCHINA        19
#define IDS_BOX_Z_SIZE                  20
#define IDS_ERROR_ZERO_VECTOR           21
#define IDS_BASE_POINT                  22
#define IDS_ENTER_NEW_SIZE              23
#define IDS_ERROR_ZERO_SIZE             24
#define IDS_X_SIZE                      25
#define IDS_Y_SIZE                      26
#define IDS_Z_SIZE                      27
#define IDS_CYL_ENTER_FIRST_P           28
#define IDS_FIRST_COEF                  29
#define IDS_SECOND_COEF                 30
#define IDS_CYL_ENTER_SEC_P             31
#define IDS_COEF_IS_EQ                  32
#define IDS_ERROR_COEF_RANGE            33
#define IDS_CHANGE_SPH_RAD              34
#define IDS_CYL_ENTER_RAD               35
#define IDS_NEW_RADIUS                  36
#define IDS_OTHER_PARAMS                37
#define IDS_NEW_SIZE                    38
#define IDS_CHANGE_X_SIZE               39
#define IDS_CHANGE_Y_SIZE               40
#define IDS_CHANGE_Z_SIZE               41
#define IDS_ENTER_NEW_HEIGHT            42
#define IDS_SPHERE_PARAMS               43
#define IDS_ELLIPSOID_PARAMS            44
#define IDS_ERROR_HEIGHT_MUST_BE_POSIT  45
#define IDS_CONE_PARAMS                 46
#define IDS_CONE_ENTER_FIR_RAD          47
#define IDS_CYL_PARAMS                  48
#define IDS_CONE_ENTER_SEC_RAD          49
#define IDS_SPH_B_PARAMS                50
#define IDS_TOR_ENTER_NORMAL            51
#define IDS_CHANGE_FIRST_RAD            52
#define IDS_CHANGE_SECOND_RAD           53
#define IDS_CHANGE_HEIGHT               54
#define IDS_CHANGE_F_COEF               55
#define IDS_CHANGE_S_COEF               56
#define IDS_TOR_ENTER_RAD               57
#define IDS_CHANGE_FIRST_R              58
#define IDS_CHANGE_SEC_R                59
#define IDS_NEW_HEIGHT                  60
#define IDS_SPH_ENTER_CENTER            61
#define IDS_SPH_ENTER_RAD               62
#define IDS_ERROR_RAD_MUST_BE_POSIT     63
#define IDS_REDACTION                   64
#define IDS_ENTER_NEW_RAD               65
#define IDS_TOR_ENTER_TOLSH             66
#define IDS_TOR_NEW_TOLSCH              67
#define IDS_ERROR_TOLS_MUST_BE_POSIT    68
#define IDS_ERROR_TOL_MUST_BE_LETTER_RAD 69
#define IDS_TOR_NEW_TOLS                70
#define IDS_CHANGE_TOLSH                71
#define IDS_SP_B_ENTER_F_C              72
#define IDS_SP_B_ENTER_S_C              73
#define IDS_SP_B_ENTER_NEW_COEF         74
#define IDR_TOOLBAR                     4020
#define IDC_SPH_MERID_EDIT              4035
#define IDC_MERID_SPH_SPIN              4036
#define IDC_SPH_PARAL_EDIT              4037
#define IDC_MERID_EDIT                  4037
#define IDC_PARAL_SPH_SPIN              4038
#define IDC_MERID_SPIN                  4038
#define IDC_TOR_MERID1_EDIT             4039
#define IDC_TOR_MERID1_SPIN             4040
#define IDC_TOR_MERID2_EDIT             4041
#define IDC_TOR_MERID2_SPIN             4042
#define IDB_BITMAP1                     4048
#define IDB_TLB_BMP                     4048
#define IDD_SPHERE_EDIT_DLG             4049
#define IDD_MERIDIANS_DLG               4050
#define IDD_TORUS_EDIT_DLG              4051
#define IDB_CUBE                        4052
#define IDB_SPHERE                      4053
#define IDB_CONE                        4054
#define IDB_CYL                         4055
#define IDB_TOR                         4056
#define IDB_ELL                         4057
#define IDB_SB                          4058
#define ID_BUTTON_0                     32783
#define ID_BUTTON_1                     32784
#define ID_BUTTON_2                     32785
#define ID_BUTTON_3                     32786
#define ID_BUTTON_4                     32787
#define ID_BUTTON_5                     32788
#define ID_BUTTON_6                     32789
#define IDS_MENU_STRING                 33775
#define IDS_STBAR_ZERO                  33776
#define IDS_TOOLTIP_ZERO                33777
#define IDS_STBAR_FIRST                 33778
#define IDS_STBAR_SECOND                33779
#define IDS_TOOLTIP_FIRST               33780
#define IDS_TOOLTIP_SECOND              33781
#define IDS_STBAR_THIRD                 33786
#define IDS_STBAR_FOURTH                33787
#define IDS_TOOLTIP_THIRD               33788
#define IDS_TOOLTIP_FOURTH              33789

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        4059
#define _APS_NEXT_COMMAND_VALUE         32790
#define _APS_NEXT_CONTROL_VALUE         4043
#define _APS_NEXT_SYMED_VALUE           4000
#endif
#endif
