//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genetibase.SmoothControls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Genetibase.SmoothControls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified {0} does not belong to this {1}..
        /// </summary>
        internal static string Argument_InvalidTabPage {
            get {
                return ResourceManager.GetString("Argument_InvalidTabPage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Back {
            get {
                object obj = ResourceManager.GetObject("Back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Blank).
        /// </summary>
        internal static string BlankText {
            get {
                return ResourceManager.GetString("BlankText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Category_Action {
            get {
                return ResourceManager.GetString("Category_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string Category_Appearance {
            get {
                return ResourceManager.GetString("Category_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        internal static string Category_Behavior {
            get {
                return ResourceManager.GetString("Category_Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string Category_Data {
            get {
                return ResourceManager.GetString("Category_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string Category_Properties {
            get {
                return ResourceManager.GetString("Category_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Changed.
        /// </summary>
        internal static string Category_PropertyChanged {
            get {
                return ResourceManager.GetString("Category_PropertyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex.
        /// </summary>
        internal static string Category_Regex {
            get {
                return ResourceManager.GetString("Category_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines how the image is resized within the picture box..
        /// </summary>
        internal static string Description_PictureBox_DisplayMode {
            get {
                return ResourceManager.GetString("Description_PictureBox_DisplayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the value of the DisplayMode property changes..
        /// </summary>
        internal static string Description_PictureBox_DisplayModeChanged {
            get {
                return ResourceManager.GetString("Description_PictureBox_DisplayModeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines the image to display within the picture box..
        /// </summary>
        internal static string Description_PictureBox_Image {
            get {
                return ResourceManager.GetString("Description_PictureBox_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the value of the Image property changes..
        /// </summary>
        internal static string Description_PictureBox_ImageChanged {
            get {
                return ResourceManager.GetString("Description_PictureBox_ImageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Description_PictureBox_ZoomFactor {
            get {
                return ResourceManager.GetString("Description_PictureBox_ZoomFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the value of the ZoomFactor property changes..
        /// </summary>
        internal static string Description_PictureBox_ZoomFactorChanged {
            get {
                return ResourceManager.GetString("Description_PictureBox_ZoomFactorChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether the border is rendered with rounded corners..
        /// </summary>
        internal static string Description_RoundedCorners {
            get {
                return ResourceManager.GetString("Description_RoundedCorners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the value of the RoundedCorners property changes..
        /// </summary>
        internal static string Description_RoundedCornersChanged {
            get {
                return ResourceManager.GetString("Description_RoundedCornersChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A panel with rounded corners and a custom background..
        /// </summary>
        internal static string Description_RoundedPanelEx {
            get {
                return ResourceManager.GetString("Description_RoundedPanelEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether to draw the border for the picture box..
        /// </summary>
        internal static string Description_SmoothPictureBox_DrawBorder {
            get {
                return ResourceManager.GetString("Description_SmoothPictureBox_DrawBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the value of the DrawBorder property changes..
        /// </summary>
        internal static string Description_SmoothPictureBox_DrawBorderChanged {
            get {
                return ResourceManager.GetString("Description_SmoothPictureBox_DrawBorderChanged", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap FastBack {
            get {
                object obj = ResourceManager.GetObject("FastBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FastForward {
            get {
                object obj = ResourceManager.GetObject("FastForward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Forward {
            get {
                object obj = ResourceManager.GetObject("Forward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background should return an array containing at least {0} element(s)..
        /// </summary>
        internal static string InvalidOperation_BackgroundArraySize {
            get {
                return ResourceManager.GetString("InvalidOperation_BackgroundArraySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border should return an array containing at least {0} element(s)..
        /// </summary>
        internal static string InvalidOperation_BorderArraySize {
            get {
                return ResourceManager.GetString("InvalidOperation_BorderArraySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InnerShadow should return an array containing at least {0} element(s)..
        /// </summary>
        internal static string InvalidOperation_InnerShadowArraySize {
            get {
                return ResourceManager.GetString("InvalidOperation_InnerShadowArraySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OuterShadow should return an array containing at least {0} element(s)..
        /// </summary>
        internal static string InvalidOperation_OuterShadowArraySize {
            get {
                return ResourceManager.GetString("InvalidOperation_OuterShadowArraySize", resourceCulture);
            }
        }
    }
}
