//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Next2Friends.Soap2Bin.Interaction.MemberService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.next2friends.com", ConfigurationName="MemberService.MemberServiceSoap")]
    public interface MemberServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.next2friends.com/CheckUserExists", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        bool CheckUserExists(string nickname, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.next2friends.com/CreateUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int CreateUser(string emailAddress, string nickname, string password, int gender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.next2friends.com/GetEncryptionKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string GetEncryptionKey(string nickname, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.next2friends.com/GetMemberID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string GetMemberID(string nickname, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.next2friends.com/GetProfilePhotoUrl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string GetProfilePhotoUrl(string nickname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.next2friends.com/GetMemberStatusText", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string GetMemberStatusText(string nickname, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.next2friends.com/SetMemberStatusText", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void SetMemberStatusText(string nickname, string password, string statusText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.next2friends.com/GetTagID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string GetTagID(string nickname, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.next2friends.com/RemindPassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void RemindPassword(string emailAddress);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface MemberServiceSoapChannel : Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class MemberServiceSoapClient : System.ServiceModel.ClientBase<Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceSoap>, Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceSoap {
        
        public MemberServiceSoapClient() {
        }
        
        public MemberServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MemberServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CheckUserExists(string nickname, string password) {
            return base.Channel.CheckUserExists(nickname, password);
        }
        
        public int CreateUser(string emailAddress, string nickname, string password, int gender) {
            return base.Channel.CreateUser(emailAddress, nickname, password, gender);
        }
        
        public string GetEncryptionKey(string nickname, string password) {
            return base.Channel.GetEncryptionKey(nickname, password);
        }
        
        public string GetMemberID(string nickname, string password) {
            return base.Channel.GetMemberID(nickname, password);
        }
        
        public string GetProfilePhotoUrl(string nickname) {
            return base.Channel.GetProfilePhotoUrl(nickname);
        }
        
        public string GetMemberStatusText(string nickname, string password) {
            return base.Channel.GetMemberStatusText(nickname, password);
        }
        
        public void SetMemberStatusText(string nickname, string password, string statusText) {
            base.Channel.SetMemberStatusText(nickname, password, statusText);
        }
        
        public string GetTagID(string nickname, string password) {
            return base.Channel.GetTagID(nickname, password);
        }
        
        public void RemindPassword(string emailAddress) {
            base.Channel.RemindPassword(emailAddress);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.next2friends.com", ConfigurationName="MemberService.MemberServiceHttpGet")]
    public interface MemberServiceHttpGet {
        
        // CODEGEN: Generating message contract since the operation CheckUserExists is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.next2friends.com/MemberServiceHttpGet/CheckUserExistsRequest", ReplyAction="http://www.next2friends.com/MemberServiceHttpGet/CheckUserExistsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Next2Friends.Soap2Bin.Interaction.MemberService.CheckUserExistsResponse CheckUserExists(Next2Friends.Soap2Bin.Interaction.MemberService.CheckUserExistsRequest request);
        
        // CODEGEN: Generating message contract since the operation CreateUser is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.next2friends.com/MemberServiceHttpGet/CreateUserRequest", ReplyAction="http://www.next2friends.com/MemberServiceHttpGet/CreateUserResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Next2Friends.Soap2Bin.Interaction.MemberService.CreateUserResponse CreateUser(Next2Friends.Soap2Bin.Interaction.MemberService.CreateUserRequest request);
        
        // CODEGEN: Generating message contract since the operation GetEncryptionKey is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.next2friends.com/MemberServiceHttpGet/GetEncryptionKeyRequest", ReplyAction="http://www.next2friends.com/MemberServiceHttpGet/GetEncryptionKeyResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Next2Friends.Soap2Bin.Interaction.MemberService.GetEncryptionKeyResponse GetEncryptionKey(Next2Friends.Soap2Bin.Interaction.MemberService.GetEncryptionKeyRequest request);
        
        // CODEGEN: Generating message contract since the operation GetMemberID is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.next2friends.com/MemberServiceHttpGet/GetMemberIDRequest", ReplyAction="http://www.next2friends.com/MemberServiceHttpGet/GetMemberIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Next2Friends.Soap2Bin.Interaction.MemberService.GetMemberIDResponse GetMemberID(Next2Friends.Soap2Bin.Interaction.MemberService.GetMemberIDRequest request);
        
        // CODEGEN: Generating message contract since the operation GetProfilePhotoUrl is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.next2friends.com/MemberServiceHttpGet/GetProfilePhotoUrlRequest", ReplyAction="http://www.next2friends.com/MemberServiceHttpGet/GetProfilePhotoUrlResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Next2Friends.Soap2Bin.Interaction.MemberService.GetProfilePhotoUrlResponse GetProfilePhotoUrl(Next2Friends.Soap2Bin.Interaction.MemberService.GetProfilePhotoUrlRequest request);
        
        // CODEGEN: Generating message contract since the operation GetMemberStatusText is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.next2friends.com/MemberServiceHttpGet/GetMemberStatusTextRequest", ReplyAction="http://www.next2friends.com/MemberServiceHttpGet/GetMemberStatusTextResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Next2Friends.Soap2Bin.Interaction.MemberService.GetMemberStatusTextResponse GetMemberStatusText(Next2Friends.Soap2Bin.Interaction.MemberService.GetMemberStatusTextRequest request);
        
        // CODEGEN: Generating message contract since the operation SetMemberStatusText is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.next2friends.com/MemberServiceHttpGet/SetMemberStatusTextRequest", ReplyAction="http://www.next2friends.com/MemberServiceHttpGet/SetMemberStatusTextResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Next2Friends.Soap2Bin.Interaction.MemberService.SetMemberStatusTextResponse SetMemberStatusText(Next2Friends.Soap2Bin.Interaction.MemberService.SetMemberStatusTextRequest request);
        
        // CODEGEN: Generating message contract since the operation GetTagID is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.next2friends.com/MemberServiceHttpGet/GetTagIDRequest", ReplyAction="http://www.next2friends.com/MemberServiceHttpGet/GetTagIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Next2Friends.Soap2Bin.Interaction.MemberService.GetTagIDResponse GetTagID(Next2Friends.Soap2Bin.Interaction.MemberService.GetTagIDRequest request);
        
        // CODEGEN: Generating message contract since the operation RemindPassword is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.next2friends.com/MemberServiceHttpGet/RemindPasswordRequest", ReplyAction="http://www.next2friends.com/MemberServiceHttpGet/RemindPasswordResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Next2Friends.Soap2Bin.Interaction.MemberService.RemindPasswordResponse RemindPassword(Next2Friends.Soap2Bin.Interaction.MemberService.RemindPasswordRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserExistsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nickname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        public CheckUserExistsRequest() {
        }
        
        public CheckUserExistsRequest(string nickname, string password) {
            this.nickname = nickname;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserExistsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.next2friends.com", Order=0)]
        public bool boolean;
        
        public CheckUserExistsResponse() {
        }
        
        public CheckUserExistsResponse(bool boolean) {
            this.boolean = boolean;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string emailAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nickname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string gender;
        
        public CreateUserRequest() {
        }
        
        public CreateUserRequest(string emailAddress, string nickname, string password, string gender) {
            this.emailAddress = emailAddress;
            this.nickname = nickname;
            this.password = password;
            this.gender = gender;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.next2friends.com", Order=0)]
        public int @int;
        
        public CreateUserResponse() {
        }
        
        public CreateUserResponse(int @int) {
            this.@int = @int;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEncryptionKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nickname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        public GetEncryptionKeyRequest() {
        }
        
        public GetEncryptionKeyRequest(string nickname, string password) {
            this.nickname = nickname;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEncryptionKeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.next2friends.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public GetEncryptionKeyResponse() {
        }
        
        public GetEncryptionKeyResponse(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMemberIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nickname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        public GetMemberIDRequest() {
        }
        
        public GetMemberIDRequest(string nickname, string password) {
            this.nickname = nickname;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMemberIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.next2friends.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public GetMemberIDResponse() {
        }
        
        public GetMemberIDResponse(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProfilePhotoUrlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nickname;
        
        public GetProfilePhotoUrlRequest() {
        }
        
        public GetProfilePhotoUrlRequest(string nickname) {
            this.nickname = nickname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProfilePhotoUrlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.next2friends.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public GetProfilePhotoUrlResponse() {
        }
        
        public GetProfilePhotoUrlResponse(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMemberStatusTextRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nickname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        public GetMemberStatusTextRequest() {
        }
        
        public GetMemberStatusTextRequest(string nickname, string password) {
            this.nickname = nickname;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMemberStatusTextResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.next2friends.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public GetMemberStatusTextResponse() {
        }
        
        public GetMemberStatusTextResponse(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetMemberStatusTextRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nickname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string statusText;
        
        public SetMemberStatusTextRequest() {
        }
        
        public SetMemberStatusTextRequest(string nickname, string password, string statusText) {
            this.nickname = nickname;
            this.password = password;
            this.statusText = statusText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetMemberStatusTextResponse {
        
        public SetMemberStatusTextResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTagIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nickname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        public GetTagIDRequest() {
        }
        
        public GetTagIDRequest(string nickname, string password) {
            this.nickname = nickname;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTagIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.next2friends.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public GetTagIDResponse() {
        }
        
        public GetTagIDResponse(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemindPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string emailAddress;
        
        public RemindPasswordRequest() {
        }
        
        public RemindPasswordRequest(string emailAddress) {
            this.emailAddress = emailAddress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemindPasswordResponse {
        
        public RemindPasswordResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface MemberServiceHttpGetChannel : Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpGet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class MemberServiceHttpGetClient : System.ServiceModel.ClientBase<Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpGet>, Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpGet {
        
        public MemberServiceHttpGetClient() {
        }
        
        public MemberServiceHttpGetClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MemberServiceHttpGetClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberServiceHttpGetClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberServiceHttpGetClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Next2Friends.Soap2Bin.Interaction.MemberService.CheckUserExistsResponse Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpGet.CheckUserExists(Next2Friends.Soap2Bin.Interaction.MemberService.CheckUserExistsRequest request) {
            return base.Channel.CheckUserExists(request);
        }
        
        public bool CheckUserExists(string nickname, string password) {
            Next2Friends.Soap2Bin.Interaction.MemberService.CheckUserExistsRequest inValue = new Next2Friends.Soap2Bin.Interaction.MemberService.CheckUserExistsRequest();
            inValue.nickname = nickname;
            inValue.password = password;
            Next2Friends.Soap2Bin.Interaction.MemberService.CheckUserExistsResponse retVal = ((Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpGet)(this)).CheckUserExists(inValue);
            return retVal.boolean;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Next2Friends.Soap2Bin.Interaction.MemberService.CreateUserResponse Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpGet.CreateUser(Next2Friends.Soap2Bin.Interaction.MemberService.CreateUserRequest request) {
            return base.Channel.CreateUser(request);
        }
        
        public int CreateUser(string emailAddress, string nickname, string password, string gender) {
            Next2Friends.Soap2Bin.Interaction.MemberService.CreateUserRequest inValue = new Next2Friends.Soap2Bin.Interaction.MemberService.CreateUserRequest();
            inValue.emailAddress = emailAddress;
            inValue.nickname = nickname;
            inValue.password = password;
            inValue.gender = gender;
            Next2Friends.Soap2Bin.Interaction.MemberService.CreateUserResponse retVal = ((Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpGet)(this)).CreateUser(inValue);
            return retVal.@int;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Next2Friends.Soap2Bin.Interaction.MemberService.GetEncryptionKeyResponse Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpGet.GetEncryptionKey(Next2Friends.Soap2Bin.Interaction.MemberService.GetEncryptionKeyRequest request) {
            return base.Channel.GetEncryptionKey(request);
        }
        
        public string GetEncryptionKey(string nickname, string password) {
            Next2Friends.Soap2Bin.Interaction.MemberService.GetEncryptionKeyRequest inValue = new Next2Friends.Soap2Bin.Interaction.MemberService.GetEncryptionKeyRequest();
            inValue.nickname = nickname;
            inValue.password = password;
            Next2Friends.Soap2Bin.Interaction.MemberService.GetEncryptionKeyResponse retVal = ((Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpGet)(this)).GetEncryptionKey(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Next2Friends.Soap2Bin.Interaction.MemberService.GetMemberIDResponse Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpGet.GetMemberID(Next2Friends.Soap2Bin.Interaction.MemberService.GetMemberIDRequest request) {
            return base.Channel.GetMemberID(request);
        }
        
        public string GetMemberID(string nickname, string password) {
            Next2Friends.Soap2Bin.Interaction.MemberService.GetMemberIDRequest inValue = new Next2Friends.Soap2Bin.Interaction.MemberService.GetMemberIDRequest();
            inValue.nickname = nickname;
            inValue.password = password;
            Next2Friends.Soap2Bin.Interaction.MemberService.GetMemberIDResponse retVal = ((Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpGet)(this)).GetMemberID(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Next2Friends.Soap2Bin.Interaction.MemberService.GetProfilePhotoUrlResponse Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpGet.GetProfilePhotoUrl(Next2Friends.Soap2Bin.Interaction.MemberService.GetProfilePhotoUrlRequest request) {
            return base.Channel.GetProfilePhotoUrl(request);
        }
        
        public string GetProfilePhotoUrl(string nickname) {
            Next2Friends.Soap2Bin.Interaction.MemberService.GetProfilePhotoUrlRequest inValue = new Next2Friends.Soap2Bin.Interaction.MemberService.GetProfilePhotoUrlRequest();
            inValue.nickname = nickname;
            Next2Friends.Soap2Bin.Interaction.MemberService.GetProfilePhotoUrlResponse retVal = ((Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpGet)(this)).GetProfilePhotoUrl(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Next2Friends.Soap2Bin.Interaction.MemberService.GetMemberStatusTextResponse Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpGet.GetMemberStatusText(Next2Friends.Soap2Bin.Interaction.MemberService.GetMemberStatusTextRequest request) {
            return base.Channel.GetMemberStatusText(request);
        }
        
        public string GetMemberStatusText(string nickname, string password) {
            Next2Friends.Soap2Bin.Interaction.MemberService.GetMemberStatusTextRequest inValue = new Next2Friends.Soap2Bin.Interaction.MemberService.GetMemberStatusTextRequest();
            inValue.nickname = nickname;
            inValue.password = password;
            Next2Friends.Soap2Bin.Interaction.MemberService.GetMemberStatusTextResponse retVal = ((Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpGet)(this)).GetMemberStatusText(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Next2Friends.Soap2Bin.Interaction.MemberService.SetMemberStatusTextResponse Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpGet.SetMemberStatusText(Next2Friends.Soap2Bin.Interaction.MemberService.SetMemberStatusTextRequest request) {
            return base.Channel.SetMemberStatusText(request);
        }
        
        public void SetMemberStatusText(string nickname, string password, string statusText) {
            Next2Friends.Soap2Bin.Interaction.MemberService.SetMemberStatusTextRequest inValue = new Next2Friends.Soap2Bin.Interaction.MemberService.SetMemberStatusTextRequest();
            inValue.nickname = nickname;
            inValue.password = password;
            inValue.statusText = statusText;
            Next2Friends.Soap2Bin.Interaction.MemberService.SetMemberStatusTextResponse retVal = ((Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpGet)(this)).SetMemberStatusText(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Next2Friends.Soap2Bin.Interaction.MemberService.GetTagIDResponse Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpGet.GetTagID(Next2Friends.Soap2Bin.Interaction.MemberService.GetTagIDRequest request) {
            return base.Channel.GetTagID(request);
        }
        
        public string GetTagID(string nickname, string password) {
            Next2Friends.Soap2Bin.Interaction.MemberService.GetTagIDRequest inValue = new Next2Friends.Soap2Bin.Interaction.MemberService.GetTagIDRequest();
            inValue.nickname = nickname;
            inValue.password = password;
            Next2Friends.Soap2Bin.Interaction.MemberService.GetTagIDResponse retVal = ((Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpGet)(this)).GetTagID(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Next2Friends.Soap2Bin.Interaction.MemberService.RemindPasswordResponse Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpGet.RemindPassword(Next2Friends.Soap2Bin.Interaction.MemberService.RemindPasswordRequest request) {
            return base.Channel.RemindPassword(request);
        }
        
        public void RemindPassword(string emailAddress) {
            Next2Friends.Soap2Bin.Interaction.MemberService.RemindPasswordRequest inValue = new Next2Friends.Soap2Bin.Interaction.MemberService.RemindPasswordRequest();
            inValue.emailAddress = emailAddress;
            Next2Friends.Soap2Bin.Interaction.MemberService.RemindPasswordResponse retVal = ((Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpGet)(this)).RemindPassword(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.next2friends.com", ConfigurationName="MemberService.MemberServiceHttpPost")]
    public interface MemberServiceHttpPost {
        
        // CODEGEN: Generating message contract since the operation CheckUserExists is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.next2friends.com/MemberServiceHttpPost/CheckUserExistsRequest", ReplyAction="http://www.next2friends.com/MemberServiceHttpPost/CheckUserExistsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Next2Friends.Soap2Bin.Interaction.MemberService.CheckUserExistsResponse1 CheckUserExists(Next2Friends.Soap2Bin.Interaction.MemberService.CheckUserExistsRequest1 request);
        
        // CODEGEN: Generating message contract since the operation CreateUser is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.next2friends.com/MemberServiceHttpPost/CreateUserRequest", ReplyAction="http://www.next2friends.com/MemberServiceHttpPost/CreateUserResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Next2Friends.Soap2Bin.Interaction.MemberService.CreateUserResponse1 CreateUser(Next2Friends.Soap2Bin.Interaction.MemberService.CreateUserRequest1 request);
        
        // CODEGEN: Generating message contract since the operation GetEncryptionKey is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.next2friends.com/MemberServiceHttpPost/GetEncryptionKeyRequest", ReplyAction="http://www.next2friends.com/MemberServiceHttpPost/GetEncryptionKeyResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Next2Friends.Soap2Bin.Interaction.MemberService.GetEncryptionKeyResponse1 GetEncryptionKey(Next2Friends.Soap2Bin.Interaction.MemberService.GetEncryptionKeyRequest1 request);
        
        // CODEGEN: Generating message contract since the operation GetMemberID is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.next2friends.com/MemberServiceHttpPost/GetMemberIDRequest", ReplyAction="http://www.next2friends.com/MemberServiceHttpPost/GetMemberIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Next2Friends.Soap2Bin.Interaction.MemberService.GetMemberIDResponse1 GetMemberID(Next2Friends.Soap2Bin.Interaction.MemberService.GetMemberIDRequest1 request);
        
        // CODEGEN: Generating message contract since the operation GetProfilePhotoUrl is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.next2friends.com/MemberServiceHttpPost/GetProfilePhotoUrlRequest", ReplyAction="http://www.next2friends.com/MemberServiceHttpPost/GetProfilePhotoUrlResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Next2Friends.Soap2Bin.Interaction.MemberService.GetProfilePhotoUrlResponse1 GetProfilePhotoUrl(Next2Friends.Soap2Bin.Interaction.MemberService.GetProfilePhotoUrlRequest1 request);
        
        // CODEGEN: Generating message contract since the operation GetMemberStatusText is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.next2friends.com/MemberServiceHttpPost/GetMemberStatusTextRequest", ReplyAction="http://www.next2friends.com/MemberServiceHttpPost/GetMemberStatusTextResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Next2Friends.Soap2Bin.Interaction.MemberService.GetMemberStatusTextResponse1 GetMemberStatusText(Next2Friends.Soap2Bin.Interaction.MemberService.GetMemberStatusTextRequest1 request);
        
        // CODEGEN: Generating message contract since the operation SetMemberStatusText is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.next2friends.com/MemberServiceHttpPost/SetMemberStatusTextRequest", ReplyAction="http://www.next2friends.com/MemberServiceHttpPost/SetMemberStatusTextResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Next2Friends.Soap2Bin.Interaction.MemberService.SetMemberStatusTextResponse1 SetMemberStatusText(Next2Friends.Soap2Bin.Interaction.MemberService.SetMemberStatusTextRequest1 request);
        
        // CODEGEN: Generating message contract since the operation GetTagID is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.next2friends.com/MemberServiceHttpPost/GetTagIDRequest", ReplyAction="http://www.next2friends.com/MemberServiceHttpPost/GetTagIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Next2Friends.Soap2Bin.Interaction.MemberService.GetTagIDResponse1 GetTagID(Next2Friends.Soap2Bin.Interaction.MemberService.GetTagIDRequest1 request);
        
        // CODEGEN: Generating message contract since the operation RemindPassword is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.next2friends.com/MemberServiceHttpPost/RemindPasswordRequest", ReplyAction="http://www.next2friends.com/MemberServiceHttpPost/RemindPasswordResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Next2Friends.Soap2Bin.Interaction.MemberService.RemindPasswordResponse1 RemindPassword(Next2Friends.Soap2Bin.Interaction.MemberService.RemindPasswordRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserExistsRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nickname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        public CheckUserExistsRequest1() {
        }
        
        public CheckUserExistsRequest1(string nickname, string password) {
            this.nickname = nickname;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserExistsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.next2friends.com", Order=0)]
        public bool boolean;
        
        public CheckUserExistsResponse1() {
        }
        
        public CheckUserExistsResponse1(bool boolean) {
            this.boolean = boolean;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string emailAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nickname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string gender;
        
        public CreateUserRequest1() {
        }
        
        public CreateUserRequest1(string emailAddress, string nickname, string password, string gender) {
            this.emailAddress = emailAddress;
            this.nickname = nickname;
            this.password = password;
            this.gender = gender;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.next2friends.com", Order=0)]
        public int @int;
        
        public CreateUserResponse1() {
        }
        
        public CreateUserResponse1(int @int) {
            this.@int = @int;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEncryptionKeyRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nickname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        public GetEncryptionKeyRequest1() {
        }
        
        public GetEncryptionKeyRequest1(string nickname, string password) {
            this.nickname = nickname;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEncryptionKeyResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.next2friends.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public GetEncryptionKeyResponse1() {
        }
        
        public GetEncryptionKeyResponse1(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMemberIDRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nickname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        public GetMemberIDRequest1() {
        }
        
        public GetMemberIDRequest1(string nickname, string password) {
            this.nickname = nickname;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMemberIDResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.next2friends.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public GetMemberIDResponse1() {
        }
        
        public GetMemberIDResponse1(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProfilePhotoUrlRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nickname;
        
        public GetProfilePhotoUrlRequest1() {
        }
        
        public GetProfilePhotoUrlRequest1(string nickname) {
            this.nickname = nickname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProfilePhotoUrlResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.next2friends.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public GetProfilePhotoUrlResponse1() {
        }
        
        public GetProfilePhotoUrlResponse1(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMemberStatusTextRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nickname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        public GetMemberStatusTextRequest1() {
        }
        
        public GetMemberStatusTextRequest1(string nickname, string password) {
            this.nickname = nickname;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMemberStatusTextResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.next2friends.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public GetMemberStatusTextResponse1() {
        }
        
        public GetMemberStatusTextResponse1(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetMemberStatusTextRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nickname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string statusText;
        
        public SetMemberStatusTextRequest1() {
        }
        
        public SetMemberStatusTextRequest1(string nickname, string password, string statusText) {
            this.nickname = nickname;
            this.password = password;
            this.statusText = statusText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetMemberStatusTextResponse1 {
        
        public SetMemberStatusTextResponse1() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTagIDRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nickname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        public GetTagIDRequest1() {
        }
        
        public GetTagIDRequest1(string nickname, string password) {
            this.nickname = nickname;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTagIDResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.next2friends.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public GetTagIDResponse1() {
        }
        
        public GetTagIDResponse1(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemindPasswordRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string emailAddress;
        
        public RemindPasswordRequest1() {
        }
        
        public RemindPasswordRequest1(string emailAddress) {
            this.emailAddress = emailAddress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemindPasswordResponse1 {
        
        public RemindPasswordResponse1() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface MemberServiceHttpPostChannel : Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpPost, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class MemberServiceHttpPostClient : System.ServiceModel.ClientBase<Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpPost>, Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpPost {
        
        public MemberServiceHttpPostClient() {
        }
        
        public MemberServiceHttpPostClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MemberServiceHttpPostClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberServiceHttpPostClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberServiceHttpPostClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Next2Friends.Soap2Bin.Interaction.MemberService.CheckUserExistsResponse1 Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpPost.CheckUserExists(Next2Friends.Soap2Bin.Interaction.MemberService.CheckUserExistsRequest1 request) {
            return base.Channel.CheckUserExists(request);
        }
        
        public bool CheckUserExists(string nickname, string password) {
            Next2Friends.Soap2Bin.Interaction.MemberService.CheckUserExistsRequest1 inValue = new Next2Friends.Soap2Bin.Interaction.MemberService.CheckUserExistsRequest1();
            inValue.nickname = nickname;
            inValue.password = password;
            Next2Friends.Soap2Bin.Interaction.MemberService.CheckUserExistsResponse1 retVal = ((Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpPost)(this)).CheckUserExists(inValue);
            return retVal.boolean;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Next2Friends.Soap2Bin.Interaction.MemberService.CreateUserResponse1 Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpPost.CreateUser(Next2Friends.Soap2Bin.Interaction.MemberService.CreateUserRequest1 request) {
            return base.Channel.CreateUser(request);
        }
        
        public int CreateUser(string emailAddress, string nickname, string password, string gender) {
            Next2Friends.Soap2Bin.Interaction.MemberService.CreateUserRequest1 inValue = new Next2Friends.Soap2Bin.Interaction.MemberService.CreateUserRequest1();
            inValue.emailAddress = emailAddress;
            inValue.nickname = nickname;
            inValue.password = password;
            inValue.gender = gender;
            Next2Friends.Soap2Bin.Interaction.MemberService.CreateUserResponse1 retVal = ((Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpPost)(this)).CreateUser(inValue);
            return retVal.@int;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Next2Friends.Soap2Bin.Interaction.MemberService.GetEncryptionKeyResponse1 Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpPost.GetEncryptionKey(Next2Friends.Soap2Bin.Interaction.MemberService.GetEncryptionKeyRequest1 request) {
            return base.Channel.GetEncryptionKey(request);
        }
        
        public string GetEncryptionKey(string nickname, string password) {
            Next2Friends.Soap2Bin.Interaction.MemberService.GetEncryptionKeyRequest1 inValue = new Next2Friends.Soap2Bin.Interaction.MemberService.GetEncryptionKeyRequest1();
            inValue.nickname = nickname;
            inValue.password = password;
            Next2Friends.Soap2Bin.Interaction.MemberService.GetEncryptionKeyResponse1 retVal = ((Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpPost)(this)).GetEncryptionKey(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Next2Friends.Soap2Bin.Interaction.MemberService.GetMemberIDResponse1 Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpPost.GetMemberID(Next2Friends.Soap2Bin.Interaction.MemberService.GetMemberIDRequest1 request) {
            return base.Channel.GetMemberID(request);
        }
        
        public string GetMemberID(string nickname, string password) {
            Next2Friends.Soap2Bin.Interaction.MemberService.GetMemberIDRequest1 inValue = new Next2Friends.Soap2Bin.Interaction.MemberService.GetMemberIDRequest1();
            inValue.nickname = nickname;
            inValue.password = password;
            Next2Friends.Soap2Bin.Interaction.MemberService.GetMemberIDResponse1 retVal = ((Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpPost)(this)).GetMemberID(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Next2Friends.Soap2Bin.Interaction.MemberService.GetProfilePhotoUrlResponse1 Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpPost.GetProfilePhotoUrl(Next2Friends.Soap2Bin.Interaction.MemberService.GetProfilePhotoUrlRequest1 request) {
            return base.Channel.GetProfilePhotoUrl(request);
        }
        
        public string GetProfilePhotoUrl(string nickname) {
            Next2Friends.Soap2Bin.Interaction.MemberService.GetProfilePhotoUrlRequest1 inValue = new Next2Friends.Soap2Bin.Interaction.MemberService.GetProfilePhotoUrlRequest1();
            inValue.nickname = nickname;
            Next2Friends.Soap2Bin.Interaction.MemberService.GetProfilePhotoUrlResponse1 retVal = ((Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpPost)(this)).GetProfilePhotoUrl(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Next2Friends.Soap2Bin.Interaction.MemberService.GetMemberStatusTextResponse1 Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpPost.GetMemberStatusText(Next2Friends.Soap2Bin.Interaction.MemberService.GetMemberStatusTextRequest1 request) {
            return base.Channel.GetMemberStatusText(request);
        }
        
        public string GetMemberStatusText(string nickname, string password) {
            Next2Friends.Soap2Bin.Interaction.MemberService.GetMemberStatusTextRequest1 inValue = new Next2Friends.Soap2Bin.Interaction.MemberService.GetMemberStatusTextRequest1();
            inValue.nickname = nickname;
            inValue.password = password;
            Next2Friends.Soap2Bin.Interaction.MemberService.GetMemberStatusTextResponse1 retVal = ((Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpPost)(this)).GetMemberStatusText(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Next2Friends.Soap2Bin.Interaction.MemberService.SetMemberStatusTextResponse1 Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpPost.SetMemberStatusText(Next2Friends.Soap2Bin.Interaction.MemberService.SetMemberStatusTextRequest1 request) {
            return base.Channel.SetMemberStatusText(request);
        }
        
        public void SetMemberStatusText(string nickname, string password, string statusText) {
            Next2Friends.Soap2Bin.Interaction.MemberService.SetMemberStatusTextRequest1 inValue = new Next2Friends.Soap2Bin.Interaction.MemberService.SetMemberStatusTextRequest1();
            inValue.nickname = nickname;
            inValue.password = password;
            inValue.statusText = statusText;
            Next2Friends.Soap2Bin.Interaction.MemberService.SetMemberStatusTextResponse1 retVal = ((Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpPost)(this)).SetMemberStatusText(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Next2Friends.Soap2Bin.Interaction.MemberService.GetTagIDResponse1 Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpPost.GetTagID(Next2Friends.Soap2Bin.Interaction.MemberService.GetTagIDRequest1 request) {
            return base.Channel.GetTagID(request);
        }
        
        public string GetTagID(string nickname, string password) {
            Next2Friends.Soap2Bin.Interaction.MemberService.GetTagIDRequest1 inValue = new Next2Friends.Soap2Bin.Interaction.MemberService.GetTagIDRequest1();
            inValue.nickname = nickname;
            inValue.password = password;
            Next2Friends.Soap2Bin.Interaction.MemberService.GetTagIDResponse1 retVal = ((Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpPost)(this)).GetTagID(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Next2Friends.Soap2Bin.Interaction.MemberService.RemindPasswordResponse1 Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpPost.RemindPassword(Next2Friends.Soap2Bin.Interaction.MemberService.RemindPasswordRequest1 request) {
            return base.Channel.RemindPassword(request);
        }
        
        public void RemindPassword(string emailAddress) {
            Next2Friends.Soap2Bin.Interaction.MemberService.RemindPasswordRequest1 inValue = new Next2Friends.Soap2Bin.Interaction.MemberService.RemindPasswordRequest1();
            inValue.emailAddress = emailAddress;
            Next2Friends.Soap2Bin.Interaction.MemberService.RemindPasswordResponse1 retVal = ((Next2Friends.Soap2Bin.Interaction.MemberService.MemberServiceHttpPost)(this)).RemindPassword(inValue);
        }
    }
}
