//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NuGenDimension.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             101
#define IDR_HTML_OBJSYSPARAMSDLG        104
#define IDR_HTML_COMMANDPANELDLG        105
#define IDR_MAINFRAME                   128
#define IDR_GEOMETRY_TYPE               129
#define IDS_PRECISION_STRING            130
#define IDS_PROJECTION_TLB_CAPT         131
#define IDS_NAVIGATE_TLB_CAPT           132
#define IDR_GEOMETRY                    133
#define IDS_DO_YOU_WANT_SAVE_SCRIPT     133
#define IDS_PLUGINS_MENU_STRING         134
#define IDS_SNAPS_TLB_CAPT              135
#define IDS_LAYER_LABEL                 136
#define IDS_STANDARD_TLB_CAPT           137
#define IDS_SETUPS_TLB_CAPT             138
#define IDS_SYSTEM_TLB_CAPT             138
#define IDS_EDIT_OBJECT_PLUGIN_NOT_FOUND 139
#define IDS_LAYER_VIS                   140
#define IDS_MESSAGE_CURR_LAYER_INVIS    141
#define IDS_OPEN_MAT_LIB_PATH           142
#define IDS_BAD_MAT_EDITOR_FILE         143
#define IDS_MAT_EDITOR_NOT_FOUND        144
#define IDS_MAT_TLB_CAPT                145
#define IDS_MODULATE_COL                146
#define IDS_BLEND_COL                   147
#define IDS_REPLACE_COL                 148
#define IDS_BAD_FONT_NAME               149
#define IDC_OPEN_HAND                   150
#define IDS_BAD_FONT_FILE               150
#define IDD_SCRIPT_DLG                  151
#define IDS_OBJECT_COPY                 151
#define IDI_SCRIPT_ICON_BIG             152
#define IDS_X_LOCK                      152
#define IDI_SCRIPT_ICON_SMALL           153
#define IDS_Y_LOCK                      153
#define IDR_SCRIPT_MENU                 154
#define IDS_Z_LOCK                      154
#define IDS_MENU_PANEL                  155
#define IDD_EMPTY_DLG                   156
#define IDS_REPORT_BAD_FILE             156
#define IDS_OB_PR_DL_ATTRIBUTES         157
#define IDS_OB_PR_DL_FULL_ATTRIBUTES    158
#define IDS_OB_PR_DL_NAME               159
#define IDS_REPORT_ONLY_ONE_ZERO_COLUMN 160
#define IDS_TRANS_OBJECTS               161
#define IDS_TRANS_PARAMS                162
#define IDS_ROT_OBJECTS                 163
#define IDS_ROT_PARAMS                  164
#define IDS_NO_SELECTED_OBJECTS         165
#define IDS_CHOISE_TRANS_OBJ            166
#define IDS_CHOISE_ROT_OBJ              167
#define IDS_TRANS_OBJ                   168
#define IDS_ROT_OBJ                     169
#define IDS_ENTER_TRANS_PARAMS          170
#define IDS_ENTER_ROT_PARAMS            171
#define IDS_ERROR_LONG_FONT_NAME        172
#define IDS_CANNT_LOAD_FONT             173
#define IDS_THIS_FONT_EXIST             174
#define IDS_GROUP_COMMAND               175
#define IDS_SELECT_OBJS_FOR_GROUP       176
#define IDS_OBJCTS                      177
#define IDS_SCENE                       178
#define IDS_SCRIPTS                     179
#define IDD_WORK_PLANES_SETUPS_DLG      180
#define IDS_PAGES                       180
#define IDS_WORK_PLANES                 181
#define IDS_LAYERS                      182
#define IDS_OB_PR_DL_FULL_NAME          183
#define IDR_SYSTEM_TOOLBAR              184
#define IDS_OB_PR_DL_LAYER              184
#define IDS_OB_PR_DL_FULL_LAYER         185
#define IDR_PROJECTION_TOOLBAR          186
#define IDS_OB_PR_DL_COLOR              186
#define IDS_OB_PR_DL_FULL_COLOR         187
#define IDR_NAVIGATE_TOOLBAR            188
#define IDS_OB_PR_DL_LIN_TH             188
#define IDS_OB_PR_DL_FULL_LIN_TH        189
#define IDR_SNAPS_TOOLBAR               190
#define IDS_OB_PR_DL_LN_TY              190
#define IDS_OB_PR_DL_FULL_LN_TY         191
#define IDR_CONTEXT_MENUS               192
#define IDS_OB_PR_DL_VIS                192
#define IDS_OB_PR_DL_FULL_VIS           193
#define IDD_LAYERS_DLG                  194
#define IDS_OB_PR_DL_SHOW               194
#define IDD_SYSTEMS_PARAMS_OBJ_DLG      195
#define IDS_OB_PR_DL_FULL_SHOW          195
#define IDD_MAT_ON_OBJ_DLG              196
#define IDS_OB_PR_DL_GAB                196
#define IDR_MATERIAL_TOOLBAR            197
#define IDS_OB_PR_DL_FULL_GAB           197
#define IDS_OB_PR_DL_SHOW_YES           198
#define IDS_OB_PR_DL_SHOW_NO            199
#define IDS_OB_PR_DL_GAB_YES            200
#define IDB_MAINFRAME_TOOBAR_TC         201
#define IDS_OB_PR_DL_GAB_NO             201
#define IDB_GEOMETRY_TOOLBAR_TC         202
#define IDS_OB_PR_DL_DRAW               202
#define IDB_PROJECTION_TOOLBAR_TC       203
#define IDS_OB_PR_DL_FULL_DRAW          203
#define IDB_NAVIGATE_TOOLBAR_TC         204
#define IDS_OB_PR_DL_DRAW_FR            204
#define IDD_TRANSLATE_PANEL             205
#define IDS_OB_PR_DL_DRAW_SOL           205
#define IDD_FONT_PREVIEW_DLG            206
#define IDS_REP_PR_DL_FRAME             206
#define IDB_BITMAP1                     207
#define IDB_SNAP_TOOLBAR_TC             207
#define IDS_REP_PR_DL_FULL_FRAME        207
#define IDD_ROTATE_PANEL                208
#define IDS_YES                         208
#define IDD_COMMAND_PANEL_DLG           209
#define IDS_NO                          209
#define IDD_GET_POINT_DLG               210
#define IDS_REP_PR_DL_LEFT              210
#define IDB_LOCK_BUTTON_BITMAP          211
#define IDS_REP_PR_DL_FULL_LEFT         211
#define IDD_GET_VECTOR_DLG              212
#define IDS_REP_PR_DL_RIGHT             212
#define IDD_GET_NUMBER_DLG              213
#define IDS_REP_PR_DL_FULL_RIGHT        213
#define IDD_GET_OBJECTS_DLG             214
#define IDS_REP_PR_DL_TOP               214
#define IDS_REP_PR_DL_FULL_TOP          215
#define IDD_SELECT_POINT_DLG            216
#define IDS_REP_PR_DL_BOTTOM            216
#define IDB_TREE_CTRL_OPTIONS           217
#define IDS_REP_PR_DL_FULL_BOTTOM       217
#define IDD_REPORT_DIALOG_LINE_PROPERTIES 218
#define IDS_PER_PR_DL_COL_FR            218
#define IDD_REPORT_DIALOG_BOX_PROPERTIES 219
#define IDS_PER_PR_DL_FULL_COL_FR       219
#define IDD_REPORT_DIALOG_LABEL_PROPERTIES 220
#define IDS_PER_PR_DL_TH_FR             220
#define IDD_REPORT_DIALOG_RULER_MEASUREMENTS 221
#define IDS_PER_PR_DL_FULL_TH_FR        221
#define IDD_REPORT_DIALOG_PICTURE_PROPERTIES 222
#define IDS_REP_COMMON_PROPS            222
#define IDS_REP_FULL_COMMON_PROPS       223
#define IDS_REP_PR_FILE                 224
#define IDD_REPORT_DIALOG_SETTINGS      225
#define IDS_REP_PR_FULL_FILE            225
#define IDS_REP_LINE_FULL_COL           226
#define IDS_REP_LINE_FULL_TH            227
#define IDR_REPORT_TYPE                 228
#define IDI_REPORT_TYPE                 229
#define IDS_REP_BOX_FILL                229
#define IDC_CURSOR1                     230
#define IDC_SPLITTER                    230
#define IDS_REP_BOX_FULL_FILL           230
#define IDD_INFO_DLG                    231
#define IDS_REP_BOX_IS_FILL             231
#define IDB_BITMAP2                     232
#define IDB_DEL_OBJ_TC                  232
#define IDS_REP_BOX_FULL_IS_FILL        232
#define IDD_SCENE_TREE_CTRL             233
#define IDS_REP_BOX_FULL_COLOR          233
#define IDD_REPORT_PAGES_PREVIEW        234
#define IDS_REP_LAB                     234
#define IDB_VISIBLE_OBJ_TC              235
#define IDS_REP_FULL_LAB                235
#define IDB_BITMAP4                     236
#define IDB_INVISIBLE_OBJ_TC            236
#define IDS_REP_LAB_FONT                236
#define IDB_BITMAP3                     237
#define IDB_FIT_OBJECT                  237
#define IDS_REP_LAB_FULL_FONT           237
#define IDD_FONTS_PREVIEW_DLG           238
#define IDS_REP_LAB_ALIGN               238
#define IDD_DRAFT_TEMPLATE_NAME_DLG     239
#define IDS_REP_LAB_ALIGN_L             239
#define IDD_CHOISE_TEMPLATE_DLG         240
#define IDS_REP_LAB_ALIGN_C             240
#define IDS_REP_LAB_ALIGN_R             241
#define IDS_REP_LAB_FULL_ALIGN          242
#define IDR_REPORT_TOOLBAR              243
#define IDS_REPORT_VIEW                 243
#define IDS_REPORT_TEXT_ANG             244
#define IDB_REPORT_TC                   245
#define IDS_REPORT_FULL_TEXT_ANG        245
#define IDR_REPORT_OBJECTS_TOOLBAR      246
#define IDS_REPORT_0_ANG                246
#define IDS_REPORT_90_ANG               247
#define IDB_REPORT_OBJECTS              248
#define IDS_REPORT_M90_ANG              248
#define IDR_REPORT_VIEW                 249
#define IDS_REPORT_180_ANG              249
#define IDS_REP_GROUP                   250
#define IDB_REPORT_VIEW                 251
#define IDS_REP_UNGROUP                 251
#define IDB_REP_UP                      252
#define IDS_REP_CUT                     252
#define IDB_BITMAP6                     253
#define IDB_REP_BACK                    253
#define IDS_REP_COPY                    253
#define IDB_BITMAP7                     254
#define IDB_REP_COPY                    254
#define IDS_REP_PASTE                   254
#define IDB_BITMAP8                     255
#define IDB_REP_CUT                     255
#define IDS_REP_CREATE_TEMPLATE         255
#define IDB_BITMAP9                     256
#define IDB_REP_DOWN                    256
#define IDS_REP_DUPLIC                  256
#define IDB_BITMAP10                    257
#define IDB_REP_FR                      257
#define IDS_REP_UP                      257
#define IDB_BITMAP11                    258
#define IDB_REP_GROUP                   258
#define IDS_REP_DOWN                    258
#define IDB_BITMAP12                    259
#define IDB_REP_PASTE                   259
#define IDS_REP_FRONT                   259
#define IDB_BITMAP13                    260
#define IDB_REP_PROP                    260
#define IDS_REP_BACK                    260
#define IDB_BITMAP14                    261
#define IDB_REP_TEMPL                   261
#define IDS_XY_WP                       261
#define IDB_BITMAP15                    262
#define IDB_REP_UNGR                    262
#define IDS_XZ_WP                       262
#define IDB_OBJECTS_BMP                 263
#define IDS_YZ_WP                       263
#define IDB_BITMAP5                     264
#define IDB_LAYERS_BMP                  264
#define IDS_NORMAL                      264
#define IDB_BITMAP16                    265
#define IDB_WP_BMP                      265
#define IDS_COMMANDER                   265
#define IDB_BITMAP17                    266
#define IDB_YZ_WP_BMP                   266
#define IDB_BITMAP18                    267
#define IDB_XY_WP_BMP                   267
#define IDB_BITMAP19                    268
#define IDB_XZ_WP_BMP                   268
#define IDB_RADIO_UNCHECK_BMP           269
#define IDB_BITMAP21                    270
#define IDB_RADIO_CHECK_BMP             270
#define IDB_UNCK_OBJ_BMP                271
#define IDB_SYSTEM_TC                   272
#define IDB_SCENE                       277
#define IDB_COMMANDER                   278
#define IDR_SCRIPT_TLB                  279
#define IDB_SCRIPT                      281
#define IDD_GET_ONE_DGL                 282
#define IDB_SCRIPT_TLB                  283
#define IDD_SETUPS_DLG                  284
#define IDD_THEME_SHEET_DLG             285
#define IDD_CURSOR_SHEET_DLG            286
#define IDB_TH_XP                       287
#define IDB_TH_CLAS                     288
#define IDB_TH_ICY                      289
#define IDB_TH_2003                     290
#define IDB_YZ_WP_BMP1                  291
#define IDB_NUGENDIM                    293
#define IDD_RTRENDER                    294
#define IDB_PROVA                       295
#define IDB_NUGENDIM1                   296
#define IDC_TEX_ON_OBJ_BTN              1003
#define IDC_RADIO1                      1012
#define IDC_RADIO2                      1013
#define IDC_SC_U_ED                     1020
#define IDC_SH_U_ED                     1021
#define IDC_SH_V_ED                     1024
#define IDC_SC_V_ED                     1032
#define IDC_MAT_COUNT                   1039
#define IDC_MAT_COMMENT                 1040
#define IDC_MAT_NAMES_LIST              1041
#define IDC_MAT_NAME                    1042
#define IDC_AMBIENT_RADIO               1043
#define IDC_DIFFUSION_RADIO             1044
#define IDC_EMISSION_RADIO              1045
#define IDC_SPECULAR_RADIO              1046
#define IDC_SC_U_SP                     1046
#define IDC_TRANSPARENT_RADIO           1047
#define IDC_SHININESS_RADIO             1048
#define IDC_SC_V_SP                     1048
#define IDC_RED_SLIDER                  1049
#define IDC_SH_U_SP                     1049
#define IDC_GREEN_SLIDER                1050
#define IDC_SH_V_SP                     1050
#define IDC_BLUE_SLIDER                 1051
#define IDC_RADIO3                      1051
#define IDC_RED_EDIT                    1052
#define IDC_GREEN_EDIT                  1053
#define IDC_ANG_EDIT                    1053
#define IDC_BLUE_EDIT                   1054
#define IDC_PLAMATEXCTRL                1055
#define IDC_R_STATIC                    1056
#define IDC_G_STATIC                    1057
#define IDC_B_STATIC                    1058
#define IDC_TRANSP_SLIDER               1059
#define IDC_ANG_SPIN                    1059
#define IDC_SHININESS_SLIDER            1060
#define IDC_TRANSP_EDIT                 1061
#define IDC_MIX_COLOR_COMBO             1061
#define IDC_SHININESS_EDIT              1062
#define IDC_TEXTURES_LIST               1063
#define IDC_TEX_PREVIEW                 1064
#define IDC_SCRIPT_RICHEDIT             1065
#define IDC_MODE_PIC                    1065
#define IDC_SMOOTH_TEXT_CHECK           1066
#define IDC_LAYERS_COMBO                1067
#define IDC_CURSOR_STEP_EDIT            1068
#define IDC_CURSOR_STEP_SPIN            1069
#define IDC_COLOR_COMBO                 1070
#define IDC_MULT_TEXT_CHECK             1070
#define IDC_LINE_THICKNESS_COMBO        1071
#define IDC_LINE_STYLE_COMBO            1072
#define IDC_X_POS_EDIT                  1079
#define IDC_Y_POS_EDIT                  1083
#define IDC_Z_POS_EDIT                  1087
#define IDC_X_POS_STATIC                1092
#define IDC_Y_POS_STATIC                1093
#define IDC_Z_POS_STATIC                1094
#define IDC_LIST1                       1099
#define IDC_LAYERS_LIST                 1099
#define IDC_FONT_PREVIEW_LIST           1099
#define IDC_SELECT_POINT_LIST           1099
#define IDC_                            1099
#define IDC_TRANS_VEC_Z_LABEL           1099
#define IDC_ROT_Y_LABEL                 1099
#define IDC_FONT_SYMB_LIST              1099
#define IDC_ADD_LAYER                   1100
#define IDC_ARMAXCTRL                   1107
#define IDC_TEXTURE_PREVIEW             1108
#define IDC_STATIC_1                    1109
#define IDC_STATIC_2                    1110
#define IDC_STATIC_3                    1111
#define IDC_STATIC_4                    1112
#define IDC_STATIC_5                    1113
#define IDC_STATIC_6                    1114
#define IDC_STATIC_7                    1115
#define IDC_FONT_COMMENT_STRING         1117
#define IDC_CUR_WORK_PLANE_RADIO        1119
#define IDC_CUR_WORK_PLANE_RADIO2       1120
#define IDC_CUR_WORK_PLANE_RADIO3       1121
#define IDC_TRANS_WITHOUT_DUBLE_RADIO   1122
#define IDC_TRANS_COPIES_COUNT          1123
#define IDC_TRANS_COPIES_CNT_EDIT       1124
#define IDC_TRANS_COPIES_CNT_SPIN       1125
#define IDC_TRANS_SEL_NEW_CHECK         1126
#define IDC_ROTATE_GLOBAL_ZERO_RADIO    1127
#define IDC_ROTATE_OBJ_CENTERS_RADIO    1128
#define IDC_ROT_X_ANG_EDIT              1129
#define IDC_ROT_Y_ANG_EDIT              1130
#define IDC_ROT_Z_ANG_EDIT              1131
#define IDC_ROT_WITHOUT_DUBLE_RADIO     1132
#define IDC_ROT_COPIES_CNT_EDIT         1133
#define IDC_ROT_COPIES_CNT_SPIN         1134
#define IDC_ROT_SEL_NEW_CHECK           1135
#define IDC_ROT_COPIES_COUNT            1136
#define IDC_WP_XY_VIS_CHECK             1137
#define IDC_WP_YZ_VIS_CHECK             1138
#define IDC_GET_POINT_X_EDIT            1138
#define IDC_WP_XY_VIS_CHECK3            1139
#define IDC_WP_XZ_VIS_CHECK             1139
#define IDC_GET_POINT_Y_EDIT            1139
#define IDC_GET_POINT_Z_EDIT            1140
#define IDC_GET_OBJECTS_FINISH_BUTTON   1155
#define IDC_SCENARIO_COMBO              1156
#define IDC_GET_POINT_X_STATIC          1158
#define IDC_GET_POINT_Y_STATIC          1159
#define IDC_GET_POINT_Z_STATIC          1160
#define IDC_REPORT_EDIT_WIDTH           1163
#define IDC_REPORT_EDIT_HEIGTH          1164
#define IDC_REPORT_EDIT_ZOOM_LEVEL      1165
#define IDC_REPORT_EDIT_GRID_SIZE       1166
#define IDC_REPORT_CHECK_GRID_VISIBLE   1167
#define IDC_REPORT_CHECK_SNAP           1168
#define IDC_REPORT_BUTTON_COLOR_BG      1169
#define IDC_REPORT_BUTTON_COLOR_GRID    1170
#define IDC_REPORT_EDIT_LEFT            1171
#define IDC_REPORT_BUTTON_DEFAULT       1172
#define IDC_REPORT_EDIT_RIGHT           1173
#define IDC_REPORT_EDIT_TOP             1175
#define IDC_REPORT_EDIT_BOTTOM          1176
#define IDC_REPORT_BUTTON_COLOR_MARGIN  1180
#define IDC_REPORT_RADIO_MARGIN         1183
#define IDC_REPORT_RADIO_PAPER          1185
#define IDC_REPORT_RADIO_NONE           1187
#define IDC_REPORT_COMBO_MEASUREMENTS   1190
#define IDC_REPORT_STATIC_BG            1192
#define IDC_REPORT_STATIC_GRID          1194
#define IDC_REPORT_STATIC_MARGIN        1197
#define IDC_REPORT_CHECK_SHOW_MARGINS   1200
#define IDC_REPORT_EDIT_ZOOM_STEP       1203
#define IDC_REPORT_EDIT_CONTENTS        1204
#define IDC_REPORT_EDIT_ROW_THICKNESS   1205
#define IDC_REPORT_COMBO_UNIT_MEASUREMENTS 1213
#define IDC_GET_OBJECTS_LIST            1225
#define IDC_TRANS_VEC_X_LABEL           1226
#define IDC_TRANS_VEC_Y_LABEL           1227
#define IDC_TRANS_SEPARATOR             1228
#define IDC_TRANS_TOP_LABEL             1229
#define IDC_ROT_ANGLES_LABEL            1230
#define IDC_ROT_SEPARATOR_1             1231
#define IDC_ROT_SEPARATOR_2             1232
#define IDC_ROT_X_LABEL                 1233
#define IDC_ROT_Z_LABEL                 1234
#define IDC_SELECT_POINT_FINISH_BUTTON  1235
#define IDC_LIST2                       1236
#define IDC_FONTS_NAMES_LIST            1236
#define IDC_TEMPLATE_NAME_EDIT          1239
#define IDC_DRAFT_TEMPLATES_LIST        1240
#define IDC_REP_TEMPL_TYPE              1241
#define IDC_REP_TEMPL_TYPE2             1242
#define IDC_REP_TEMPL_TYPE3             1243
#define IDC_HOR_REP_FRAME               1244
#define IDC_VER_REP_FRAME               1245
#define IDC_GET_ONE_COMBO               1245
#define IDC_ABOUT_SERIAL                1246
#define IDC_ABOUT_CORE_VERSION          1247
#define IDC_SETUPS_TABS                 1247
#define IDC_THEME_RADIO1                1248
#define IDC_THEME_RADIO2                1249
#define IDC_THEME_RADIO3                1250
#define IDC_THEME_RADIO4                1251
#define IDC_THEME_PIC_FRAME             1252
#define IDC_CURSOR_SIZE_COMBO           1253
#define IDC_CURSOR_TYPE_RADIO1          1254
#define IDC_CURSOR_TYPE_RADIO2          1255
#define IDC_CURSOR_PREVIEW              1256
#define IDC_CURSOR_OUT_COL              1257
#define IDC_SCRIPT_ERRORS_LOG           1257
#define IDC_CURSOR_OUT_COL2             1258
#define IDC_CURSOR_IN_COL               1258
#define IDC_SCRIPT_ERRORS_LOG2          1259
#define IDC_SCRIPT_TRACE_LOG            1259
#define IDC_VER                         1261
#define IDC_RENDER                      1262
#define IDC_START_RENDER                1262
#define IDC_RENDERBMP                   1263
#define IDC_STOP_RENDER                 1264
#define IDC_ANTIALIAS                   1265
#define IDC_BMP_GENTIBASE               1266
#define IDC_BMP_GENTIBASE2              1267
#define IDC_PREVIEW                     1267
#define IDC_SIZEIMG                     1268
#define IDC_RENDRESIZE                  1269
#define IDC_COMBO1                      1271
#define IDB_SPLASH                      2001
#define IDC_VECTOR_X_RADIO              4000
#define IDC_VECTOR_Y_RADIO              4001
#define IDC_TRANS_VEC_X_EDIT            4002
#define IDC_VECTOR_Z_RADIO              4002
#define IDC_TRANS_VEC_Y_EDIT            4003
#define IDC_VECTOR_USER_RADIO           4003
#define IDC_TRANS_VEC_Z_EDIT            4004
#define IDC_VEC_X_STATIC                4004
#define IDC_PNT_X_LOCK_BTN              4005
#define IDC_VEC_Y_STATIC                4005
#define IDC_PNT_Y_LOCK_BTN              4006
#define IDC_VEC_Z_STATIC                4006
#define IDC_PNT_Z_LOCK_BTN              4007
#define IDC_NUMBER_EDIT                 4020
#define IDC_VECTOR_X_EDIT               4022
#define IDC_VECTOR_Y_EDIT               4023
#define IDC_VECTOR_Z_EDIT               4024
#define IDC_VECTOR_Z_LOCK_BTN           4027
#define IDC_VECTOR_Y_LOCK_BTN           4028
#define IDC_VECTOR_X_LOCK_BTN           4029
#define ID_PROPERTIES                   32773
#define ID_DXF_EXPORT                   32788
#define ID_DXF_IMPORT                   32789
#define ID_ADD_NEW_MATERIAL             32790
#define ID_DELETE_CUR_MATERIAL          32791
#define ID_ADD_NEW_TEXTURE              32796
#define ID_DELETE_CUR_TEXTURE           32798
#define ID_PRINT_VIEW_ZOOM_DEFAULT      32801
#define ID_PRINT_VIEW_ZOOM_IN           32802
#define ID_PRINT_VIEW_ZOOM_OUT          32803
#define ID_PRINT_VIEW_MOVE              32804
#define ID_PRINTER_CHANGED              32805
#define ID_SCRIPT_NEW                   32807
#define ID_SCRIPT_OPEN                  32808
#define ID_SAVE_SCRIPT                  32810
#define ID_SAVE_AS_SCRIPT               32811
#define ID_OPEN_SCRIPT                  32812
#define ID_CLOSE_SCRIPT                 32813
#define ID_SCRIPT_HELP                  32814
#define ID_RUN_SCRIPT                   32815
#define ID_WORK_PLANES_SETUPS           32817
#define ID_X_WP_SHOW                    32818
#define ID_Y_WP_SHOW                    32819
#define ID_Z_WP_SHOW                    32820
#define ID_LAYERS                       32830
#define ID_SYSTEM_PANEL                 32831
#define ID_TOCHN1                       32832
#define ID_TOCHN2                       32833
#define ID_CVET                         32834
#define ID_TOLZHINA                     32835
#define ID_TIPLINII                     32836
#define ID_SLOI                         32837
#define ID_PARALL_PROJ                  32838
#define ID_PERSPECT_PROJ                32839
#define ID_FRONT_VIEW                   32840
#define ID_BACK_VIEW                    32841
#define ID_TOP_VIEW                     32842
#define ID_BOTTOM_VIEW                  32843
#define ID_LEFT_VIEW                    32844
#define ID_RIGHT_VIEW                   32845
#define ID_ISO_FRONT_VIEW               32846
#define ID_ISO_BACK_VIEW                32847
#define ID_Menu                         32848
#define ID_MOVE_EYE_HAND                32849
#define ID_ROTATE_EYE_HAND              32850
#define ID_ZOOM_EYE_HAND                32851
#define ID_ALL_SCENE_VIEW               32852
#define ID_ROTATE_Z_AUTO                32855
#define ID_ROTATE_Y_AUTO                32856
#define ID_ROTATE_X_AUTO                32857
#define ID_MOVE_LEFT_AUTO               32858
#define ID_MOVE_RIGHT_AUTO              32859
#define ID_MOVE_UP_AUTO                 32860
#define ID_MOVE_DOWN_AUTO               32861
#define ID_ZOOM_PLUS_AUTO               32862
#define ID_ZOOM_MINUS_AUTO              32863
#define ID_SNAP_NO                      32866
#define ID_SNAP_POINTS                  32867
#define ID_SNAP_ENDS                    32868
#define ID_SNAP_MIDS                    32872
#define ID_DELETE_HOT_OBJECT            32873
#define ID_THIS_PROJECTION_ON_2D        32874
#define ID_END_COMMANDER                32876
#define ID_OBJECT_PROPERTIES            32877
#define ID_CANCEL_COMMANDER             32878
#define ID_SNAP_CENTERS                 32881
#define ID_BUTTON32885                  32885
#define ID_ATTACH_MAT_LIB               32889
#define ID_DETACH_MAT_LIB               32890
#define ID_MAT_EDITOR                   32891
#define ID_COPY_AS_RASTR                32896
#define ID_COPY_AS_VECTOR               32897
#define ID_SAVE_AS_RASTR                32898
#define ID_SAVE_AS_VECTOR               32899
#define ID_32900                        32900
#define ID_32907                        32907
#define ID_TRANSLATE                    32908
#define ID_ROTATE                       32909
#define ID_FONTS                        32911
#define ID_BUTTON32913                  32913
#define ID_ATT_FONTS                    32913
#define ID_BREAK_HOT_GROUP              32915
#define ID_BREAK_HOT_CONTOUR            32916
#define ID_REPORT_FILE_NEW              32918
#define ID_CREATE_GROUP                 32922
#define ID_REPORT_UNDO                  32923
#define ID_REPORT_CUT                   32924
#define ID_REPORT_COPY                  32925
#define ID_REPORT_PASTE                 32926
#define ID_REPORT_LINE                  32927
#define ID_REPORT_RECT                  32928
#define ID_REPORT_LABEL                 32929
#define ID_REPORT_ADD_PAGE              32931
#define ID_REPORT_FILE_OPEN             32932
#define ID_REPORT_SAVE_FILE             32933
#define ID_REPORT_PICTURE               32934
#define ID_SET_MATERIAL_TO_OBJ          32935
#define ID_UNSET_MATERIAL               32936
#define ID_FIT_ONE_OBJ                  32937
#define ID_FONTS_PREVIEW                32939
#define ID_REPORT_GRID                  32941
#define ID_REPORT_SNAP_TO_GRID          32942
#define ID_REPORT_ZOOM_IN               32943
#define ID_REPORT_ZOOM_OUT              32944
#define ID_Menu32945                    32945
#define ID_REPORT_ALIGN_LEFT            32946
#define ID_REPORT_ALIGN_RIGHT           32947
#define ID_REPORT_ALIGN_TOP             32948
#define ID_REPORT_ALIGN_BOTTOM          32949
#define ID_REPORT_ALIGN_SIZES           32950
#define ID_BUTTON32977                  32977
#define ID_SHOW_SCENE_PANEL             32978
#define ID_SHOW_COMMAND_PANEL           32979
#define ID_SHOW_SCRIPT_PANEL            32980
#define ID_SETUPS                       32981
#define ID_RAY_TRACE_START              32982
#define ID_STL_IMPORT                   32983
#define ID_STL_EXPORT                   32984
#define START_ID_FOR_FRAMES_TOOLBARS    39000
#define START_ID_FOR_COMMANDER_CONTEXT_MENU 39500
#define START_ID_FOR_PLUGINS_MENU       40000
#define START_ID_FOR_PLUGINS_TOOLBARS   41000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        297
#define _APS_NEXT_COMMAND_VALUE         32985
#define _APS_NEXT_CONTROL_VALUE         1272
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
