//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Next2Friends.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Next2Friends.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Ask Question comments exist with the AskAFriendCommentID = {0}..
        /// </summary>
        internal static string Argument_InvalidAskQuestionCommentID {
            get {
                return ResourceManager.GetString("Argument_InvalidAskQuestionCommentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Blog Comment exists with CommentID = {0}..
        /// </summary>
        internal static string Argument_InvalidBlogCommentID {
            get {
                return ResourceManager.GetString("Argument_InvalidBlogCommentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accountType should be one of the following values: 0 - None, 1 - Twitter..
        /// </summary>
        internal static string Argument_InvalidMemberAccountType {
            get {
                return ResourceManager.GetString("Argument_InvalidMemberAccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activityType should be one of the following values: 0 - None, 1 - Video, 2 - PhotoGallery, 3 - Photo, 4 - Status..
        /// </summary>
        internal static string Argument_InvalidMemberActivityType {
            get {
                return ResourceManager.GetString("Argument_InvalidMemberActivityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No NSpot exists with NSpotCommentID = {0}..
        /// </summary>
        internal static string Argument_InvalidNSpotCommentID {
            get {
                return ResourceManager.GetString("Argument_InvalidNSpotCommentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAF does not exist with WebAskAFriendID = {0}..
        /// </summary>
        internal static string Argument_InvalidWebAskID {
            get {
                return ResourceManager.GetString("Argument_InvalidWebAskID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no InviteClick in the database with the WebInviteClickID = {0}..
        /// </summary>
        internal static string Argument_InvalidWebInviteClickID {
            get {
                return ResourceManager.GetString("Argument_InvalidWebInviteClickID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Member exists with WebMemberID = {0}..
        /// </summary>
        internal static string Argument_InvalidWebMemberID {
            get {
                return ResourceManager.GetString("Argument_InvalidWebMemberID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No NSpot exists with WebNSpotID = {0}..
        /// </summary>
        internal static string Argument_InvalidWebNSpotID {
            get {
                return ResourceManager.GetString("Argument_InvalidWebNSpotID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no ISOCountry in the database with the ISOCode = {0}..
        /// </summary>
        internal static string Argument_NoISOCountry {
            get {
                return ResourceManager.GetString("Argument_NoISOCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no MemberSettings for MemberID = {0}..
        /// </summary>
        internal static string Argument_NoMemberSettingsForMemberID {
            get {
                return ResourceManager.GetString("Argument_NoMemberSettingsForMemberID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user with the specified EmailAddress and Password does not exist..
        /// </summary>
        internal static string BadCredentials_InvalidEmailAddressOrPassword {
            get {
                return ResourceManager.GetString("BadCredentials_InvalidEmailAddressOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user with the specified Nickname does not exist..
        /// </summary>
        internal static string BadCredentials_InvalidNickname {
            get {
                return ResourceManager.GetString("BadCredentials_InvalidNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user with the specified Nickname or Password does not exist..
        /// </summary>
        internal static string BadCredentials_InvalidNicknameOrPassword {
            get {
                return ResourceManager.GetString("BadCredentials_InvalidNicknameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user with the specified WebMemberID or Password does not exist..
        /// </summary>
        internal static string BadCredentials_InvalidWebMemberIDOrPassword {
            get {
                return ResourceManager.GetString("BadCredentials_InvalidWebMemberIDOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For some strange reason there is no Member Profile for this member, Bad DB relationship?.
        /// </summary>
        internal static string InvalidOperation_BadDbRelationship {
            get {
                return ResourceManager.GetString("InvalidOperation_BadDbRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Ask Questions! How did this ever happen!.
        /// </summary>
        internal static string InvalidOperation_NoAskQuestions {
            get {
                return ResourceManager.GetString("InvalidOperation_NoAskQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This object cannot be created as its parent object is null..
        /// </summary>
        internal static string InvalidOperation_ParentObjectIsNull {
            get {
                return ResourceManager.GetString("InvalidOperation_ParentObjectIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not write file to &quot;{0}&quot;..
        /// </summary>
        internal static string IO_WriteFileErrorToSavePath {
            get {
                return ResourceManager.GetString("IO_WriteFileErrorToSavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find or access registry key &quot;{0}&quot;..
        /// </summary>
        internal static string Win32_CannotFindOrAccessRegKey {
            get {
                return ResourceManager.GetString("Win32_CannotFindOrAccessRegKey", resourceCulture);
            }
        }
    }
}
