<%@ Page Language="C#" MasterPageFile="~/Main.master" AutoEventWireup="true" CodeFile="PP.aspx.cs" Inherits="PP" Title="Untitled Page" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">


<!-- middle start -->
	<div id="middle" class="no_Subnav clearfix">



		<!-- page start -->
		<div class="page clearfix fullPageBkg">
		    <h2>Privacy Policy:</h2>
	        <p></p>
            <p>Registration Information/Privacy Policy Collection of Personal Information</p>
            <p>When you engage in certain activities on this site, such as ordering services, downloading software, or entering contests, Next2Friends Limited may ask you to provide certain information about yourself by filling out and submitting an online form. It is completely optional for you to engage in these activities. If you elect to engage in these activities, however, Next2Friends Limited may require that you provide certain personal information, such as your name, mailing address, e-mail address, and other personal identifying information. When ordering services on the web site, you may be asked to provide a credit card number or other details of payment mechanisms.</p>
            <p>In some countries, Next2Friends Limited is represented by an exclusive reseller who provides marketing, sales, and support services on behalf of Next2Friends Limited in the interest of providing better service to customers residing in that country. When you submit personal information to Next2Friends Limited, you understand and agree that if you reside in a country where Next2Friends Limited is represented by an exclusive reseller, Next2Friends Limited may forward your customer profile to that reseller.</p>
            <p>Your personal information will not be leased, sold, rented or otherwise made available to any other third party except to the extent necessary to comply with applicable laws, police investigations, or in legal proceedings where such information is relevant.</p>
            <p>Occasionally, Next2Friends Limited allows access to database information to bonded mailing houses only for the purpose of allowing for the printing of mailing labels that are used for Next2Friends Limited’s own direct mail and promotional purposes. In those instances, the third party is bound by these terms. All information collected, regardless of type, will be protected pursuant to the Privacy Act and the Freedom of Information Act. Next2Friends Limited collects this information in order to record and support your participation in the activities you select. If you order a product, for example, the information is used to register your license and rights, if any, to upgrade discounts, technical support, or other benefits that may be made available to registered users. If you enter a contest, information is collected to qualify the entry and contact you regarding the contest or prize awards.</p>
            <p>Next2Friends Limited also uses information that you provide as part of our effort to keep you informed about product upgrades, special offers, and other Next2Friends Limited services and services. Other provisions contained herein to the contrary notwithstanding, you hereby agree that Next2Friends Limited may assign, sell, license, or otherwise transfer to a third party, your name, address, email address, member name and any other personal information in connection with an assignment, sale, joint venture, or other transfer or disposition of a material portion or essentially all of the assets or stock of Next2Friends Limited or its affiliated entities.</p>
            <p>Your personally identifying information will not be used by Next2Friends Limited for editorial purposes unless you first agree in writing. Next2Friends Limited may also use such information for Next2Friends Limited promotional and marketing purposes. Next2Friends Limited respects your privacy.</p>
            <p>We recognize and appreciate the importance of responsible use of this information and realize that not everyone likes to receive special offers or information about Next2Friends Limited services. If you would like your name deactivated from Next2Friends Limited’s lists, or if you would like to unsubscribe from Next2Friends Limited’s e-mail bulletins, please use the contact information below to request that Next2Friends Limited deactivate you from its lists. Be sure to include your name, postal address, telephone number, information contained in your Next2Friends Limited mailer, and/or other necessary information needed for deactivation. Next2Friends Limited will use reasonable efforts to honor your requests, but we appreciate your patience in allowing us a reasonable amount of time for processing. You should be aware that when you voluntarily disclose personal information (e.g., user name, e-mail address, physical address, etc.) publicly on Next2Friends Limited’s discussion forum, that information can be viewed and used by others and may result in unsolicited messages from other posters or parties.</p>
            <p>Use of Cookies – When you visit Next2Friends.com, you can surf the site anonymously and access important information without revealing your identity. In order to analyze and improve our site, we use “cookies” to track your visit. A cookie is small amount of data that is transferred to your browser by a Web server and can only be read by the server that gave it to you. It cannot be executed as code or deliver viruses. Most browsers are initially set to accept cookies. You can set your browser to notify you when you receive a cookie, giving you the chance to decide whether or not to accept it. (For some Web pages that require an authorization, cookies are not optional. Users choosing not to accept cookies will not be able to access those pages.) While Next2Friends Limited uses cookies to track your visit to Next2Friends.com, and our Web servers automatically log the IP/Internet address of your computer, this information does not identify you personally and you remain anonymous unless you have otherwise provided Next2Friends Limited with personal information. Please note that Next2Friends Limited is not responsible for the content or privacy practices of non-Next2Friends Limited Web sites to which Next2Friends.com may link.</p>
            <p>Next2Friends Limited</p>
            <p>Copyright © 2007 Next2Friends Limited All Rights Reserved. All third-party trademarks within this Site are copyrights of their respective owners and are subject to each mark holder’s respective terms of use.</p>
        </div>
    </div>
</asp:Content>
