#ifndef __FOOTER_PROPS__
#define __FOOTER_PROPS__

#include "stringres.h"

#define SOFT_KEYS_CHECK_ANCHOR	0x2F92

const int16 SOFT_KEYS_ID[] = //POSITIVE SOFT, NEGATIVE SOFT
{
		IDS_MORE,			IDS_EXIT /*ESN_TITLE*/
	,	IDS_MORE,			IDS_EXIT /*ESN_MAIN_MENU*/
	,	IDS_MORE,			IDS_BACK /*ESN_GO*/
	,	IDS_MORE,			IDS_BACK /*ESN_CREDENTIALS*/
	,	IDS_MORE,			IDS_BACK /*ESN_REMIND_PASSWORD*/
	,	IDS_MORE,			IDS_BACK /*ESN_ASK*/
	,	IDS_SUBMIT,			IDS_BACK /*ESN_TEMPLATES*/
	,	IDS_MORE,			IDS_BACK /*ESN_DRAFTS*/
	,	IDS_MORE,			IDS_BACK /*ESN_ATTACH_FROM_FILE*/
	,	IDS_MORE,			IDS_BACK /*ESN_VIEW_PHOTO*/
	,	IDS_TAKE_SHOT,		IDS_BACK /*ESN_CAMERA*/
	,	IDS_MORE,			IDS_BACK /*ESN_OUTBOX*/
	,	IDS_MORE,			IDS_BACK /*ESN_INBOX*/
	,	IDS_MORE,			IDS_BACK /*ESN_DASHBOARD*/
	,	IDS_SELECT,			IDS_BACK /*ESN_SEND_SELECTION*/
	,	IDS_EMPTY_STRING,	IDS_BACK /*ESN_DASHBOARD_READ*/
	,	IDS_COMMENT,		IDS_BACK /*ESN_RESPONSE*/
	,	IDS_SUBMIT,			IDS_BACK /*ESN_WRITE_COMMENT*/
	,	IDS_CHANGE,			IDS_BACK /*ESN_CHANGE_STATUS*/
	,	IDS_SELECT,			IDS_BACK /*ESN_SNAP_UP*/

	,	SOFT_KEYS_CHECK_ANCHOR//check code
};


#endif