#ifndef _GUI_DATA_H_
#define _GUI_DATA_H_

#include "BaseTypes.h"

// #define BACK_LEFT

enum eControlParams
{

	ECP_TEXT_SPACE					= 5,
	ECP_MENULIST_MARGIN				= 3,
	ECP_EDITTEXT_MARGIN_SIDE		= 7,
	ECP_EDITTEXT_MARGIN_TOP			= 2,
	ECP_EDITTEXT_MARGIN_BOTTOM		= 3,

	ECP_LISTVIEW_PRESCROLL			= 46,
	ECP_SCROLL_WIDTH				= 4,


    ECP_COUNT
};

enum eControlIDs
{
	ECIDS_TEXT_ID					= 237,
	ECIDS_FIRST_SCREEN_ID			= 1000,
	ECIDS_MENU_ITEM_ID				= 5000,
	ECIDS_GO_ITEM_ID				= 5100,
	ECIDS_CREDENTIALS_ITEM_ID		= 5200,
	ECIDS_REMIND_PASSWORD_ITEM_ID	= 5300,
	ECIDS_ASK_ITEM_ID				= 5400,
	ECIDS_TEMPLATES_ITEM_ID			= 5500,
	ECIDS_DRAFTS_ITEM_ID			= 5600,
	ECIDS_ATTACH_FROM_FILE_ITEM_ID	= 5700,
	ECIDS_SELECT_SEND_ITEM_ID		= 5800,
	ECIDS_DASHBOARD_READ_ITEM_ID	= 5900,
	ECIDS_RESPONSE_ITEM_ID			= 6000,
	ECIDS_WRITE_COMMENT_ITEM_ID		= 6100,
	ECIDS_POPUP_ITEM_TEXT_ID		= 8000,
	ECIDS_POPUP_ITEM_ID				= 8010,
	ECIDS_ILIST_ITEM_ID				= 9000,
	ECIDS_HEADER_ID					= 10000,
	ECIDS_FOOTER_ID					= 10100
};



#endif //_GUI_DATA_H_
