#ifndef __GUI_TYPES__
#define __GUI_TYPES__

#include "BaseTypes.h"

enum eDrawType
{
	EDT_DEFAULT = 0,
	EDT_NONE,
	EDT_TEXT,
	EDT_CONTROL,
	EDT_DISABLED_CONTROL,
	EDT_IMAGE,
	EDT_SCROLL,
	EDT_SCROLL_BAR,
	EDT_HEADER,
	EDT_HEADER_TEXT,
	EDT_FOOTER_BUTTON_LEFT,
	EDT_FOOTER_BUTTON_RIGHT,
	EDT_SELECTED_ITEM,
	EDT_SELECTED_TEXT,
	EDT_UNSELECTED_TEXT,
	EDT_POPUP_BORDER,
	EDT_ALERT_BORDER,
	EDT_POPUP_ITEM,
	EDT_POPUP_SELECTED_TEXT,
	EDT_POPUP_UNSELECTED_TEXT,
	EDT_LOADING_BAR,
	EDT_EDITBOX,
	EDT_EDITBOX_ACTIVE,
	EDT_MULTIEDIT,
	EDT_CHECKBOX_CHECKED,
	EDT_CHECKBOX_UNCHECKED,
	EDT_CAPS_TEXT,
	EDT_TAB_BACK,
	EDT_TAB_SELECTOR,
	EDT_PHOTO_ITEM,

	EDT_COUNT

};


enum eFont1
{
	EF1_BLACK = 0,
	EF1_WHITE,
	EF1_RED
};

enum eFontSmall
{
	EFS_BLACK = 0,
	EFS_WHITE
};

enum eEditTextType
{
	EETT_ALL			=	0,
	EETT_LOGIN			=	1,
	EETT_DIGITS			=	2
};

enum eLengthParams
{
	ELP_DEFAULT_MAX_TEXT = 255
};

static const int32	LIGHT_UP_SPEED		= 2;
static const int32	LIGHT_DOWN_SPEED	= 3;


enum eEventID
{
	EEI_NONE = 0,
	EEI_CLR_PRESSED,
	EEI_SELECT_PRESSED,
	EEI_SOFT1_PRESSED,
	EEI_SOFT2_PRESSED,

	EEI_CHAR,


	EEI_BUTTON_PRESSED,

	EEI_TEXT_CHANGED,

	EEI_BOTTOM_REACH,
	EEI_TOP_REACH,
	EEI_LEFT_REACH,
	EEI_RIGHT_REACH,

	//EEI_WINDOW_ACTIVATED,
	//EEI_WINDOW_DEACTIVATED,
	EEI_WINDOW_WILL_ACTIVATE,
	EEI_WINDOW_DID_ACTIVATE,
	EEI_WINDOW_WILL_DEACTIVATE,
	EEI_WINDOW_DID_DEACTIVATE,

	EEI_WINDOW_SET_MAIN,
	EEI_WINDOW_LOST_MAIN,

	EEI_TRANSITION_FINISHED,

	EEI_TAB_PAGE_SWITCHED,

	EEI_SELECTOR_CHANGED,



	EEI_N2FMESSAGE_CHANGED,
	EEI_N2FMESSAGE_COUNT_CHANGED,

	EEI_LOCK_WINDOW_CANCELED,

	EEI_COUNT
};

struct EventData 
{
	uint32	lParam;		//!< l-param
	uint32	wParam;		//!< w-param
	EventData(uint32 _lParam=0, uint32 _wParam=0)
	{
		lParam = _lParam;
		wParam = _wParam;
	}
};
#endif
