#ifndef _N2F_DATA_H_
#define _N2F_DATA_H_

#include "BaseTypes.h"



enum eN2FParams
{
	  ENP_MAX_TEMPLATES				= 20
	, ENP_MAX_QUESTION_SIZE			= 500
	, ENP_MAX_STATUS_SIZE			= 50
	, ENP_MAX_LOGIN_SIZE			= 50
	, ENP_MAX_PASSWORD_SIZE			= 50
	, ENP_MAX_EMAIL_SIZE			= 50
	, ENP_MAX_PHONE_NUMBER_SIZE		= 50
	, ENP_MAX_ADDTEXT_SIZE			= 50
	, ENP_MAX_N2F_MESSAGES			= 150
	, ENP_MAX_QUESTION_ID_SIZE		= 50
	, ENP_MAX_PHOTO_SIZE			= 100 * 1024
	, ENP_MAX_PHOTO_WIDTH			= 640
	, ENP_MAX_PHOTO_HEIGHT			= 480
};



#endif //_GUI_DATA_H_
