/* soapMemberServicesSoapProxy.h
   Generated by gSOAP 2.7.10 from output\memberservice.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapMemberServicesSoapProxy_H
#define soapMemberServicesSoapProxy_H
#include "soapH.h"

class SOAP_CMAC MemberServicesSoapProxy : public soap
{ public:
	/// Endpoint URL of service 'MemberServicesSoapProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	MemberServicesSoapProxy();
	/// Constructor with copy of another engine state
	MemberServicesSoapProxy(const struct soap&);
	/// Constructor with engine input+output mode control
	MemberServicesSoapProxy(soap_mode iomode);
	/// Constructor with engine input and output mode control
	MemberServicesSoapProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~MemberServicesSoapProxy();
	/// Initializer used by constructor
	virtual	void MemberServicesSoapProxy_init(soap_mode imode, soap_mode omode);
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Force close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
	virtual	void soap_stream_fault(std::ostream&);
	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'GetEncryptionKey' (returns error code or SOAP_OK)
	virtual	int GetEncryptionKey(_ns1__GetEncryptionKey *ns1__GetEncryptionKey, _ns1__GetEncryptionKeyResponse *ns1__GetEncryptionKeyResponse);

	/// Web service operation 'GetMemberID' (returns error code or SOAP_OK)
	virtual	int GetMemberID(_ns1__GetMemberID *ns1__GetMemberID, _ns1__GetMemberIDResponse *ns1__GetMemberIDResponse);

	/// Web service operation 'GetTagID' (returns error code or SOAP_OK)
	virtual	int GetTagID(_ns1__GetTagID *ns1__GetTagID, _ns1__GetTagIDResponse *ns1__GetTagIDResponse);
};
#endif
