// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package n2f.tag.webservice.stub;


public class ArrayOfString {
    protected java.lang.String[] string;
    
    public ArrayOfString() {
    }
    
    public ArrayOfString(java.lang.String[] string) {
        this.string = string;
    }
    
    public java.lang.String[] getString() {
        return string;
    }
    
    public void setString(java.lang.String[] string) {
        this.string = string;
    }
}
