// This class was generated by 172 StubGenerator.
// Contents subject to change without notice.
// @generated

package n2f.tag.webservice.stub;

public interface EditBlockListSoap extends java.rmi.Remote {
	public n2f.tag.webservice.stub.ArrayOfDeviceBlockItem getBlockList(java.lang.String webMemberID, java.lang.String webPassword) throws java.rmi.RemoteException;

}
