// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package n2f.tag.webservice.stub;


public class MemberBlock {
    protected int memberBlockID;
    protected int memberID;
    protected int blockMemberID;
    protected java.util.Calendar DTCreated;
    
    public MemberBlock() {
    }
    
    public MemberBlock(int memberBlockID, int memberID, int blockMemberID, java.util.Calendar DTCreated) {
        this.memberBlockID = memberBlockID;
        this.memberID = memberID;
        this.blockMemberID = blockMemberID;
        this.DTCreated = DTCreated;
    }
    
    public int getMemberBlockID() {
        return memberBlockID;
    }
    
    public void setMemberBlockID(int memberBlockID) {
        this.memberBlockID = memberBlockID;
    }
    
    public int getMemberID() {
        return memberID;
    }
    
    public void setMemberID(int memberID) {
        this.memberID = memberID;
    }
    
    public int getBlockMemberID() {
        return blockMemberID;
    }
    
    public void setBlockMemberID(int blockMemberID) {
        this.blockMemberID = blockMemberID;
    }
    
    public java.util.Calendar getDTCreated() {
        return DTCreated;
    }
    
    public void setDTCreated(java.util.Calendar DTCreated) {
        this.DTCreated = DTCreated;
    }
}
