
Dependencies:

You need several libraries to build GLStereoPlayer.  Befor building the GLStereoPlayer applications
and library, you have to set the following libraries property and set your include and library path
to them.

    * Microsoft Platform SDK
      http://www.microsoft.com/msdownload/platformsdk/sdkupdate/

    * Microsoft DirectX SDK
      http://msdn.microsoft.com/directx/
      Pre-compiled version was built with Microsoft DirectX 9.0 SDK Update (February 2005).
      If you want to build with VisualC++6, try to use Microsoft DirectX 9.0 SDK Update (Summer 2003).
      You have to build its 'Samples/C++/DirectShow/BaseClasses/baseclasses.dsw' and
      set the include and library path to here and its output directories.

    * Developer's Image Library (DevIL)
      http://openil.sourceforge.net/
      Pre-compiled version was built with DevIL ver.1.6.7.

    Optional:

    * OpenGL Utility Toolkit (GLUT)
      http://www.xmission.com/~nate/glut.html
      'glutStereoPlayer' needs this library.

    * OpenGL Extension Wrangler Library (GLEW)
      http://glew.sourceforge.net/
      Pre-compiled version does not use this library. You'll need it if you want to use Pixel Buffer Object extension.


Build:

To build the GLStereoPlayer, you need Microsoft VisualC++6.0 or later.
Open 'projects/standalone/GLStereoPlayer.dsw' to build an MFC standalone application of the GLStereoPlayer.
Open 'projects/activex/GLStereoPlayerAX.dsw' to build an ActiveX component of the GLStereoPlayer.
Open 'projects/glut/glutStereoPlayer.dsw' to build a simple glut example of the GLStereoPlayer.

When you build each of them, its outputs will be placed in 'bin' directory.

