//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genetibase.Controls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Genetibase.Controls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified {0} does not belong to this {1}..
        /// </summary>
        internal static string Argument_InvalidTabPage {
            get {
                return ResourceManager.GetString("Argument_InvalidTabPage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Blank {
            get {
                object obj = ResourceManager.GetObject("Blank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Blank).
        /// </summary>
        internal static string BlankText {
            get {
                return ResourceManager.GetString("BlankText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Category_Action {
            get {
                return ResourceManager.GetString("Category_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string Category_Appearance {
            get {
                return ResourceManager.GetString("Category_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Changed.
        /// </summary>
        internal static string Category_PropertyChanged {
            get {
                return ResourceManager.GetString("Category_PropertyChanged", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap CloseButton_Hot {
            get {
                object obj = ResourceManager.GetObject("CloseButton_Hot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CloseButton_Normal {
            get {
                object obj = ResourceManager.GetObject("CloseButton_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CloseButton_Pressed {
            get {
                object obj = ResourceManager.GetObject("CloseButton_Pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The items within the Nodes collection should be compatible with Genetibase.Controls.NuGenTreeNode type..
        /// </summary>
        internal static string InvalidCast_NodeType {
            get {
                return ResourceManager.GetString("InvalidCast_NodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual styles are not currently available..
        /// </summary>
        internal static string InvalidOperation_VisualStyles {
            get {
                return ResourceManager.GetString("InvalidOperation_VisualStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines whether to show a close button for every tab..
        /// </summary>
        internal static string NuGenTabControl_CloseButtonOnTab_Description {
            get {
                return ResourceManager.GetString("NuGenTabControl_CloseButtonOnTab_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines the tab control appearance..
        /// </summary>
        internal static string NuGenTabControl_FlatStyle_Description {
            get {
                return ResourceManager.GetString("NuGenTabControl_FlatStyle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the value of the FlatStyle property changes..
        /// </summary>
        internal static string NuGenTabControl_FlatStyleChanged_Description {
            get {
                return ResourceManager.GetString("NuGenTabControl_FlatStyleChanged_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when a new tab page is added..
        /// </summary>
        internal static string NuGenTabControl_TabPageAdded_Description {
            get {
                return ResourceManager.GetString("NuGenTabControl_TabPageAdded_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when a tab page is removed..
        /// </summary>
        internal static string NuGenTabControl_TabPageRemoved_Description {
            get {
                return ResourceManager.GetString("NuGenTabControl_TabPageRemoved_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add TabPage.
        /// </summary>
        internal static string NuGenTabControlActionList_AddTabPage {
            get {
                return ResourceManager.GetString("NuGenTabControlActionList_AddTabPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove TabPage.
        /// </summary>
        internal static string NuGenTabControlActionList_RemoveTabPage {
            get {
                return ResourceManager.GetString("NuGenTabControlActionList_RemoveTabPage", resourceCulture);
            }
        }
    }
}
