// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package n2f.tag.webservice.stub;


public class ArrayOfBTTagConfirmation {
    protected n2f.tag.webservice.stub.BTTagConfirmation[] BTTagConfirmation;
    
    public ArrayOfBTTagConfirmation() {
    }
    
    public ArrayOfBTTagConfirmation(n2f.tag.webservice.stub.BTTagConfirmation[] BTTagConfirmation) {
        this.BTTagConfirmation = BTTagConfirmation;
    }
    
    public n2f.tag.webservice.stub.BTTagConfirmation[] getBTTagConfirmation() {
        return BTTagConfirmation;
    }
    
    public void setBTTagConfirmation(n2f.tag.webservice.stub.BTTagConfirmation[] BTTagConfirmation) {
        this.BTTagConfirmation = BTTagConfirmation;
    }
}
