// This class was generated by 172 StubGenerator.
// Contents subject to change without notice.
// @generated

package n2f.tag.webservice.stub;

public interface BTTagSendSoap extends java.rmi.Remote {
	public n2f.tag.webservice.stub.ArrayOfBTTagConfirmation uploadBTTags(java.lang.String webMemberID, java.lang.String webPassword, n2f.tag.webservice.stub.BTTagUpdate BTTags) throws java.rmi.RemoteException;

}
