// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package n2f.tag.webservice.stub;


public class DeviceBlock {
    protected int deviceBlockID;
    protected java.lang.String deviceTagID;
    protected int memberID;
    protected int blockingMemberID;
    protected java.lang.String MACAddress;
    protected java.util.Calendar DTCreated;
    
    public DeviceBlock() {
    }
    
    public DeviceBlock(int deviceBlockID, java.lang.String deviceTagID, int memberID, int blockingMemberID, java.lang.String MACAddress, java.util.Calendar DTCreated) {
        this.deviceBlockID = deviceBlockID;
        this.deviceTagID = deviceTagID;
        this.memberID = memberID;
        this.blockingMemberID = blockingMemberID;
        this.MACAddress = MACAddress;
        this.DTCreated = DTCreated;
    }
    
    public int getDeviceBlockID() {
        return deviceBlockID;
    }
    
    public void setDeviceBlockID(int deviceBlockID) {
        this.deviceBlockID = deviceBlockID;
    }
    
    public java.lang.String getDeviceTagID() {
        return deviceTagID;
    }
    
    public void setDeviceTagID(java.lang.String deviceTagID) {
        this.deviceTagID = deviceTagID;
    }
    
    public int getMemberID() {
        return memberID;
    }
    
    public void setMemberID(int memberID) {
        this.memberID = memberID;
    }
    
    public int getBlockingMemberID() {
        return blockingMemberID;
    }
    
    public void setBlockingMemberID(int blockingMemberID) {
        this.blockingMemberID = blockingMemberID;
    }
    
    public java.lang.String getMACAddress() {
        return MACAddress;
    }
    
    public void setMACAddress(java.lang.String MACAddress) {
        this.MACAddress = MACAddress;
    }
    
    public java.util.Calendar getDTCreated() {
        return DTCreated;
    }
    
    public void setDTCreated(java.util.Calendar DTCreated) {
        this.DTCreated = DTCreated;
    }
}
