//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Standard2D.rc
//
#define IDS_CIRC_SCENAR_CEN_RAD_NORM    1
#define IDS_CIRC_SCENAR_THREE_POINTS    2
#define IDS_CENTER                      3
#define IDS_LINE_SCENAR_TWO_POINTS      4
#define IDS_FIRST_POINT                 5
#define IDS_SECOND_POINT                6
#define IDS_INCREASE                    7
#define IDS_DIR                         8
#define IDS_LENGTH                      9
#define IDS_LINE_SCENSG_POINT_DXDYDZ    10
#define IDS_LINE_SCENSG_POINT_DIR_LEN   11
#define IDS_RADIUS                      12
#define IDS_DIAMETR                     13
#define IDS_NORMAL                      14
#define IDS_THIRD_POINT                 15
#define IDS_NEW_COORDINATES             16
#define IDS_CHANGE_COORDS               17
#define IDS_CHANGE_COOR_1               18
#define IDS_CHANGE_COOR_2               19
#define IDS_CHANGE_CENTER_COORDS        20
#define IDS_CHANGE_RAD                  21
#define IDS_CHANGE_NORM                 22
#define IDS_NEW_RAD                     23
#define IDS_NEW_NORMAL                  24
#define IDS_ERROR_ZERO_LENGTH           25
#define IDS_ERROR_ZERO_VECTOR           26
#define IDS_ERROR_ZERO_RADIUS           27
#define IDS_ENTER_NEW_COORDS            28
#define IDS_REDACTION                   29
#define IDS_QEUID_GET_OBJ               30
#define IDS_EQUID_GET_H                 31
#define IDS_EQUID_H                     32
#define IDS_SPLINE_EXISTING_KNOTS       33
#define IDS_ERROR_INFIN_RAD             34
#define IDS_POINT_ON_ARC                35
#define IDS_ARC_SCENAR_B_E_M            36
#define IDS_BEG_POINT                   37
#define IDS_END_POINT                   38
#define IDS_SPL_NEW_KNOT                39
#define IDS_SPL_ENTER_NEW_KNOT          40
#define IDS_INVERT                      41
#define IDS_ARC_SCENAR_C_B_E            42
#define IDS_CHANGE_ARC_POINT_COORD      43
#define IDS_LINE_SCENAR_OTHER_LINE_EXT  44
#define IDS_LINE_SCENAR_PERPEND_OTHER_LINE 45
#define IDS_LINE_SCENSG_ARC_EXT         46
#define IDS_LINE_SCENAR_PERPEND_ARC     47
#define IDS_CHOISE_LINE                 48
#define IDS_CHOISE_ARC                  49
#define IDS_CHOISE_LINE_PNT             50
#define IDS_CHOISE_ARC_PNT              51
#define IDS_ERROR_OBJ_NOT_SEL           52
#define IDS_END_OPER                    53
#define IDS_ERROR_SPL_KNOT_AS_PREV      54
#define IDS_WARNING_CHOISE_SCREEN_POINT 55
#define IDS_ARC_SCENAR_OTHER_ARC_EXT    56
#define IDS_ARC_SCENAR_PERPEND_OTHER_ARC 57
#define IDS_ARC_SCENSG_LINE_EXT         58
#define IDS_ARC_SCENAR_PERPEND_LINE     59
#define IDS_CLOSE_SPLINE                60
#define IDS_WANT_MORE_POINTS            61
#define IDS_CHOISE_SPLINE_PNT           62
#define IDS_CREARE_SPL_ERROR            63
#define IDS_MOVE_SPLINE_KNOT            64
#define IDS_N_IY_KNOT                   65
#define IDS_TOOLTIP_FIVETH              66
#define IDS_TOOLTIP_SIXTH               67
#define IDS_STBAR_FIVETH                68
#define IDS_STBAR_SIXTH                 69
#define IDS_CHOISE_FIRST_OBJ_OF_PATH    70
#define IDS_CLOSE_CONTOUR               71
#define IDS_STBAR_SEVENTH               72
#define IDS_STBAR_EIGHTTH               73
#define IDS_TOOLTIP_SEVETH              74
#define IDS_TOOLTIP_EIGHTTH             75
#define IDS_OBJECT                      76
#define IDS_FIRST_SHIFT                 77
#define IDS_SECOND_SHIFT                78
#define IDS_COORDS                      79
#define IDS_CLOSING_SPLINE              80
#define IDS_FLATING_SPLINE              81
#define IDS_NO_SELF_INTERS_SPLINE       82
#define IDS_NO_CLOSING_SPLINE           83
#define IDS_NO_FLATING_SPLINE           84
#define IDS_SELF_INTERS_SPLINE          85
#define IDS_CANNT_CLOSE_SPLINE          86
#define IDS_ENTER_POINT_COORDS          87
#define IDS_ARC_ENTER_NWE_POINT         88
#define IDS_CONT_SCENAR                 89
#define IDS_CONT_OBJ_TYPE               90
#define IDS_PREV                        91
#define IDS_ARC_ERR_ON_LINE             92
#define IDS_ERR_PNT_AS_PREV             93
#define IDS_ERR_PATH_NO_OBJ             94
#define IDS_ERR_PATH_ONE_OBJ            95
#define IDS_CIR_ENTER_CENTER            96
#define IDS_CIR_ENTER_NORMAL            97
#define IDS_CIR_ENTER_RAD               98
#define IDS_CIR_NEW_CENTER              99
#define IDS_CIR_NEW_NORM                100
#define IDS_CIR_NEW_RAD                 101
#define IDS_ARC_ERR_SEC_P_AS_FIR        102
#define IDS_EQ_ERR                      103
#define IDS_EQ_ERR_NO_OBJ               104
#define IDR_TOOLBAR                     4020
#define IDC_SPLINE_POINTS_LIST          4035
#define IDC_CONT_SCENARS_RADIO1         4036
#define IDC_CONT_SCENARS_RADIO2         4037
#define IDC_CONT_OBJ_RADIO1             4038
#define IDC_CONT_OBJ_RADIO2             4039
#define IDB_LINE_TWO_PNTS               4049
#define IDB_LINE_ARC_EXT                4050
#define IDB_LINE_ARC_PERP               4051
#define IDB_LINE_LINE_EXT               4052
#define IDB_LINE_LINE_PERP              4053
#define IDB_LINE_POINT_INC              4054
#define IDB_LINE_POINT_VECTOR           4055
#define IDB_CIRC_CEN_RAD                4063
#define IDB_CIRC_3P                     4065
#define IDB_PNT_EDIT                    4068
#define IDB_LINE_EDIT                   4069
#define IDB_CIRC_EDIT_RAD               4070
#define IDB_CIRC_EDIT_CEN               4071
#define IDB_CIRC_EDIT_NORM              4072
#define IDB_SPL_EDIT                    4076
#define IDB_TOOLBAR32_BMP               4077
#define IDD_SPLINE_POINTS_DLG           4078
#define IDD_CONT_SCENARS_DLG            4079
#define IDD_CONT_OBJ_TYPE               4080
#define IDB_ARC32                       4081
#define IDB_CIRC32                      4082
#define IDB_LINE32                      4083
#define IDB_PATH32                      4084
#define IDB_PNT32                       4085
#define IDB_SPL32                       4086
#define ID_BUTTON_0                     32783
#define ID_BUTTON_1                     32784
#define ID_BUTTON_2                     32785
#define ID_BUTTON_3                     32786
#define ID_BUTTON_4                     32787
#define ID_BUTTON_5                     32788
#define ID_BUTTON_6                     32789
#define ID_BUTTON_7                     32790
#define ID_BUTTON_8                     32791
#define IDS_MENU_STRING                 33775
#define IDS_STBAR_ZERO                  33776
#define IDS_TOOLTIP_ZERO                33777
#define IDS_STBAR_FIRST                 33778
#define IDS_STBAR_SECOND                33779
#define IDS_TOOLTIP_FIRST               33780
#define IDS_TOOLTIP_SECOND              33781
#define IDS_STBAR_THIRD                 33786
#define IDS_STBAR_FOURTH                33787
#define IDS_TOOLTIP_THIRD               33788
#define IDS_TOOLTIP_FOURTH              33789

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        4087
#define _APS_NEXT_COMMAND_VALUE         32792
#define _APS_NEXT_CONTROL_VALUE         4038
#define _APS_NEXT_SYMED_VALUE           4000
#endif
#endif
