// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.genetibase.askafriend.common.network.stub;


public class AskAFriendResponse {
    protected java.lang.String webAskAFriendID;
    protected java.lang.String question;
    protected java.lang.String photoBase64Binary;
    protected com.genetibase.askafriend.common.network.stub.ArrayOfInt responseValues;
    protected double average;
    protected int responseType;
    protected com.genetibase.askafriend.common.network.stub.ArrayOfString customResponses;
    
    public AskAFriendResponse() {
    }
    
    public AskAFriendResponse(java.lang.String webAskAFriendID, java.lang.String question, java.lang.String photoBase64Binary, com.genetibase.askafriend.common.network.stub.ArrayOfInt responseValues, double average, int responseType, com.genetibase.askafriend.common.network.stub.ArrayOfString customResponses) {
        this.webAskAFriendID = webAskAFriendID;
        this.question = question;
        this.photoBase64Binary = photoBase64Binary;
        this.responseValues = responseValues;
        this.average = average;
        this.responseType = responseType;
        this.customResponses = customResponses;
    }
    
    public java.lang.String getWebAskAFriendID() {
        return webAskAFriendID;
    }
    
    public void setWebAskAFriendID(java.lang.String webAskAFriendID) {
        this.webAskAFriendID = webAskAFriendID;
    }
    
    public java.lang.String getQuestion() {
        return question;
    }
    
    public void setQuestion(java.lang.String question) {
        this.question = question;
    }
    
    public java.lang.String getPhotoBase64Binary() {
        return photoBase64Binary;
    }
    
    public void setPhotoBase64Binary(java.lang.String photoBase64Binary) {
        this.photoBase64Binary = photoBase64Binary;
    }
    
    public com.genetibase.askafriend.common.network.stub.ArrayOfInt getResponseValues() {
        return responseValues;
    }
    
    public void setResponseValues(com.genetibase.askafriend.common.network.stub.ArrayOfInt responseValues) {
        this.responseValues = responseValues;
    }
    
    public double getAverage() {
        return average;
    }
    
    public void setAverage(double average) {
        this.average = average;
    }
    
    public int getResponseType() {
        return responseType;
    }
    
    public void setResponseType(int responseType) {
        this.responseType = responseType;
    }
    
    public com.genetibase.askafriend.common.network.stub.ArrayOfString getCustomResponses() {
        return customResponses;
    }
    
    public void setCustomResponses(com.genetibase.askafriend.common.network.stub.ArrayOfString customResponses) {
        this.customResponses = customResponses;
    }
}
