// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.genetibase.askafriend.common.network.stub;


public class PrivateAAFQuestion {
    protected java.lang.String nickName;
    protected java.lang.String question;
    protected java.lang.String URL;
    protected java.lang.String dateTimePosted;
    
    public PrivateAAFQuestion() {
    }
    
    public PrivateAAFQuestion(java.lang.String nickName, java.lang.String question, java.lang.String URL, java.lang.String dateTimePosted) {
        this.nickName = nickName;
        this.question = question;
        this.URL = URL;
        this.dateTimePosted = dateTimePosted;
    }
    
    public java.lang.String getNickName() {
        return nickName;
    }
    
    public void setNickName(java.lang.String nickName) {
        this.nickName = nickName;
    }
    
    public java.lang.String getQuestion() {
        return question;
    }
    
    public void setQuestion(java.lang.String question) {
        this.question = question;
    }
    
    public java.lang.String getURL() {
        return URL;
    }
    
    public void setURL(java.lang.String URL) {
        this.URL = URL;
    }
    
    public java.lang.String getDateTimePosted() {
        return dateTimePosted;
    }
    
    public void setDateTimePosted(java.lang.String dateTimePosted) {
        this.dateTimePosted = dateTimePosted;
    }
}
