// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.genetibase.askafriend.common.network.stub;


public class SubmitQuestionResponse {
    protected com.genetibase.askafriend.common.network.stub.AskAFriendConfirm submitQuestionResult;
    
    public SubmitQuestionResponse() {
    }
    
    public SubmitQuestionResponse(com.genetibase.askafriend.common.network.stub.AskAFriendConfirm submitQuestionResult) {
        this.submitQuestionResult = submitQuestionResult;
    }
    
    public com.genetibase.askafriend.common.network.stub.AskAFriendConfirm getSubmitQuestionResult() {
        return submitQuestionResult;
    }
    
    public void setSubmitQuestionResult(com.genetibase.askafriend.common.network.stub.AskAFriendConfirm submitQuestionResult) {
        this.submitQuestionResult = submitQuestionResult;
    }
}
