#pragma once


D3DXMATRIX * GetRotMatrixFromVec(_IN_ D3DXVECTOR3 * vecDir, _IN_ D3DXVECTOR3 * upDir, _OUT_ D3DXMATRIX * matRot);
D3DXMATRIX * GetMatrixFromVec ( CONST D3DXVECTOR3 *pEye, CONST D3DXVECTOR3 *pAt, CONST D3DXVECTOR3 *pUp, D3DXMATRIX * pMatTransform );
D3DXMATRIX * GetMatrixFromTwoVec ( CONST D3DXVECTOR3 *pEye1, CONST D3DXVECTOR3 *pAt1, CONST D3DXVECTOR3 *pUp1, CONST D3DXVECTOR3 *pEye2, CONST D3DXVECTOR3 *pAt2, CONST D3DXVECTOR3 *pUp2 , D3DXMATRIX * pMatTransformResult );
