/* WS_MemberServices_v2Stub.h
   Generated by gSOAP 2.7.10 from .\wsdl-h\MemberServices.v2.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef WS_MemberServices_v2Stub_H
#define WS_MemberServices_v2Stub_H
#include <vector>
#ifndef WITH_NONAMESPACES
#define WITH_NONAMESPACES
#endif
#ifndef WITH_NOGLOBAL
#define WITH_NOGLOBAL
#endif
#include "stdsoap2.h"

namespace WS_MemberServices_v2 {

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not redeclare here */

#endif

#if 0 /* volatile type: do not redeclare here */

#endif

#ifndef SOAP_TYPE_WS_MemberServices_v2__MemberServicesV2__GetEncryptionKey
#define SOAP_TYPE_WS_MemberServices_v2__MemberServicesV2__GetEncryptionKey (8)
/* MemberServicesV2:GetEncryptionKey */
class SOAP_CMAC _MemberServicesV2__GetEncryptionKey
{
public:
	std::string *WebMemberID;	/* optional element of type xsd:string */
	std::string *WebPassword;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 8; } /* = unique id SOAP_TYPE_WS_MemberServices_v2__MemberServicesV2__GetEncryptionKey */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _MemberServicesV2__GetEncryptionKey() : WebMemberID(NULL), WebPassword(NULL), soap(NULL) { }
	virtual ~_MemberServicesV2__GetEncryptionKey() { }
};
#endif

#ifndef SOAP_TYPE_WS_MemberServices_v2__MemberServicesV2__GetEncryptionKeyResponse
#define SOAP_TYPE_WS_MemberServices_v2__MemberServicesV2__GetEncryptionKeyResponse (9)
/* MemberServicesV2:GetEncryptionKeyResponse */
class SOAP_CMAC _MemberServicesV2__GetEncryptionKeyResponse
{
public:
	std::string *GetEncryptionKeyResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 9; } /* = unique id SOAP_TYPE_WS_MemberServices_v2__MemberServicesV2__GetEncryptionKeyResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _MemberServicesV2__GetEncryptionKeyResponse() : GetEncryptionKeyResult(NULL), soap(NULL) { }
	virtual ~_MemberServicesV2__GetEncryptionKeyResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS_MemberServices_v2__MemberServicesV2__GetMemberID
#define SOAP_TYPE_WS_MemberServices_v2__MemberServicesV2__GetMemberID (10)
/* MemberServicesV2:GetMemberID */
class SOAP_CMAC _MemberServicesV2__GetMemberID
{
public:
	std::string *NickName;	/* optional element of type xsd:string */
	std::string *WebPassword;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 10; } /* = unique id SOAP_TYPE_WS_MemberServices_v2__MemberServicesV2__GetMemberID */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _MemberServicesV2__GetMemberID() : NickName(NULL), WebPassword(NULL), soap(NULL) { }
	virtual ~_MemberServicesV2__GetMemberID() { }
};
#endif

#ifndef SOAP_TYPE_WS_MemberServices_v2__MemberServicesV2__GetMemberIDResponse
#define SOAP_TYPE_WS_MemberServices_v2__MemberServicesV2__GetMemberIDResponse (11)
/* MemberServicesV2:GetMemberIDResponse */
class SOAP_CMAC _MemberServicesV2__GetMemberIDResponse
{
public:
	std::string *GetMemberIDResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 11; } /* = unique id SOAP_TYPE_WS_MemberServices_v2__MemberServicesV2__GetMemberIDResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _MemberServicesV2__GetMemberIDResponse() : GetMemberIDResult(NULL), soap(NULL) { }
	virtual ~_MemberServicesV2__GetMemberIDResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS_MemberServices_v2__MemberServicesV2__GetTagID
#define SOAP_TYPE_WS_MemberServices_v2__MemberServicesV2__GetTagID (12)
/* MemberServicesV2:GetTagID */
class SOAP_CMAC _MemberServicesV2__GetTagID
{
public:
	std::string *WebMemberID;	/* optional element of type xsd:string */
	std::string *WebPassword;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 12; } /* = unique id SOAP_TYPE_WS_MemberServices_v2__MemberServicesV2__GetTagID */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _MemberServicesV2__GetTagID() : WebMemberID(NULL), WebPassword(NULL), soap(NULL) { }
	virtual ~_MemberServicesV2__GetTagID() { }
};
#endif

#ifndef SOAP_TYPE_WS_MemberServices_v2__MemberServicesV2__GetTagIDResponse
#define SOAP_TYPE_WS_MemberServices_v2__MemberServicesV2__GetTagIDResponse (13)
/* MemberServicesV2:GetTagIDResponse */
class SOAP_CMAC _MemberServicesV2__GetTagIDResponse
{
public:
	std::string *GetTagIDResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 13; } /* = unique id SOAP_TYPE_WS_MemberServices_v2__MemberServicesV2__GetTagIDResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _MemberServicesV2__GetTagIDResponse() : GetTagIDResult(NULL), soap(NULL) { }
	virtual ~_MemberServicesV2__GetTagIDResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS_MemberServices_v2___MemberServicesV22__GetEncryptionKey
#define SOAP_TYPE_WS_MemberServices_v2___MemberServicesV22__GetEncryptionKey (20)
/* Operation wrapper: */
struct __MemberServicesV22__GetEncryptionKey
{
public:
	_MemberServicesV2__GetEncryptionKey *MemberServicesV2__GetEncryptionKey;	/* optional element of type MemberServicesV2:GetEncryptionKey */
};
#endif

#ifndef SOAP_TYPE_WS_MemberServices_v2___MemberServicesV22__GetMemberID
#define SOAP_TYPE_WS_MemberServices_v2___MemberServicesV22__GetMemberID (24)
/* Operation wrapper: */
struct __MemberServicesV22__GetMemberID
{
public:
	_MemberServicesV2__GetMemberID *MemberServicesV2__GetMemberID;	/* optional element of type MemberServicesV2:GetMemberID */
};
#endif

#ifndef SOAP_TYPE_WS_MemberServices_v2___MemberServicesV22__GetTagID
#define SOAP_TYPE_WS_MemberServices_v2___MemberServicesV22__GetTagID (28)
/* Operation wrapper: */
struct __MemberServicesV22__GetTagID
{
public:
	_MemberServicesV2__GetTagID *MemberServicesV2__GetTagID;	/* optional element of type MemberServicesV2:GetTagID */
};
#endif

#ifndef SOAP_TYPE_WS_MemberServices_v2___MemberServicesV23__GetEncryptionKey
#define SOAP_TYPE_WS_MemberServices_v2___MemberServicesV23__GetEncryptionKey (30)
/* Operation wrapper: */
struct __MemberServicesV23__GetEncryptionKey
{
public:
	_MemberServicesV2__GetEncryptionKey *MemberServicesV2__GetEncryptionKey;	/* optional element of type MemberServicesV2:GetEncryptionKey */
};
#endif

#ifndef SOAP_TYPE_WS_MemberServices_v2___MemberServicesV23__GetMemberID
#define SOAP_TYPE_WS_MemberServices_v2___MemberServicesV23__GetMemberID (32)
/* Operation wrapper: */
struct __MemberServicesV23__GetMemberID
{
public:
	_MemberServicesV2__GetMemberID *MemberServicesV2__GetMemberID;	/* optional element of type MemberServicesV2:GetMemberID */
};
#endif

#ifndef SOAP_TYPE_WS_MemberServices_v2___MemberServicesV23__GetTagID
#define SOAP_TYPE_WS_MemberServices_v2___MemberServicesV23__GetTagID (34)
/* Operation wrapper: */
struct __MemberServicesV23__GetTagID
{
public:
	_MemberServicesV2__GetTagID *MemberServicesV2__GetTagID;	/* optional element of type MemberServicesV2:GetTagID */
};
#endif

#ifndef SOAP_TYPE_WS_MemberServices_v2_SOAP_ENV__Header
#define SOAP_TYPE_WS_MemberServices_v2_SOAP_ENV__Header (35)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
private:
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_WS_MemberServices_v2_SOAP_ENV__Code
#define SOAP_TYPE_WS_MemberServices_v2_SOAP_ENV__Code (36)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
public:
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#ifndef SOAP_TYPE_WS_MemberServices_v2_SOAP_ENV__Detail
#define SOAP_TYPE_WS_MemberServices_v2_SOAP_ENV__Detail (38)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
public:
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
	char *__any;
};
#endif

#ifndef SOAP_TYPE_WS_MemberServices_v2_SOAP_ENV__Reason
#define SOAP_TYPE_WS_MemberServices_v2_SOAP_ENV__Reason (41)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
public:
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_WS_MemberServices_v2_SOAP_ENV__Fault
#define SOAP_TYPE_WS_MemberServices_v2_SOAP_ENV__Fault (42)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
public:
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE_WS_MemberServices_v2__QName
#define SOAP_TYPE_WS_MemberServices_v2__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE_WS_MemberServices_v2__XML
#define SOAP_TYPE_WS_MemberServices_v2__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Typedef Synonyms                                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Stubs                                                                      *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call___MemberServicesV22__GetEncryptionKey(struct soap *soap, const char *soap_endpoint, const char *soap_action, _MemberServicesV2__GetEncryptionKey *MemberServicesV2__GetEncryptionKey, _MemberServicesV2__GetEncryptionKeyResponse *MemberServicesV2__GetEncryptionKeyResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___MemberServicesV22__GetMemberID(struct soap *soap, const char *soap_endpoint, const char *soap_action, _MemberServicesV2__GetMemberID *MemberServicesV2__GetMemberID, _MemberServicesV2__GetMemberIDResponse *MemberServicesV2__GetMemberIDResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___MemberServicesV22__GetTagID(struct soap *soap, const char *soap_endpoint, const char *soap_action, _MemberServicesV2__GetTagID *MemberServicesV2__GetTagID, _MemberServicesV2__GetTagIDResponse *MemberServicesV2__GetTagIDResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___MemberServicesV23__GetEncryptionKey(struct soap *soap, const char *soap_endpoint, const char *soap_action, _MemberServicesV2__GetEncryptionKey *MemberServicesV2__GetEncryptionKey, _MemberServicesV2__GetEncryptionKeyResponse *MemberServicesV2__GetEncryptionKeyResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___MemberServicesV23__GetMemberID(struct soap *soap, const char *soap_endpoint, const char *soap_action, _MemberServicesV2__GetMemberID *MemberServicesV2__GetMemberID, _MemberServicesV2__GetMemberIDResponse *MemberServicesV2__GetMemberIDResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___MemberServicesV23__GetTagID(struct soap *soap, const char *soap_endpoint, const char *soap_action, _MemberServicesV2__GetTagID *MemberServicesV2__GetTagID, _MemberServicesV2__GetTagIDResponse *MemberServicesV2__GetTagIDResponse);

} // namespace WS_MemberServices_v2


#endif

/* End of WS_MemberServices_v2Stub.h */
