/* WS_MemberService_v3H.h
   Generated by gSOAP 2.7.10 from .\wsdl-h\MemberService.v3.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef WS_MemberService_v3H_H
#define WS_MemberService_v3H_H
#include "WS_MemberService_v3Stub.h"

namespace WS_MemberService_v3 {
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_WS_MemberService_v3_byte
#define SOAP_TYPE_WS_MemberService_v3_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_WS_MemberService_v3_int
#define SOAP_TYPE_WS_MemberService_v3_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_WS_MemberService_v3_bool
#define SOAP_TYPE_WS_MemberService_v3_bool (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_bool(struct soap*, bool *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_bool(struct soap*, const bool *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_bool(struct soap*, const char*, int, const bool *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_bool2s(struct soap*, bool);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_get_bool(struct soap*, bool *, const char*, const char*);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_in_bool(struct soap*, const char*, bool *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2bool(struct soap*, const char*, bool *);

#ifndef SOAP_TYPE_WS_MemberService_v3_std__string
#define SOAP_TYPE_WS_MemberService_v3_std__string (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);
SOAP_FMAC5 std::string * SOAP_FMAC6 soap_new_std__string(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_std__string(struct soap*, std::string*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_WS_MemberService_v3__MemberServiceV3__RemindPasswordResponse
#define SOAP_TYPE_WS_MemberService_v3__MemberServiceV3__RemindPasswordResponse (17)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__MemberServiceV3__RemindPasswordResponse(struct soap*, const char*, int, const _MemberServiceV3__RemindPasswordResponse *, const char*);
SOAP_FMAC3 _MemberServiceV3__RemindPasswordResponse * SOAP_FMAC4 soap_get__MemberServiceV3__RemindPasswordResponse(struct soap*, _MemberServiceV3__RemindPasswordResponse *, const char*, const char*);
SOAP_FMAC3 _MemberServiceV3__RemindPasswordResponse * SOAP_FMAC4 soap_in__MemberServiceV3__RemindPasswordResponse(struct soap*, const char*, _MemberServiceV3__RemindPasswordResponse *, const char*);
SOAP_FMAC5 _MemberServiceV3__RemindPasswordResponse * SOAP_FMAC6 soap_new__MemberServiceV3__RemindPasswordResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__MemberServiceV3__RemindPasswordResponse(struct soap*, _MemberServiceV3__RemindPasswordResponse*);
SOAP_FMAC3 _MemberServiceV3__RemindPasswordResponse * SOAP_FMAC4 soap_instantiate__MemberServiceV3__RemindPasswordResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__MemberServiceV3__RemindPasswordResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_WS_MemberService_v3__MemberServiceV3__RemindPassword
#define SOAP_TYPE_WS_MemberService_v3__MemberServiceV3__RemindPassword (16)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__MemberServiceV3__RemindPassword(struct soap*, const char*, int, const _MemberServiceV3__RemindPassword *, const char*);
SOAP_FMAC3 _MemberServiceV3__RemindPassword * SOAP_FMAC4 soap_get__MemberServiceV3__RemindPassword(struct soap*, _MemberServiceV3__RemindPassword *, const char*, const char*);
SOAP_FMAC3 _MemberServiceV3__RemindPassword * SOAP_FMAC4 soap_in__MemberServiceV3__RemindPassword(struct soap*, const char*, _MemberServiceV3__RemindPassword *, const char*);
SOAP_FMAC5 _MemberServiceV3__RemindPassword * SOAP_FMAC6 soap_new__MemberServiceV3__RemindPassword(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__MemberServiceV3__RemindPassword(struct soap*, _MemberServiceV3__RemindPassword*);
SOAP_FMAC3 _MemberServiceV3__RemindPassword * SOAP_FMAC4 soap_instantiate__MemberServiceV3__RemindPassword(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__MemberServiceV3__RemindPassword(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_WS_MemberService_v3__MemberServiceV3__GetTagIDResponse
#define SOAP_TYPE_WS_MemberService_v3__MemberServiceV3__GetTagIDResponse (15)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__MemberServiceV3__GetTagIDResponse(struct soap*, const char*, int, const _MemberServiceV3__GetTagIDResponse *, const char*);
SOAP_FMAC3 _MemberServiceV3__GetTagIDResponse * SOAP_FMAC4 soap_get__MemberServiceV3__GetTagIDResponse(struct soap*, _MemberServiceV3__GetTagIDResponse *, const char*, const char*);
SOAP_FMAC3 _MemberServiceV3__GetTagIDResponse * SOAP_FMAC4 soap_in__MemberServiceV3__GetTagIDResponse(struct soap*, const char*, _MemberServiceV3__GetTagIDResponse *, const char*);
SOAP_FMAC5 _MemberServiceV3__GetTagIDResponse * SOAP_FMAC6 soap_new__MemberServiceV3__GetTagIDResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__MemberServiceV3__GetTagIDResponse(struct soap*, _MemberServiceV3__GetTagIDResponse*);
SOAP_FMAC3 _MemberServiceV3__GetTagIDResponse * SOAP_FMAC4 soap_instantiate__MemberServiceV3__GetTagIDResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__MemberServiceV3__GetTagIDResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_WS_MemberService_v3__MemberServiceV3__GetTagID
#define SOAP_TYPE_WS_MemberService_v3__MemberServiceV3__GetTagID (14)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__MemberServiceV3__GetTagID(struct soap*, const char*, int, const _MemberServiceV3__GetTagID *, const char*);
SOAP_FMAC3 _MemberServiceV3__GetTagID * SOAP_FMAC4 soap_get__MemberServiceV3__GetTagID(struct soap*, _MemberServiceV3__GetTagID *, const char*, const char*);
SOAP_FMAC3 _MemberServiceV3__GetTagID * SOAP_FMAC4 soap_in__MemberServiceV3__GetTagID(struct soap*, const char*, _MemberServiceV3__GetTagID *, const char*);
SOAP_FMAC5 _MemberServiceV3__GetTagID * SOAP_FMAC6 soap_new__MemberServiceV3__GetTagID(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__MemberServiceV3__GetTagID(struct soap*, _MemberServiceV3__GetTagID*);
SOAP_FMAC3 _MemberServiceV3__GetTagID * SOAP_FMAC4 soap_instantiate__MemberServiceV3__GetTagID(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__MemberServiceV3__GetTagID(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_WS_MemberService_v3__MemberServiceV3__GetMemberIDResponse
#define SOAP_TYPE_WS_MemberService_v3__MemberServiceV3__GetMemberIDResponse (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__MemberServiceV3__GetMemberIDResponse(struct soap*, const char*, int, const _MemberServiceV3__GetMemberIDResponse *, const char*);
SOAP_FMAC3 _MemberServiceV3__GetMemberIDResponse * SOAP_FMAC4 soap_get__MemberServiceV3__GetMemberIDResponse(struct soap*, _MemberServiceV3__GetMemberIDResponse *, const char*, const char*);
SOAP_FMAC3 _MemberServiceV3__GetMemberIDResponse * SOAP_FMAC4 soap_in__MemberServiceV3__GetMemberIDResponse(struct soap*, const char*, _MemberServiceV3__GetMemberIDResponse *, const char*);
SOAP_FMAC5 _MemberServiceV3__GetMemberIDResponse * SOAP_FMAC6 soap_new__MemberServiceV3__GetMemberIDResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__MemberServiceV3__GetMemberIDResponse(struct soap*, _MemberServiceV3__GetMemberIDResponse*);
SOAP_FMAC3 _MemberServiceV3__GetMemberIDResponse * SOAP_FMAC4 soap_instantiate__MemberServiceV3__GetMemberIDResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__MemberServiceV3__GetMemberIDResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_WS_MemberService_v3__MemberServiceV3__GetMemberID
#define SOAP_TYPE_WS_MemberService_v3__MemberServiceV3__GetMemberID (12)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__MemberServiceV3__GetMemberID(struct soap*, const char*, int, const _MemberServiceV3__GetMemberID *, const char*);
SOAP_FMAC3 _MemberServiceV3__GetMemberID * SOAP_FMAC4 soap_get__MemberServiceV3__GetMemberID(struct soap*, _MemberServiceV3__GetMemberID *, const char*, const char*);
SOAP_FMAC3 _MemberServiceV3__GetMemberID * SOAP_FMAC4 soap_in__MemberServiceV3__GetMemberID(struct soap*, const char*, _MemberServiceV3__GetMemberID *, const char*);
SOAP_FMAC5 _MemberServiceV3__GetMemberID * SOAP_FMAC6 soap_new__MemberServiceV3__GetMemberID(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__MemberServiceV3__GetMemberID(struct soap*, _MemberServiceV3__GetMemberID*);
SOAP_FMAC3 _MemberServiceV3__GetMemberID * SOAP_FMAC4 soap_instantiate__MemberServiceV3__GetMemberID(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__MemberServiceV3__GetMemberID(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_WS_MemberService_v3__MemberServiceV3__GetEncryptionKeyResponse
#define SOAP_TYPE_WS_MemberService_v3__MemberServiceV3__GetEncryptionKeyResponse (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__MemberServiceV3__GetEncryptionKeyResponse(struct soap*, const char*, int, const _MemberServiceV3__GetEncryptionKeyResponse *, const char*);
SOAP_FMAC3 _MemberServiceV3__GetEncryptionKeyResponse * SOAP_FMAC4 soap_get__MemberServiceV3__GetEncryptionKeyResponse(struct soap*, _MemberServiceV3__GetEncryptionKeyResponse *, const char*, const char*);
SOAP_FMAC3 _MemberServiceV3__GetEncryptionKeyResponse * SOAP_FMAC4 soap_in__MemberServiceV3__GetEncryptionKeyResponse(struct soap*, const char*, _MemberServiceV3__GetEncryptionKeyResponse *, const char*);
SOAP_FMAC5 _MemberServiceV3__GetEncryptionKeyResponse * SOAP_FMAC6 soap_new__MemberServiceV3__GetEncryptionKeyResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__MemberServiceV3__GetEncryptionKeyResponse(struct soap*, _MemberServiceV3__GetEncryptionKeyResponse*);
SOAP_FMAC3 _MemberServiceV3__GetEncryptionKeyResponse * SOAP_FMAC4 soap_instantiate__MemberServiceV3__GetEncryptionKeyResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__MemberServiceV3__GetEncryptionKeyResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_WS_MemberService_v3__MemberServiceV3__GetEncryptionKey
#define SOAP_TYPE_WS_MemberService_v3__MemberServiceV3__GetEncryptionKey (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__MemberServiceV3__GetEncryptionKey(struct soap*, const char*, int, const _MemberServiceV3__GetEncryptionKey *, const char*);
SOAP_FMAC3 _MemberServiceV3__GetEncryptionKey * SOAP_FMAC4 soap_get__MemberServiceV3__GetEncryptionKey(struct soap*, _MemberServiceV3__GetEncryptionKey *, const char*, const char*);
SOAP_FMAC3 _MemberServiceV3__GetEncryptionKey * SOAP_FMAC4 soap_in__MemberServiceV3__GetEncryptionKey(struct soap*, const char*, _MemberServiceV3__GetEncryptionKey *, const char*);
SOAP_FMAC5 _MemberServiceV3__GetEncryptionKey * SOAP_FMAC6 soap_new__MemberServiceV3__GetEncryptionKey(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__MemberServiceV3__GetEncryptionKey(struct soap*, _MemberServiceV3__GetEncryptionKey*);
SOAP_FMAC3 _MemberServiceV3__GetEncryptionKey * SOAP_FMAC4 soap_instantiate__MemberServiceV3__GetEncryptionKey(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__MemberServiceV3__GetEncryptionKey(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_WS_MemberService_v3__MemberServiceV3__CheckUserExistsResponse
#define SOAP_TYPE_WS_MemberService_v3__MemberServiceV3__CheckUserExistsResponse (9)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__MemberServiceV3__CheckUserExistsResponse(struct soap*, const char*, int, const _MemberServiceV3__CheckUserExistsResponse *, const char*);
SOAP_FMAC3 _MemberServiceV3__CheckUserExistsResponse * SOAP_FMAC4 soap_get__MemberServiceV3__CheckUserExistsResponse(struct soap*, _MemberServiceV3__CheckUserExistsResponse *, const char*, const char*);
SOAP_FMAC3 _MemberServiceV3__CheckUserExistsResponse * SOAP_FMAC4 soap_in__MemberServiceV3__CheckUserExistsResponse(struct soap*, const char*, _MemberServiceV3__CheckUserExistsResponse *, const char*);
SOAP_FMAC5 _MemberServiceV3__CheckUserExistsResponse * SOAP_FMAC6 soap_new__MemberServiceV3__CheckUserExistsResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__MemberServiceV3__CheckUserExistsResponse(struct soap*, _MemberServiceV3__CheckUserExistsResponse*);
SOAP_FMAC3 _MemberServiceV3__CheckUserExistsResponse * SOAP_FMAC4 soap_instantiate__MemberServiceV3__CheckUserExistsResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__MemberServiceV3__CheckUserExistsResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_WS_MemberService_v3__MemberServiceV3__CheckUserExists
#define SOAP_TYPE_WS_MemberService_v3__MemberServiceV3__CheckUserExists (8)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__MemberServiceV3__CheckUserExists(struct soap*, const char*, int, const _MemberServiceV3__CheckUserExists *, const char*);
SOAP_FMAC3 _MemberServiceV3__CheckUserExists * SOAP_FMAC4 soap_get__MemberServiceV3__CheckUserExists(struct soap*, _MemberServiceV3__CheckUserExists *, const char*, const char*);
SOAP_FMAC3 _MemberServiceV3__CheckUserExists * SOAP_FMAC4 soap_in__MemberServiceV3__CheckUserExists(struct soap*, const char*, _MemberServiceV3__CheckUserExists *, const char*);
SOAP_FMAC5 _MemberServiceV3__CheckUserExists * SOAP_FMAC6 soap_new__MemberServiceV3__CheckUserExists(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__MemberServiceV3__CheckUserExists(struct soap*, _MemberServiceV3__CheckUserExists*);
SOAP_FMAC3 _MemberServiceV3__CheckUserExists * SOAP_FMAC4 soap_instantiate__MemberServiceV3__CheckUserExists(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__MemberServiceV3__CheckUserExists(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_WS_MemberService_v3_SOAP_ENV__Fault
#define SOAP_TYPE_WS_MemberService_v3_SOAP_ENV__Fault (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Fault * SOAP_FMAC6 soap_new_SOAP_ENV__Fault(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_WS_MemberService_v3_SOAP_ENV__Reason
#define SOAP_TYPE_WS_MemberService_v3_SOAP_ENV__Reason (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Reason * SOAP_FMAC6 soap_new_SOAP_ENV__Reason(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_WS_MemberService_v3_SOAP_ENV__Detail
#define SOAP_TYPE_WS_MemberService_v3_SOAP_ENV__Detail (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Detail * SOAP_FMAC6 soap_new_SOAP_ENV__Detail(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_WS_MemberService_v3_SOAP_ENV__Code
#define SOAP_TYPE_WS_MemberService_v3_SOAP_ENV__Code (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Code * SOAP_FMAC6 soap_new_SOAP_ENV__Code(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_WS_MemberService_v3_SOAP_ENV__Header
#define SOAP_TYPE_WS_MemberService_v3_SOAP_ENV__Header (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Header * SOAP_FMAC6 soap_new_SOAP_ENV__Header(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE_WS_MemberService_v3___MemberServiceV33__RemindPassword
#define SOAP_TYPE_WS_MemberService_v3___MemberServiceV33__RemindPassword (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___MemberServiceV33__RemindPassword(struct soap*, struct __MemberServiceV33__RemindPassword *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___MemberServiceV33__RemindPassword(struct soap*, const struct __MemberServiceV33__RemindPassword *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___MemberServiceV33__RemindPassword(struct soap*, const struct __MemberServiceV33__RemindPassword *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___MemberServiceV33__RemindPassword(struct soap*, const char*, int, const struct __MemberServiceV33__RemindPassword *, const char*);
SOAP_FMAC3 struct __MemberServiceV33__RemindPassword * SOAP_FMAC4 soap_get___MemberServiceV33__RemindPassword(struct soap*, struct __MemberServiceV33__RemindPassword *, const char*, const char*);
SOAP_FMAC3 struct __MemberServiceV33__RemindPassword * SOAP_FMAC4 soap_in___MemberServiceV33__RemindPassword(struct soap*, const char*, struct __MemberServiceV33__RemindPassword *, const char*);
SOAP_FMAC5 struct __MemberServiceV33__RemindPassword * SOAP_FMAC6 soap_new___MemberServiceV33__RemindPassword(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___MemberServiceV33__RemindPassword(struct soap*, struct __MemberServiceV33__RemindPassword*);
SOAP_FMAC3 struct __MemberServiceV33__RemindPassword * SOAP_FMAC4 soap_instantiate___MemberServiceV33__RemindPassword(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___MemberServiceV33__RemindPassword(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_WS_MemberService_v3___MemberServiceV33__GetTagID
#define SOAP_TYPE_WS_MemberService_v3___MemberServiceV33__GetTagID (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___MemberServiceV33__GetTagID(struct soap*, struct __MemberServiceV33__GetTagID *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___MemberServiceV33__GetTagID(struct soap*, const struct __MemberServiceV33__GetTagID *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___MemberServiceV33__GetTagID(struct soap*, const struct __MemberServiceV33__GetTagID *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___MemberServiceV33__GetTagID(struct soap*, const char*, int, const struct __MemberServiceV33__GetTagID *, const char*);
SOAP_FMAC3 struct __MemberServiceV33__GetTagID * SOAP_FMAC4 soap_get___MemberServiceV33__GetTagID(struct soap*, struct __MemberServiceV33__GetTagID *, const char*, const char*);
SOAP_FMAC3 struct __MemberServiceV33__GetTagID * SOAP_FMAC4 soap_in___MemberServiceV33__GetTagID(struct soap*, const char*, struct __MemberServiceV33__GetTagID *, const char*);
SOAP_FMAC5 struct __MemberServiceV33__GetTagID * SOAP_FMAC6 soap_new___MemberServiceV33__GetTagID(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___MemberServiceV33__GetTagID(struct soap*, struct __MemberServiceV33__GetTagID*);
SOAP_FMAC3 struct __MemberServiceV33__GetTagID * SOAP_FMAC4 soap_instantiate___MemberServiceV33__GetTagID(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___MemberServiceV33__GetTagID(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_WS_MemberService_v3___MemberServiceV33__GetMemberID
#define SOAP_TYPE_WS_MemberService_v3___MemberServiceV33__GetMemberID (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___MemberServiceV33__GetMemberID(struct soap*, struct __MemberServiceV33__GetMemberID *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___MemberServiceV33__GetMemberID(struct soap*, const struct __MemberServiceV33__GetMemberID *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___MemberServiceV33__GetMemberID(struct soap*, const struct __MemberServiceV33__GetMemberID *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___MemberServiceV33__GetMemberID(struct soap*, const char*, int, const struct __MemberServiceV33__GetMemberID *, const char*);
SOAP_FMAC3 struct __MemberServiceV33__GetMemberID * SOAP_FMAC4 soap_get___MemberServiceV33__GetMemberID(struct soap*, struct __MemberServiceV33__GetMemberID *, const char*, const char*);
SOAP_FMAC3 struct __MemberServiceV33__GetMemberID * SOAP_FMAC4 soap_in___MemberServiceV33__GetMemberID(struct soap*, const char*, struct __MemberServiceV33__GetMemberID *, const char*);
SOAP_FMAC5 struct __MemberServiceV33__GetMemberID * SOAP_FMAC6 soap_new___MemberServiceV33__GetMemberID(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___MemberServiceV33__GetMemberID(struct soap*, struct __MemberServiceV33__GetMemberID*);
SOAP_FMAC3 struct __MemberServiceV33__GetMemberID * SOAP_FMAC4 soap_instantiate___MemberServiceV33__GetMemberID(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___MemberServiceV33__GetMemberID(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_WS_MemberService_v3___MemberServiceV33__GetEncryptionKey
#define SOAP_TYPE_WS_MemberService_v3___MemberServiceV33__GetEncryptionKey (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___MemberServiceV33__GetEncryptionKey(struct soap*, struct __MemberServiceV33__GetEncryptionKey *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___MemberServiceV33__GetEncryptionKey(struct soap*, const struct __MemberServiceV33__GetEncryptionKey *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___MemberServiceV33__GetEncryptionKey(struct soap*, const struct __MemberServiceV33__GetEncryptionKey *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___MemberServiceV33__GetEncryptionKey(struct soap*, const char*, int, const struct __MemberServiceV33__GetEncryptionKey *, const char*);
SOAP_FMAC3 struct __MemberServiceV33__GetEncryptionKey * SOAP_FMAC4 soap_get___MemberServiceV33__GetEncryptionKey(struct soap*, struct __MemberServiceV33__GetEncryptionKey *, const char*, const char*);
SOAP_FMAC3 struct __MemberServiceV33__GetEncryptionKey * SOAP_FMAC4 soap_in___MemberServiceV33__GetEncryptionKey(struct soap*, const char*, struct __MemberServiceV33__GetEncryptionKey *, const char*);
SOAP_FMAC5 struct __MemberServiceV33__GetEncryptionKey * SOAP_FMAC6 soap_new___MemberServiceV33__GetEncryptionKey(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___MemberServiceV33__GetEncryptionKey(struct soap*, struct __MemberServiceV33__GetEncryptionKey*);
SOAP_FMAC3 struct __MemberServiceV33__GetEncryptionKey * SOAP_FMAC4 soap_instantiate___MemberServiceV33__GetEncryptionKey(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___MemberServiceV33__GetEncryptionKey(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_WS_MemberService_v3___MemberServiceV33__CheckUserExists
#define SOAP_TYPE_WS_MemberService_v3___MemberServiceV33__CheckUserExists (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___MemberServiceV33__CheckUserExists(struct soap*, struct __MemberServiceV33__CheckUserExists *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___MemberServiceV33__CheckUserExists(struct soap*, const struct __MemberServiceV33__CheckUserExists *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___MemberServiceV33__CheckUserExists(struct soap*, const struct __MemberServiceV33__CheckUserExists *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___MemberServiceV33__CheckUserExists(struct soap*, const char*, int, const struct __MemberServiceV33__CheckUserExists *, const char*);
SOAP_FMAC3 struct __MemberServiceV33__CheckUserExists * SOAP_FMAC4 soap_get___MemberServiceV33__CheckUserExists(struct soap*, struct __MemberServiceV33__CheckUserExists *, const char*, const char*);
SOAP_FMAC3 struct __MemberServiceV33__CheckUserExists * SOAP_FMAC4 soap_in___MemberServiceV33__CheckUserExists(struct soap*, const char*, struct __MemberServiceV33__CheckUserExists *, const char*);
SOAP_FMAC5 struct __MemberServiceV33__CheckUserExists * SOAP_FMAC6 soap_new___MemberServiceV33__CheckUserExists(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___MemberServiceV33__CheckUserExists(struct soap*, struct __MemberServiceV33__CheckUserExists*);
SOAP_FMAC3 struct __MemberServiceV33__CheckUserExists * SOAP_FMAC4 soap_instantiate___MemberServiceV33__CheckUserExists(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___MemberServiceV33__CheckUserExists(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_WS_MemberService_v3___MemberServiceV32__RemindPassword
#define SOAP_TYPE_WS_MemberService_v3___MemberServiceV32__RemindPassword (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___MemberServiceV32__RemindPassword(struct soap*, struct __MemberServiceV32__RemindPassword *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___MemberServiceV32__RemindPassword(struct soap*, const struct __MemberServiceV32__RemindPassword *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___MemberServiceV32__RemindPassword(struct soap*, const struct __MemberServiceV32__RemindPassword *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___MemberServiceV32__RemindPassword(struct soap*, const char*, int, const struct __MemberServiceV32__RemindPassword *, const char*);
SOAP_FMAC3 struct __MemberServiceV32__RemindPassword * SOAP_FMAC4 soap_get___MemberServiceV32__RemindPassword(struct soap*, struct __MemberServiceV32__RemindPassword *, const char*, const char*);
SOAP_FMAC3 struct __MemberServiceV32__RemindPassword * SOAP_FMAC4 soap_in___MemberServiceV32__RemindPassword(struct soap*, const char*, struct __MemberServiceV32__RemindPassword *, const char*);
SOAP_FMAC5 struct __MemberServiceV32__RemindPassword * SOAP_FMAC6 soap_new___MemberServiceV32__RemindPassword(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___MemberServiceV32__RemindPassword(struct soap*, struct __MemberServiceV32__RemindPassword*);
SOAP_FMAC3 struct __MemberServiceV32__RemindPassword * SOAP_FMAC4 soap_instantiate___MemberServiceV32__RemindPassword(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___MemberServiceV32__RemindPassword(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_WS_MemberService_v3___MemberServiceV32__GetTagID
#define SOAP_TYPE_WS_MemberService_v3___MemberServiceV32__GetTagID (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___MemberServiceV32__GetTagID(struct soap*, struct __MemberServiceV32__GetTagID *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___MemberServiceV32__GetTagID(struct soap*, const struct __MemberServiceV32__GetTagID *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___MemberServiceV32__GetTagID(struct soap*, const struct __MemberServiceV32__GetTagID *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___MemberServiceV32__GetTagID(struct soap*, const char*, int, const struct __MemberServiceV32__GetTagID *, const char*);
SOAP_FMAC3 struct __MemberServiceV32__GetTagID * SOAP_FMAC4 soap_get___MemberServiceV32__GetTagID(struct soap*, struct __MemberServiceV32__GetTagID *, const char*, const char*);
SOAP_FMAC3 struct __MemberServiceV32__GetTagID * SOAP_FMAC4 soap_in___MemberServiceV32__GetTagID(struct soap*, const char*, struct __MemberServiceV32__GetTagID *, const char*);
SOAP_FMAC5 struct __MemberServiceV32__GetTagID * SOAP_FMAC6 soap_new___MemberServiceV32__GetTagID(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___MemberServiceV32__GetTagID(struct soap*, struct __MemberServiceV32__GetTagID*);
SOAP_FMAC3 struct __MemberServiceV32__GetTagID * SOAP_FMAC4 soap_instantiate___MemberServiceV32__GetTagID(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___MemberServiceV32__GetTagID(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_WS_MemberService_v3___MemberServiceV32__GetMemberID
#define SOAP_TYPE_WS_MemberService_v3___MemberServiceV32__GetMemberID (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___MemberServiceV32__GetMemberID(struct soap*, struct __MemberServiceV32__GetMemberID *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___MemberServiceV32__GetMemberID(struct soap*, const struct __MemberServiceV32__GetMemberID *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___MemberServiceV32__GetMemberID(struct soap*, const struct __MemberServiceV32__GetMemberID *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___MemberServiceV32__GetMemberID(struct soap*, const char*, int, const struct __MemberServiceV32__GetMemberID *, const char*);
SOAP_FMAC3 struct __MemberServiceV32__GetMemberID * SOAP_FMAC4 soap_get___MemberServiceV32__GetMemberID(struct soap*, struct __MemberServiceV32__GetMemberID *, const char*, const char*);
SOAP_FMAC3 struct __MemberServiceV32__GetMemberID * SOAP_FMAC4 soap_in___MemberServiceV32__GetMemberID(struct soap*, const char*, struct __MemberServiceV32__GetMemberID *, const char*);
SOAP_FMAC5 struct __MemberServiceV32__GetMemberID * SOAP_FMAC6 soap_new___MemberServiceV32__GetMemberID(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___MemberServiceV32__GetMemberID(struct soap*, struct __MemberServiceV32__GetMemberID*);
SOAP_FMAC3 struct __MemberServiceV32__GetMemberID * SOAP_FMAC4 soap_instantiate___MemberServiceV32__GetMemberID(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___MemberServiceV32__GetMemberID(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_WS_MemberService_v3___MemberServiceV32__GetEncryptionKey
#define SOAP_TYPE_WS_MemberService_v3___MemberServiceV32__GetEncryptionKey (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___MemberServiceV32__GetEncryptionKey(struct soap*, struct __MemberServiceV32__GetEncryptionKey *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___MemberServiceV32__GetEncryptionKey(struct soap*, const struct __MemberServiceV32__GetEncryptionKey *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___MemberServiceV32__GetEncryptionKey(struct soap*, const struct __MemberServiceV32__GetEncryptionKey *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___MemberServiceV32__GetEncryptionKey(struct soap*, const char*, int, const struct __MemberServiceV32__GetEncryptionKey *, const char*);
SOAP_FMAC3 struct __MemberServiceV32__GetEncryptionKey * SOAP_FMAC4 soap_get___MemberServiceV32__GetEncryptionKey(struct soap*, struct __MemberServiceV32__GetEncryptionKey *, const char*, const char*);
SOAP_FMAC3 struct __MemberServiceV32__GetEncryptionKey * SOAP_FMAC4 soap_in___MemberServiceV32__GetEncryptionKey(struct soap*, const char*, struct __MemberServiceV32__GetEncryptionKey *, const char*);
SOAP_FMAC5 struct __MemberServiceV32__GetEncryptionKey * SOAP_FMAC6 soap_new___MemberServiceV32__GetEncryptionKey(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___MemberServiceV32__GetEncryptionKey(struct soap*, struct __MemberServiceV32__GetEncryptionKey*);
SOAP_FMAC3 struct __MemberServiceV32__GetEncryptionKey * SOAP_FMAC4 soap_instantiate___MemberServiceV32__GetEncryptionKey(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___MemberServiceV32__GetEncryptionKey(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_WS_MemberService_v3___MemberServiceV32__CheckUserExists
#define SOAP_TYPE_WS_MemberService_v3___MemberServiceV32__CheckUserExists (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___MemberServiceV32__CheckUserExists(struct soap*, struct __MemberServiceV32__CheckUserExists *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___MemberServiceV32__CheckUserExists(struct soap*, const struct __MemberServiceV32__CheckUserExists *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___MemberServiceV32__CheckUserExists(struct soap*, const struct __MemberServiceV32__CheckUserExists *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___MemberServiceV32__CheckUserExists(struct soap*, const char*, int, const struct __MemberServiceV32__CheckUserExists *, const char*);
SOAP_FMAC3 struct __MemberServiceV32__CheckUserExists * SOAP_FMAC4 soap_get___MemberServiceV32__CheckUserExists(struct soap*, struct __MemberServiceV32__CheckUserExists *, const char*, const char*);
SOAP_FMAC3 struct __MemberServiceV32__CheckUserExists * SOAP_FMAC4 soap_in___MemberServiceV32__CheckUserExists(struct soap*, const char*, struct __MemberServiceV32__CheckUserExists *, const char*);
SOAP_FMAC5 struct __MemberServiceV32__CheckUserExists * SOAP_FMAC6 soap_new___MemberServiceV32__CheckUserExists(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___MemberServiceV32__CheckUserExists(struct soap*, struct __MemberServiceV32__CheckUserExists*);
SOAP_FMAC3 struct __MemberServiceV32__CheckUserExists * SOAP_FMAC4 soap_instantiate___MemberServiceV32__CheckUserExists(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___MemberServiceV32__CheckUserExists(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_WS_MemberService_v3_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_WS_MemberService_v3_PointerToSOAP_ENV__Reason (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_WS_MemberService_v3_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_WS_MemberService_v3_PointerToSOAP_ENV__Detail (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_WS_MemberService_v3_PointerToSOAP_ENV__Code
#define SOAP_TYPE_WS_MemberService_v3_PointerToSOAP_ENV__Code (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_WS_MemberService_v3_PointerTo_MemberServiceV3__RemindPasswordResponse
#define SOAP_TYPE_WS_MemberService_v3_PointerTo_MemberServiceV3__RemindPasswordResponse (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_MemberServiceV3__RemindPasswordResponse(struct soap*, _MemberServiceV3__RemindPasswordResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_MemberServiceV3__RemindPasswordResponse(struct soap*, _MemberServiceV3__RemindPasswordResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_MemberServiceV3__RemindPasswordResponse(struct soap*, const char *, int, _MemberServiceV3__RemindPasswordResponse *const*, const char *);
SOAP_FMAC3 _MemberServiceV3__RemindPasswordResponse ** SOAP_FMAC4 soap_get_PointerTo_MemberServiceV3__RemindPasswordResponse(struct soap*, _MemberServiceV3__RemindPasswordResponse **, const char*, const char*);
SOAP_FMAC3 _MemberServiceV3__RemindPasswordResponse ** SOAP_FMAC4 soap_in_PointerTo_MemberServiceV3__RemindPasswordResponse(struct soap*, const char*, _MemberServiceV3__RemindPasswordResponse **, const char*);

#ifndef SOAP_TYPE_WS_MemberService_v3_PointerTo_MemberServiceV3__RemindPassword
#define SOAP_TYPE_WS_MemberService_v3_PointerTo_MemberServiceV3__RemindPassword (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_MemberServiceV3__RemindPassword(struct soap*, _MemberServiceV3__RemindPassword *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_MemberServiceV3__RemindPassword(struct soap*, _MemberServiceV3__RemindPassword *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_MemberServiceV3__RemindPassword(struct soap*, const char *, int, _MemberServiceV3__RemindPassword *const*, const char *);
SOAP_FMAC3 _MemberServiceV3__RemindPassword ** SOAP_FMAC4 soap_get_PointerTo_MemberServiceV3__RemindPassword(struct soap*, _MemberServiceV3__RemindPassword **, const char*, const char*);
SOAP_FMAC3 _MemberServiceV3__RemindPassword ** SOAP_FMAC4 soap_in_PointerTo_MemberServiceV3__RemindPassword(struct soap*, const char*, _MemberServiceV3__RemindPassword **, const char*);

#ifndef SOAP_TYPE_WS_MemberService_v3_PointerTo_MemberServiceV3__GetTagIDResponse
#define SOAP_TYPE_WS_MemberService_v3_PointerTo_MemberServiceV3__GetTagIDResponse (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_MemberServiceV3__GetTagIDResponse(struct soap*, _MemberServiceV3__GetTagIDResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_MemberServiceV3__GetTagIDResponse(struct soap*, _MemberServiceV3__GetTagIDResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_MemberServiceV3__GetTagIDResponse(struct soap*, const char *, int, _MemberServiceV3__GetTagIDResponse *const*, const char *);
SOAP_FMAC3 _MemberServiceV3__GetTagIDResponse ** SOAP_FMAC4 soap_get_PointerTo_MemberServiceV3__GetTagIDResponse(struct soap*, _MemberServiceV3__GetTagIDResponse **, const char*, const char*);
SOAP_FMAC3 _MemberServiceV3__GetTagIDResponse ** SOAP_FMAC4 soap_in_PointerTo_MemberServiceV3__GetTagIDResponse(struct soap*, const char*, _MemberServiceV3__GetTagIDResponse **, const char*);

#ifndef SOAP_TYPE_WS_MemberService_v3_PointerTo_MemberServiceV3__GetTagID
#define SOAP_TYPE_WS_MemberService_v3_PointerTo_MemberServiceV3__GetTagID (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_MemberServiceV3__GetTagID(struct soap*, _MemberServiceV3__GetTagID *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_MemberServiceV3__GetTagID(struct soap*, _MemberServiceV3__GetTagID *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_MemberServiceV3__GetTagID(struct soap*, const char *, int, _MemberServiceV3__GetTagID *const*, const char *);
SOAP_FMAC3 _MemberServiceV3__GetTagID ** SOAP_FMAC4 soap_get_PointerTo_MemberServiceV3__GetTagID(struct soap*, _MemberServiceV3__GetTagID **, const char*, const char*);
SOAP_FMAC3 _MemberServiceV3__GetTagID ** SOAP_FMAC4 soap_in_PointerTo_MemberServiceV3__GetTagID(struct soap*, const char*, _MemberServiceV3__GetTagID **, const char*);

#ifndef SOAP_TYPE_WS_MemberService_v3_PointerTo_MemberServiceV3__GetMemberIDResponse
#define SOAP_TYPE_WS_MemberService_v3_PointerTo_MemberServiceV3__GetMemberIDResponse (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_MemberServiceV3__GetMemberIDResponse(struct soap*, _MemberServiceV3__GetMemberIDResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_MemberServiceV3__GetMemberIDResponse(struct soap*, _MemberServiceV3__GetMemberIDResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_MemberServiceV3__GetMemberIDResponse(struct soap*, const char *, int, _MemberServiceV3__GetMemberIDResponse *const*, const char *);
SOAP_FMAC3 _MemberServiceV3__GetMemberIDResponse ** SOAP_FMAC4 soap_get_PointerTo_MemberServiceV3__GetMemberIDResponse(struct soap*, _MemberServiceV3__GetMemberIDResponse **, const char*, const char*);
SOAP_FMAC3 _MemberServiceV3__GetMemberIDResponse ** SOAP_FMAC4 soap_in_PointerTo_MemberServiceV3__GetMemberIDResponse(struct soap*, const char*, _MemberServiceV3__GetMemberIDResponse **, const char*);

#ifndef SOAP_TYPE_WS_MemberService_v3_PointerTo_MemberServiceV3__GetMemberID
#define SOAP_TYPE_WS_MemberService_v3_PointerTo_MemberServiceV3__GetMemberID (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_MemberServiceV3__GetMemberID(struct soap*, _MemberServiceV3__GetMemberID *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_MemberServiceV3__GetMemberID(struct soap*, _MemberServiceV3__GetMemberID *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_MemberServiceV3__GetMemberID(struct soap*, const char *, int, _MemberServiceV3__GetMemberID *const*, const char *);
SOAP_FMAC3 _MemberServiceV3__GetMemberID ** SOAP_FMAC4 soap_get_PointerTo_MemberServiceV3__GetMemberID(struct soap*, _MemberServiceV3__GetMemberID **, const char*, const char*);
SOAP_FMAC3 _MemberServiceV3__GetMemberID ** SOAP_FMAC4 soap_in_PointerTo_MemberServiceV3__GetMemberID(struct soap*, const char*, _MemberServiceV3__GetMemberID **, const char*);

#ifndef SOAP_TYPE_WS_MemberService_v3_PointerTo_MemberServiceV3__GetEncryptionKeyResponse
#define SOAP_TYPE_WS_MemberService_v3_PointerTo_MemberServiceV3__GetEncryptionKeyResponse (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_MemberServiceV3__GetEncryptionKeyResponse(struct soap*, _MemberServiceV3__GetEncryptionKeyResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_MemberServiceV3__GetEncryptionKeyResponse(struct soap*, _MemberServiceV3__GetEncryptionKeyResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_MemberServiceV3__GetEncryptionKeyResponse(struct soap*, const char *, int, _MemberServiceV3__GetEncryptionKeyResponse *const*, const char *);
SOAP_FMAC3 _MemberServiceV3__GetEncryptionKeyResponse ** SOAP_FMAC4 soap_get_PointerTo_MemberServiceV3__GetEncryptionKeyResponse(struct soap*, _MemberServiceV3__GetEncryptionKeyResponse **, const char*, const char*);
SOAP_FMAC3 _MemberServiceV3__GetEncryptionKeyResponse ** SOAP_FMAC4 soap_in_PointerTo_MemberServiceV3__GetEncryptionKeyResponse(struct soap*, const char*, _MemberServiceV3__GetEncryptionKeyResponse **, const char*);

#ifndef SOAP_TYPE_WS_MemberService_v3_PointerTo_MemberServiceV3__GetEncryptionKey
#define SOAP_TYPE_WS_MemberService_v3_PointerTo_MemberServiceV3__GetEncryptionKey (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_MemberServiceV3__GetEncryptionKey(struct soap*, _MemberServiceV3__GetEncryptionKey *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_MemberServiceV3__GetEncryptionKey(struct soap*, _MemberServiceV3__GetEncryptionKey *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_MemberServiceV3__GetEncryptionKey(struct soap*, const char *, int, _MemberServiceV3__GetEncryptionKey *const*, const char *);
SOAP_FMAC3 _MemberServiceV3__GetEncryptionKey ** SOAP_FMAC4 soap_get_PointerTo_MemberServiceV3__GetEncryptionKey(struct soap*, _MemberServiceV3__GetEncryptionKey **, const char*, const char*);
SOAP_FMAC3 _MemberServiceV3__GetEncryptionKey ** SOAP_FMAC4 soap_in_PointerTo_MemberServiceV3__GetEncryptionKey(struct soap*, const char*, _MemberServiceV3__GetEncryptionKey **, const char*);

#ifndef SOAP_TYPE_WS_MemberService_v3_PointerTo_MemberServiceV3__CheckUserExistsResponse
#define SOAP_TYPE_WS_MemberService_v3_PointerTo_MemberServiceV3__CheckUserExistsResponse (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_MemberServiceV3__CheckUserExistsResponse(struct soap*, _MemberServiceV3__CheckUserExistsResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_MemberServiceV3__CheckUserExistsResponse(struct soap*, _MemberServiceV3__CheckUserExistsResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_MemberServiceV3__CheckUserExistsResponse(struct soap*, const char *, int, _MemberServiceV3__CheckUserExistsResponse *const*, const char *);
SOAP_FMAC3 _MemberServiceV3__CheckUserExistsResponse ** SOAP_FMAC4 soap_get_PointerTo_MemberServiceV3__CheckUserExistsResponse(struct soap*, _MemberServiceV3__CheckUserExistsResponse **, const char*, const char*);
SOAP_FMAC3 _MemberServiceV3__CheckUserExistsResponse ** SOAP_FMAC4 soap_in_PointerTo_MemberServiceV3__CheckUserExistsResponse(struct soap*, const char*, _MemberServiceV3__CheckUserExistsResponse **, const char*);

#ifndef SOAP_TYPE_WS_MemberService_v3_PointerTo_MemberServiceV3__CheckUserExists
#define SOAP_TYPE_WS_MemberService_v3_PointerTo_MemberServiceV3__CheckUserExists (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_MemberServiceV3__CheckUserExists(struct soap*, _MemberServiceV3__CheckUserExists *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_MemberServiceV3__CheckUserExists(struct soap*, _MemberServiceV3__CheckUserExists *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_MemberServiceV3__CheckUserExists(struct soap*, const char *, int, _MemberServiceV3__CheckUserExists *const*, const char *);
SOAP_FMAC3 _MemberServiceV3__CheckUserExists ** SOAP_FMAC4 soap_get_PointerTo_MemberServiceV3__CheckUserExists(struct soap*, _MemberServiceV3__CheckUserExists **, const char*, const char*);
SOAP_FMAC3 _MemberServiceV3__CheckUserExists ** SOAP_FMAC4 soap_in_PointerTo_MemberServiceV3__CheckUserExists(struct soap*, const char*, _MemberServiceV3__CheckUserExists **, const char*);

#ifndef SOAP_TYPE_WS_MemberService_v3_PointerTostd__string
#define SOAP_TYPE_WS_MemberService_v3_PointerTostd__string (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostd__string(struct soap*, std::string *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostd__string(struct soap*, std::string *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostd__string(struct soap*, const char *, int, std::string *const*, const char *);
SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_get_PointerTostd__string(struct soap*, std::string **, const char*, const char*);
SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_in_PointerTostd__string(struct soap*, const char*, std::string **, const char*);

#ifndef SOAP_TYPE_WS_MemberService_v3__QName
#define SOAP_TYPE_WS_MemberService_v3__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_WS_MemberService_v3_string
#define SOAP_TYPE_WS_MemberService_v3_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

} // namespace WS_MemberService_v3


#endif

/* End of WS_MemberService_v3H.h */
