/* WS_PhotoOrganiseClientLib.cpp
   Generated by gSOAP 2.7.10 from .\wsdl-h\PhotoOrganise.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#ifndef WITH_NOGLOBAL
#define WITH_NOGLOBAL
#endif
#define SOAP_FMAC3 static
#include "WS_PhotoOrganiseC.cpp"
#include "WS_PhotoOrganiseClient.cpp"

/* End of WS_PhotoOrganiseClientLib.cpp */
