/* WS_SnapUpServiceStub.h
   Generated by gSOAP 2.7.10 from .\wsdl-h\SnapUpService.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef WS_SnapUpServiceStub_H
#define WS_SnapUpServiceStub_H
#include <vector>
#ifndef WITH_NONAMESPACES
#define WITH_NONAMESPACES
#endif
#ifndef WITH_NOGLOBAL
#define WITH_NOGLOBAL
#endif
#include "stdsoap2.h"

namespace WS_SnapUpService {

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not redeclare here */

#endif

#if 0 /* volatile type: do not redeclare here */

#endif

#ifndef SOAP_TYPE_WS_SnapUpService__SnapUpService__DeviceUploadPhoto
#define SOAP_TYPE_WS_SnapUpService__SnapUpService__DeviceUploadPhoto (8)
/* SnapUpService:DeviceUploadPhoto */
class SOAP_CMAC _SnapUpService__DeviceUploadPhoto
{
public:
	std::string *nickname;	/* optional element of type xsd:string */
	std::string *password;	/* optional element of type xsd:string */
	std::string *base64StringPhoto;	/* optional element of type xsd:string */
	std::string *dateTime;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 8; } /* = unique id SOAP_TYPE_WS_SnapUpService__SnapUpService__DeviceUploadPhoto */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _SnapUpService__DeviceUploadPhoto() : nickname(NULL), password(NULL), base64StringPhoto(NULL), dateTime(NULL), soap(NULL) { }
	virtual ~_SnapUpService__DeviceUploadPhoto() { }
};
#endif

#ifndef SOAP_TYPE_WS_SnapUpService__SnapUpService__DeviceUploadPhotoResponse
#define SOAP_TYPE_WS_SnapUpService__SnapUpService__DeviceUploadPhotoResponse (9)
/* SnapUpService:DeviceUploadPhotoResponse */
class SOAP_CMAC _SnapUpService__DeviceUploadPhotoResponse
{
public:
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 9; } /* = unique id SOAP_TYPE_WS_SnapUpService__SnapUpService__DeviceUploadPhotoResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _SnapUpService__DeviceUploadPhotoResponse() : soap(NULL) { }
	virtual ~_SnapUpService__DeviceUploadPhotoResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS_SnapUpService__SnapUpService__JavaUploadPhoto
#define SOAP_TYPE_WS_SnapUpService__SnapUpService__JavaUploadPhoto (10)
/* SnapUpService:JavaUploadPhoto */
class SOAP_CMAC _SnapUpService__JavaUploadPhoto
{
public:
	std::string *encryptedWebMemberID;	/* optional element of type xsd:string */
	std::string *webPhotoCollectionID;	/* optional element of type xsd:string */
	std::string *base64StringPhoto;	/* optional element of type xsd:string */
	std::string *dateTime;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 10; } /* = unique id SOAP_TYPE_WS_SnapUpService__SnapUpService__JavaUploadPhoto */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _SnapUpService__JavaUploadPhoto() : encryptedWebMemberID(NULL), webPhotoCollectionID(NULL), base64StringPhoto(NULL), dateTime(NULL), soap(NULL) { }
	virtual ~_SnapUpService__JavaUploadPhoto() { }
};
#endif

#ifndef SOAP_TYPE_WS_SnapUpService__SnapUpService__JavaUploadPhotoResponse
#define SOAP_TYPE_WS_SnapUpService__SnapUpService__JavaUploadPhotoResponse (11)
/* SnapUpService:JavaUploadPhotoResponse */
class SOAP_CMAC _SnapUpService__JavaUploadPhotoResponse
{
public:
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 11; } /* = unique id SOAP_TYPE_WS_SnapUpService__SnapUpService__JavaUploadPhotoResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _SnapUpService__JavaUploadPhotoResponse() : soap(NULL) { }
	virtual ~_SnapUpService__JavaUploadPhotoResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS_SnapUpService___SnapUpService2__DeviceUploadPhoto
#define SOAP_TYPE_WS_SnapUpService___SnapUpService2__DeviceUploadPhoto (18)
/* Operation wrapper: */
struct __SnapUpService2__DeviceUploadPhoto
{
public:
	_SnapUpService__DeviceUploadPhoto *SnapUpService__DeviceUploadPhoto;	/* optional element of type SnapUpService:DeviceUploadPhoto */
};
#endif

#ifndef SOAP_TYPE_WS_SnapUpService___SnapUpService2__JavaUploadPhoto
#define SOAP_TYPE_WS_SnapUpService___SnapUpService2__JavaUploadPhoto (22)
/* Operation wrapper: */
struct __SnapUpService2__JavaUploadPhoto
{
public:
	_SnapUpService__JavaUploadPhoto *SnapUpService__JavaUploadPhoto;	/* optional element of type SnapUpService:JavaUploadPhoto */
};
#endif

#ifndef SOAP_TYPE_WS_SnapUpService___SnapUpService3__DeviceUploadPhoto
#define SOAP_TYPE_WS_SnapUpService___SnapUpService3__DeviceUploadPhoto (24)
/* Operation wrapper: */
struct __SnapUpService3__DeviceUploadPhoto
{
public:
	_SnapUpService__DeviceUploadPhoto *SnapUpService__DeviceUploadPhoto;	/* optional element of type SnapUpService:DeviceUploadPhoto */
};
#endif

#ifndef SOAP_TYPE_WS_SnapUpService___SnapUpService3__JavaUploadPhoto
#define SOAP_TYPE_WS_SnapUpService___SnapUpService3__JavaUploadPhoto (26)
/* Operation wrapper: */
struct __SnapUpService3__JavaUploadPhoto
{
public:
	_SnapUpService__JavaUploadPhoto *SnapUpService__JavaUploadPhoto;	/* optional element of type SnapUpService:JavaUploadPhoto */
};
#endif

#ifndef SOAP_TYPE_WS_SnapUpService_SOAP_ENV__Header
#define SOAP_TYPE_WS_SnapUpService_SOAP_ENV__Header (27)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
private:
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_WS_SnapUpService_SOAP_ENV__Code
#define SOAP_TYPE_WS_SnapUpService_SOAP_ENV__Code (28)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
public:
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#ifndef SOAP_TYPE_WS_SnapUpService_SOAP_ENV__Detail
#define SOAP_TYPE_WS_SnapUpService_SOAP_ENV__Detail (30)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
public:
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
	char *__any;
};
#endif

#ifndef SOAP_TYPE_WS_SnapUpService_SOAP_ENV__Reason
#define SOAP_TYPE_WS_SnapUpService_SOAP_ENV__Reason (33)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
public:
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_WS_SnapUpService_SOAP_ENV__Fault
#define SOAP_TYPE_WS_SnapUpService_SOAP_ENV__Fault (34)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
public:
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE_WS_SnapUpService__QName
#define SOAP_TYPE_WS_SnapUpService__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE_WS_SnapUpService__XML
#define SOAP_TYPE_WS_SnapUpService__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Typedef Synonyms                                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Stubs                                                                      *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call___SnapUpService2__DeviceUploadPhoto(struct soap *soap, const char *soap_endpoint, const char *soap_action, _SnapUpService__DeviceUploadPhoto *SnapUpService__DeviceUploadPhoto, _SnapUpService__DeviceUploadPhotoResponse *SnapUpService__DeviceUploadPhotoResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___SnapUpService2__JavaUploadPhoto(struct soap *soap, const char *soap_endpoint, const char *soap_action, _SnapUpService__JavaUploadPhoto *SnapUpService__JavaUploadPhoto, _SnapUpService__JavaUploadPhotoResponse *SnapUpService__JavaUploadPhotoResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___SnapUpService3__DeviceUploadPhoto(struct soap *soap, const char *soap_endpoint, const char *soap_action, _SnapUpService__DeviceUploadPhoto *SnapUpService__DeviceUploadPhoto, _SnapUpService__DeviceUploadPhotoResponse *SnapUpService__DeviceUploadPhotoResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___SnapUpService3__JavaUploadPhoto(struct soap *soap, const char *soap_endpoint, const char *soap_action, _SnapUpService__JavaUploadPhoto *SnapUpService__JavaUploadPhoto, _SnapUpService__JavaUploadPhotoResponse *SnapUpService__JavaUploadPhotoResponse);

} // namespace WS_SnapUpService


#endif

/* End of WS_SnapUpServiceStub.h */
