// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.genetibase.askafriend.common.network.stub;


public class ArrayOfPrivateAAFQuestion {
    protected com.genetibase.askafriend.common.network.stub.PrivateAAFQuestion[] privateAAFQuestion;
    
    public ArrayOfPrivateAAFQuestion() {
    }
    
    public ArrayOfPrivateAAFQuestion(com.genetibase.askafriend.common.network.stub.PrivateAAFQuestion[] privateAAFQuestion) {
        this.privateAAFQuestion = privateAAFQuestion;
    }
    
    public com.genetibase.askafriend.common.network.stub.PrivateAAFQuestion[] getPrivateAAFQuestion() {
        return privateAAFQuestion;
    }
    
    public void setPrivateAAFQuestion(com.genetibase.askafriend.common.network.stub.PrivateAAFQuestion[] privateAAFQuestion) {
        this.privateAAFQuestion = privateAAFQuestion;
    }
}
