// This class was generated by 172 StubGenerator.
// Contents subject to change without notice.
// @generated

package com.genetibase.askafriend.common.network.stub;

import javax.xml.rpc.JAXRPCException;
import javax.xml.namespace.QName;
import javax.microedition.xml.rpc.Operation;
import javax.microedition.xml.rpc.Type;
import javax.microedition.xml.rpc.ComplexType;
import javax.microedition.xml.rpc.Element;

public class AskAFriendWSSoap_Stub implements com.genetibase.askafriend.common.network.stub.AskAFriendWSSoap, javax.xml.rpc.Stub {
	private String[] _propertyNames;
	private Object[] _propertyValues;

	public AskAFriendWSSoap_Stub() {
		_propertyNames = new String[] {ENDPOINT_ADDRESS_PROPERTY};
		_propertyValues = new Object[] {"http://services.next2friends.com/N2fWebServices/AskAFriend.asmx"};
	}

	public void _setProperty(String name, Object value) {
		int size = _propertyNames.length;
		for (int i = 0; i < size; ++i) {
			if (_propertyNames[i].equals(name)) {
				_propertyValues[i] = value;
				return;
			}
		}
		// Need to expand our array for a new property
		String[] newPropNames = new String[size + 1];
		System.arraycopy(_propertyNames, 0, newPropNames, 0, size);
		_propertyNames = newPropNames;
		Object[] newPropValues = new Object[size + 1];
		System.arraycopy(_propertyValues, 0, newPropValues, 0, size);
		_propertyValues = newPropValues;

		_propertyNames[size] = name;
		_propertyValues[size] = value;
	}

	public Object _getProperty(String name) {
		for (int i = 0; i < _propertyNames.length; ++i) {
			if (_propertyNames[i].equals(name)) {
				return _propertyValues[i];
			}
		}
		if (ENDPOINT_ADDRESS_PROPERTY.equals(name) || USERNAME_PROPERTY.equals(name) || PASSWORD_PROPERTY.equals(name)) {
			return null;
		}
		if (SESSION_MAINTAIN_PROPERTY.equals(name)) {
			return new java.lang.Boolean(false);
		}
		throw new JAXRPCException("Stub does not recognize property: "+name);
	}

	protected void _prepOperation(Operation op) {
		for (int i = 0; i < _propertyNames.length; ++i) {
			op.setProperty(_propertyNames[i], _propertyValues[i].toString());
		}
	}

	// 
	//  Begin user methods
	// 

	public com.genetibase.askafriend.common.network.stub.AskAFriendConfirm submitQuestion(java.lang.String webMemberID, java.lang.String webPassword, java.lang.String question, int numberOfPhotos, int responseType, com.genetibase.askafriend.common.network.stub.ArrayOfString customResponses, int duration, boolean isPrivate) throws java.rmi.RemoteException {
		// Copy the incoming values into an Object array if needed.
		Object[] inputObject = new Object[8];
		inputObject[0] = webMemberID;
		inputObject[1] = webPassword;
		inputObject[2] = question;
		inputObject[3] = new java.lang.Integer(numberOfPhotos);
		inputObject[4] = new java.lang.Integer(responseType);
		Object[] arrayOfStringObject;
		if (customResponses == null) {
			arrayOfStringObject = null;
		} else {
			arrayOfStringObject = new Object[1];
			arrayOfStringObject[0] = customResponses.getString();
		}
		inputObject[5] = arrayOfStringObject;
		inputObject[6] = new java.lang.Integer(duration);
		inputObject[7] = new java.lang.Boolean(isPrivate);

		Operation op = Operation.newInstance(_qname_SubmitQuestion, _type_SubmitQuestion, _type_SubmitQuestionResponse);
		_prepOperation(op);
		op.setProperty(Operation.SOAPACTION_URI_PROPERTY, "http://tempuri.org/SubmitQuestion");
		Object resultObj;
		try {
			resultObj = op.invoke(inputObject);
		} catch (JAXRPCException e) {
			Throwable cause = e.getLinkedCause();
			if (cause instanceof java.rmi.RemoteException) {
				throw (java.rmi.RemoteException) cause;
			}
			throw e;
		}
		com.genetibase.askafriend.common.network.stub.AskAFriendConfirm result;
		// Convert the result into the right Java type.
		// Unwrapped return value
		Object[] submitQuestionResultObj = (Object[]) ((Object[])resultObj)[0];
		if (submitQuestionResultObj == null) {
			result = null;
		} else {
			result = new com.genetibase.askafriend.common.network.stub.AskAFriendConfirm();
			java.lang.String string;
			Object advertURLObj = submitQuestionResultObj[0];
			string = (java.lang.String)advertURLObj;
			result.setAdvertURL(string);
			java.lang.String string2;
			Object advertImageObj = submitQuestionResultObj[1];
			string2 = (java.lang.String)advertImageObj;
			result.setAdvertImage(string2);
			java.lang.String string3;
			Object webAskAFriendIDObj = submitQuestionResultObj[2];
			string3 = (java.lang.String)webAskAFriendIDObj;
			result.setWebAskAFriendID(string3);
		}
		return result;
	}

	public com.genetibase.askafriend.common.network.stub.AttachPhotoResponse attachPhoto(java.lang.String webMemberID, java.lang.String webPassword, java.lang.String webAskAFriendID, int indexOrder, java.lang.String photoBase64String) throws java.rmi.RemoteException {
		// Copy the incoming values into an Object array if needed.
		Object[] inputObject = new Object[5];
		inputObject[0] = webMemberID;
		inputObject[1] = webPassword;
		inputObject[2] = webAskAFriendID;
		inputObject[3] = new java.lang.Integer(indexOrder);
		inputObject[4] = photoBase64String;

		Operation op = Operation.newInstance(_qname_AttachPhoto, _type_AttachPhoto, _type_AttachPhotoResponse);
		_prepOperation(op);
		op.setProperty(Operation.SOAPACTION_URI_PROPERTY, "http://tempuri.org/AttachPhoto");
		Object resultObj;
		try {
			resultObj = op.invoke(inputObject);
		} catch (JAXRPCException e) {
			Throwable cause = e.getLinkedCause();
			if (cause instanceof java.rmi.RemoteException) {
				throw (java.rmi.RemoteException) cause;
			}
			throw e;
		}
		com.genetibase.askafriend.common.network.stub.AttachPhotoResponse result;
		// Convert the result into the right Java type.
		if (resultObj == null) {
			result = null;
		} else {
			result = new com.genetibase.askafriend.common.network.stub.AttachPhotoResponse();
		}
		return result;
	}

	public com.genetibase.askafriend.common.network.stub.CompleteQuestionResponse completeQuestion(java.lang.String webMemberID, java.lang.String webPassword, java.lang.String webAskAFriendID) throws java.rmi.RemoteException {
		// Copy the incoming values into an Object array if needed.
		Object[] inputObject = new Object[3];
		inputObject[0] = webMemberID;
		inputObject[1] = webPassword;
		inputObject[2] = webAskAFriendID;

		Operation op = Operation.newInstance(_qname_CompleteQuestion, _type_CompleteQuestion, _type_CompleteQuestionResponse);
		_prepOperation(op);
		op.setProperty(Operation.SOAPACTION_URI_PROPERTY, "http://tempuri.org/CompleteQuestion");
		Object resultObj;
		try {
			resultObj = op.invoke(inputObject);
		} catch (JAXRPCException e) {
			Throwable cause = e.getLinkedCause();
			if (cause instanceof java.rmi.RemoteException) {
				throw (java.rmi.RemoteException) cause;
			}
			throw e;
		}
		com.genetibase.askafriend.common.network.stub.CompleteQuestionResponse result;
		// Convert the result into the right Java type.
		if (resultObj == null) {
			result = null;
		} else {
			result = new com.genetibase.askafriend.common.network.stub.CompleteQuestionResponse();
		}
		return result;
	}

	public com.genetibase.askafriend.common.network.stub.ArrayOfPrivateAAFQuestion getPrivateAAFQuestion(java.lang.String webMemberID, java.lang.String webPassword) throws java.rmi.RemoteException {
		// Copy the incoming values into an Object array if needed.
		Object[] inputObject = new Object[2];
		inputObject[0] = webMemberID;
		inputObject[1] = webPassword;

		Operation op = Operation.newInstance(_qname_GetPrivateAAFQuestion, _type_GetPrivateAAFQuestion, _type_GetPrivateAAFQuestionResponse);
		_prepOperation(op);
		op.setProperty(Operation.SOAPACTION_URI_PROPERTY, "http://tempuri.org/GetPrivateAAFQuestion");
		Object resultObj;
		try {
			resultObj = op.invoke(inputObject);
		} catch (JAXRPCException e) {
			Throwable cause = e.getLinkedCause();
			if (cause instanceof java.rmi.RemoteException) {
				throw (java.rmi.RemoteException) cause;
			}
			throw e;
		}
		com.genetibase.askafriend.common.network.stub.ArrayOfPrivateAAFQuestion result;
		// Convert the result into the right Java type.
		// Unwrapped return value
		Object[] getPrivateAAFQuestionResultObj = (Object[]) ((Object[])resultObj)[0];
		if (getPrivateAAFQuestionResultObj == null) {
			result = null;
		} else {
			result = new com.genetibase.askafriend.common.network.stub.ArrayOfPrivateAAFQuestion();
			com.genetibase.askafriend.common.network.stub.PrivateAAFQuestion[] privateAAFQuestionArray;
			Object[] privateAAFQuestionObj = (Object[]) getPrivateAAFQuestionResultObj[0];
			if (privateAAFQuestionObj == null) {
				privateAAFQuestionArray = null;
			} else {
				int privateAAFQuestionArraySize = privateAAFQuestionObj.length;
				privateAAFQuestionArray = new com.genetibase.askafriend.common.network.stub.PrivateAAFQuestion[privateAAFQuestionArraySize];
				for (int privateAAFQuestionArrayIndex = 0; 
					privateAAFQuestionArrayIndex < privateAAFQuestionArraySize; 
					++privateAAFQuestionArrayIndex) {
					if (privateAAFQuestionObj[privateAAFQuestionArrayIndex] == null) {
						privateAAFQuestionArray[privateAAFQuestionArrayIndex] = null;
					} else {
						privateAAFQuestionArray[privateAAFQuestionArrayIndex] = new com.genetibase.askafriend.common.network.stub.PrivateAAFQuestion();
						java.lang.String string;
						Object nickNameObj = ((Object[])privateAAFQuestionObj[privateAAFQuestionArrayIndex])[0];
						string = (java.lang.String)nickNameObj;
						privateAAFQuestionArray[privateAAFQuestionArrayIndex].setNickName(string);
						java.lang.String string2;
						Object questionObj = ((Object[])privateAAFQuestionObj[privateAAFQuestionArrayIndex])[1];
						string2 = (java.lang.String)questionObj;
						privateAAFQuestionArray[privateAAFQuestionArrayIndex].setQuestion(string2);
						java.lang.String string3;
						Object URLObj = ((Object[])privateAAFQuestionObj[privateAAFQuestionArrayIndex])[2];
						string3 = (java.lang.String)URLObj;
						privateAAFQuestionArray[privateAAFQuestionArrayIndex].setURL(string3);
						java.lang.String string4;
						Object dateTimePostedObj = ((Object[])privateAAFQuestionObj[privateAAFQuestionArrayIndex])[3];
						string4 = (java.lang.String)dateTimePostedObj;
						privateAAFQuestionArray[privateAAFQuestionArrayIndex].setDateTimePosted(string4);
					}
				}
			}
			result.setPrivateAAFQuestion(privateAAFQuestionArray);
		}
		return result;
	}

	public com.genetibase.askafriend.common.network.stub.ArrayOfAskAFriendQuestion getMyAAFQuestions(java.lang.String webMemberID, java.lang.String webPassword, java.lang.String lastWebAskAFriendID) throws java.rmi.RemoteException {
		// Copy the incoming values into an Object array if needed.
		Object[] inputObject = new Object[3];
		inputObject[0] = webMemberID;
		inputObject[1] = webPassword;
		inputObject[2] = lastWebAskAFriendID;

		Operation op = Operation.newInstance(_qname_GetMyAAFQuestions, _type_GetMyAAFQuestions, _type_GetMyAAFQuestionsResponse);
		_prepOperation(op);
		op.setProperty(Operation.SOAPACTION_URI_PROPERTY, "http://tempuri.org/GetMyAAFQuestions");
		Object resultObj;
		try {
			resultObj = op.invoke(inputObject);
		} catch (JAXRPCException e) {
			Throwable cause = e.getLinkedCause();
			if (cause instanceof java.rmi.RemoteException) {
				throw (java.rmi.RemoteException) cause;
			}
			throw e;
		}
		com.genetibase.askafriend.common.network.stub.ArrayOfAskAFriendQuestion result;
		// Convert the result into the right Java type.
		// Unwrapped return value
		Object[] getMyAAFQuestionsResultObj = (Object[]) ((Object[])resultObj)[0];
		if (getMyAAFQuestionsResultObj == null) {
			result = null;
		} else {
			result = new com.genetibase.askafriend.common.network.stub.ArrayOfAskAFriendQuestion();
			com.genetibase.askafriend.common.network.stub.AskAFriendQuestion[] askAFriendQuestionArray;
			Object[] askAFriendQuestionObj = (Object[]) getMyAAFQuestionsResultObj[0];
			if (askAFriendQuestionObj == null) {
				askAFriendQuestionArray = null;
			} else {
				int askAFriendQuestionArraySize = askAFriendQuestionObj.length;
				askAFriendQuestionArray = new com.genetibase.askafriend.common.network.stub.AskAFriendQuestion[askAFriendQuestionArraySize];
				for (int askAFriendQuestionArrayIndex = 0; 
					askAFriendQuestionArrayIndex < askAFriendQuestionArraySize; 
					++askAFriendQuestionArrayIndex) {
					if (askAFriendQuestionObj[askAFriendQuestionArrayIndex] == null) {
						askAFriendQuestionArray[askAFriendQuestionArrayIndex] = null;
					} else {
						askAFriendQuestionArray[askAFriendQuestionArrayIndex] = new com.genetibase.askafriend.common.network.stub.AskAFriendQuestion();
						java.lang.String string;
						Object webAskAFriendIDObj = ((Object[])askAFriendQuestionObj[askAFriendQuestionArrayIndex])[0];
						string = (java.lang.String)webAskAFriendIDObj;
						askAFriendQuestionArray[askAFriendQuestionArrayIndex].setWebAskAFriendID(string);
						java.lang.String string2;
						Object questionObj = ((Object[])askAFriendQuestionObj[askAFriendQuestionArrayIndex])[1];
						string2 = (java.lang.String)questionObj;
						askAFriendQuestionArray[askAFriendQuestionArrayIndex].setQuestion(string2);
					}
				}
			}
			result.setAskAFriendQuestion(askAFriendQuestionArray);
		}
		return result;
	}

	public com.genetibase.askafriend.common.network.stub.ArrayOfString getNewAAFQuestionCommentIDs(java.lang.String webMemberID, java.lang.String webPassword, com.genetibase.askafriend.common.network.stub.ArrayOfString webAskAFriendIDs, com.genetibase.askafriend.common.network.stub.ArrayOfString webLastAskAFriendQuestionIDs) throws java.rmi.RemoteException {
		// Copy the incoming values into an Object array if needed.
		Object[] inputObject = new Object[4];
		inputObject[0] = webMemberID;
		inputObject[1] = webPassword;
		Object[] arrayOfStringObject;
		if (webAskAFriendIDs == null) {
			arrayOfStringObject = null;
		} else {
			arrayOfStringObject = new Object[1];
			arrayOfStringObject[0] = webAskAFriendIDs.getString();
		}
		inputObject[2] = arrayOfStringObject;
		Object[] arrayOfStringObject2;
		if (webLastAskAFriendQuestionIDs == null) {
			arrayOfStringObject2 = null;
		} else {
			arrayOfStringObject2 = new Object[1];
			arrayOfStringObject2[0] = webLastAskAFriendQuestionIDs.getString();
		}
		inputObject[3] = arrayOfStringObject2;

		Operation op = Operation.newInstance(_qname_GetNewAAFQuestionCommentIDs, _type_GetNewAAFQuestionCommentIDs, _type_GetNewAAFQuestionCommentIDsResponse);
		_prepOperation(op);
		op.setProperty(Operation.SOAPACTION_URI_PROPERTY, "http://tempuri.org/GetNewAAFQuestionCommentIDs");
		Object resultObj;
		try {
			resultObj = op.invoke(inputObject);
		} catch (JAXRPCException e) {
			Throwable cause = e.getLinkedCause();
			if (cause instanceof java.rmi.RemoteException) {
				throw (java.rmi.RemoteException) cause;
			}
			throw e;
		}
		com.genetibase.askafriend.common.network.stub.ArrayOfString result;
		// Convert the result into the right Java type.
		// Unwrapped return value
		Object[] getNewAAFQuestionCommentIDsResultObj = (Object[]) ((Object[])resultObj)[0];
		if (getNewAAFQuestionCommentIDsResultObj == null) {
			result = null;
		} else {
			result = new com.genetibase.askafriend.common.network.stub.ArrayOfString();
			java.lang.String[] stringArray;
			Object stringObj = getNewAAFQuestionCommentIDsResultObj[0];
			stringArray = (java.lang.String[]) stringObj;
			result.setString(stringArray);
		}
		return result;
	}

	public com.genetibase.askafriend.common.network.stub.AskAFriendResponse getAAFResponse(java.lang.String webMemberID, java.lang.String webPassword, java.lang.String webAskAFriendID) throws java.rmi.RemoteException {
		// Copy the incoming values into an Object array if needed.
		Object[] inputObject = new Object[3];
		inputObject[0] = webMemberID;
		inputObject[1] = webPassword;
		inputObject[2] = webAskAFriendID;

		Operation op = Operation.newInstance(_qname_GetAAFResponse, _type_GetAAFResponse, _type_GetAAFResponseResponse);
		_prepOperation(op);
		op.setProperty(Operation.SOAPACTION_URI_PROPERTY, "http://tempuri.org/GetAAFResponse");
		Object resultObj;
		try {
			resultObj = op.invoke(inputObject);
		} catch (JAXRPCException e) {
			Throwable cause = e.getLinkedCause();
			if (cause instanceof java.rmi.RemoteException) {
				throw (java.rmi.RemoteException) cause;
			}
			throw e;
		}
		com.genetibase.askafriend.common.network.stub.AskAFriendResponse result;
		// Convert the result into the right Java type.
		// Unwrapped return value
		Object[] getAAFResponseResultObj = (Object[]) ((Object[])resultObj)[0];
		if (getAAFResponseResultObj == null) {
			result = null;
		} else {
			result = new com.genetibase.askafriend.common.network.stub.AskAFriendResponse();
			java.lang.String string;
			Object webAskAFriendIDObj = getAAFResponseResultObj[0];
			string = (java.lang.String)webAskAFriendIDObj;
			result.setWebAskAFriendID(string);
			java.lang.String string2;
			Object questionObj = getAAFResponseResultObj[1];
			string2 = (java.lang.String)questionObj;
			result.setQuestion(string2);
			java.lang.String string3;
			Object photoBase64BinaryObj = getAAFResponseResultObj[2];
			string3 = (java.lang.String)photoBase64BinaryObj;
			result.setPhotoBase64Binary(string3);
			com.genetibase.askafriend.common.network.stub.ArrayOfInt arrayOfInt;
			Object[] responseValuesObj = (Object[]) getAAFResponseResultObj[3];
			if (responseValuesObj == null) {
				arrayOfInt = null;
			} else {
				arrayOfInt = new com.genetibase.askafriend.common.network.stub.ArrayOfInt();
				int[] intArray;
				Object _intObj = responseValuesObj[0];
				intArray = (int[]) _intObj;
				arrayOfInt.set_int(intArray);
			}
			result.setResponseValues(arrayOfInt);
			double a_double;
			Object averageObj = getAAFResponseResultObj[4];
			a_double = ((java.lang.Double)averageObj).doubleValue();
			result.setAverage(a_double);
			int a_int;
			Object responseTypeObj = getAAFResponseResultObj[5];
			a_int = ((java.lang.Integer)responseTypeObj).intValue();
			result.setResponseType(a_int);
			com.genetibase.askafriend.common.network.stub.ArrayOfString arrayOfString;
			Object[] customResponsesObj = (Object[]) getAAFResponseResultObj[6];
			if (customResponsesObj == null) {
				arrayOfString = null;
			} else {
				arrayOfString = new com.genetibase.askafriend.common.network.stub.ArrayOfString();
				java.lang.String[] stringArray;
				Object stringObj = customResponsesObj[0];
				stringArray = (java.lang.String[]) stringObj;
				arrayOfString.setString(stringArray);
			}
			result.setCustomResponses(arrayOfString);
		}
		return result;
	}

	public com.genetibase.askafriend.common.network.stub.ArrayOfAskAFriendComment getAAFComments(java.lang.String webMemberID, java.lang.String webPassword, java.lang.String webAskAFriendID, java.lang.String lastWebAskAFriendCommentID) throws java.rmi.RemoteException {
		// Copy the incoming values into an Object array if needed.
		Object[] inputObject = new Object[4];
		inputObject[0] = webMemberID;
		inputObject[1] = webPassword;
		inputObject[2] = webAskAFriendID;
		inputObject[3] = lastWebAskAFriendCommentID;

		Operation op = Operation.newInstance(_qname_GetAAFComments, _type_GetAAFComments, _type_GetAAFCommentsResponse);
		_prepOperation(op);
		op.setProperty(Operation.SOAPACTION_URI_PROPERTY, "http://tempuri.org/GetAAFComments");
		Object resultObj;
		try {
			resultObj = op.invoke(inputObject);
		} catch (JAXRPCException e) {
			Throwable cause = e.getLinkedCause();
			if (cause instanceof java.rmi.RemoteException) {
				throw (java.rmi.RemoteException) cause;
			}
			throw e;
		}
		com.genetibase.askafriend.common.network.stub.ArrayOfAskAFriendComment result;
		// Convert the result into the right Java type.
		// Unwrapped return value
		Object[] getAAFCommentsResultObj = (Object[]) ((Object[])resultObj)[0];
		if (getAAFCommentsResultObj == null) {
			result = null;
		} else {
			result = new com.genetibase.askafriend.common.network.stub.ArrayOfAskAFriendComment();
			com.genetibase.askafriend.common.network.stub.AskAFriendComment[] askAFriendCommentArray;
			Object[] askAFriendCommentObj = (Object[]) getAAFCommentsResultObj[0];
			if (askAFriendCommentObj == null) {
				askAFriendCommentArray = null;
			} else {
				int askAFriendCommentArraySize = askAFriendCommentObj.length;
				askAFriendCommentArray = new com.genetibase.askafriend.common.network.stub.AskAFriendComment[askAFriendCommentArraySize];
				for (int askAFriendCommentArrayIndex = 0; 
					askAFriendCommentArrayIndex < askAFriendCommentArraySize; 
					++askAFriendCommentArrayIndex) {
					if (askAFriendCommentObj[askAFriendCommentArrayIndex] == null) {
						askAFriendCommentArray[askAFriendCommentArrayIndex] = null;
					} else {
						askAFriendCommentArray[askAFriendCommentArrayIndex] = new com.genetibase.askafriend.common.network.stub.AskAFriendComment();
						java.lang.String string;
						Object nickNameObj = ((Object[])askAFriendCommentObj[askAFriendCommentArrayIndex])[0];
						string = (java.lang.String)nickNameObj;
						askAFriendCommentArray[askAFriendCommentArrayIndex].setNickName(string);
						java.lang.String string2;
						Object webMemberIDObj = ((Object[])askAFriendCommentObj[askAFriendCommentArrayIndex])[1];
						string2 = (java.lang.String)webMemberIDObj;
						askAFriendCommentArray[askAFriendCommentArrayIndex].setWebMemberID(string2);
						java.lang.String string3;
						Object webAskAFriendCommentIDObj = ((Object[])askAFriendCommentObj[askAFriendCommentArrayIndex])[2];
						string3 = (java.lang.String)webAskAFriendCommentIDObj;
						askAFriendCommentArray[askAFriendCommentArrayIndex].setWebAskAFriendCommentID(string3);
						java.lang.String string4;
						Object textObj = ((Object[])askAFriendCommentObj[askAFriendCommentArrayIndex])[3];
						string4 = (java.lang.String)textObj;
						askAFriendCommentArray[askAFriendCommentArrayIndex].setText(string4);
						java.lang.String string5;
						Object dateTimePostedObj = ((Object[])askAFriendCommentObj[askAFriendCommentArrayIndex])[4];
						string5 = (java.lang.String)dateTimePostedObj;
						askAFriendCommentArray[askAFriendCommentArrayIndex].setDateTimePosted(string5);
					}
				}
			}
			result.setAskAFriendComment(askAFriendCommentArray);
		}
		return result;
	}
	// 
	//  End user methods
	// 

	protected static final QName _qname_AdvertImage = new QName("http://tempuri.org/", "AdvertImage");
	protected static final QName _qname_AdvertURL = new QName("http://tempuri.org/", "AdvertURL");
	protected static final QName _qname_AskAFriendComment = new QName("http://tempuri.org/", "AskAFriendComment");
	protected static final QName _qname_AskAFriendQuestion = new QName("http://tempuri.org/", "AskAFriendQuestion");
	protected static final QName _qname_AttachPhoto = new QName("http://tempuri.org/", "AttachPhoto");
	protected static final QName _qname_AttachPhotoResponse = new QName("http://tempuri.org/", "AttachPhotoResponse");
	protected static final QName _qname_Average = new QName("http://tempuri.org/", "Average");
	protected static final QName _qname_CompleteQuestion = new QName("http://tempuri.org/", "CompleteQuestion");
	protected static final QName _qname_CompleteQuestionResponse = new QName("http://tempuri.org/", "CompleteQuestionResponse");
	protected static final QName _qname_CustomResponses = new QName("http://tempuri.org/", "CustomResponses");
	protected static final QName _qname_DateTimePosted = new QName("http://tempuri.org/", "DateTimePosted");
	protected static final QName _qname_Duration = new QName("http://tempuri.org/", "Duration");
	protected static final QName _qname_GetAAFComments = new QName("http://tempuri.org/", "GetAAFComments");
	protected static final QName _qname_GetAAFCommentsResponse = new QName("http://tempuri.org/", "GetAAFCommentsResponse");
	protected static final QName _qname_GetAAFCommentsResult = new QName("http://tempuri.org/", "GetAAFCommentsResult");
	protected static final QName _qname_GetAAFResponse = new QName("http://tempuri.org/", "GetAAFResponse");
	protected static final QName _qname_GetAAFResponseResponse = new QName("http://tempuri.org/", "GetAAFResponseResponse");
	protected static final QName _qname_GetAAFResponseResult = new QName("http://tempuri.org/", "GetAAFResponseResult");
	protected static final QName _qname_GetMyAAFQuestions = new QName("http://tempuri.org/", "GetMyAAFQuestions");
	protected static final QName _qname_GetMyAAFQuestionsResponse = new QName("http://tempuri.org/", "GetMyAAFQuestionsResponse");
	protected static final QName _qname_GetMyAAFQuestionsResult = new QName("http://tempuri.org/", "GetMyAAFQuestionsResult");
	protected static final QName _qname_GetNewAAFQuestionCommentIDs = new QName("http://tempuri.org/", "GetNewAAFQuestionCommentIDs");
	protected static final QName _qname_GetNewAAFQuestionCommentIDsResponse = new QName("http://tempuri.org/", "GetNewAAFQuestionCommentIDsResponse");
	protected static final QName _qname_GetNewAAFQuestionCommentIDsResult = new QName("http://tempuri.org/", "GetNewAAFQuestionCommentIDsResult");
	protected static final QName _qname_GetPrivateAAFQuestion = new QName("http://tempuri.org/", "GetPrivateAAFQuestion");
	protected static final QName _qname_GetPrivateAAFQuestionResponse = new QName("http://tempuri.org/", "GetPrivateAAFQuestionResponse");
	protected static final QName _qname_GetPrivateAAFQuestionResult = new QName("http://tempuri.org/", "GetPrivateAAFQuestionResult");
	protected static final QName _qname_IndexOrder = new QName("http://tempuri.org/", "IndexOrder");
	protected static final QName _qname_IsPrivate = new QName("http://tempuri.org/", "IsPrivate");
	protected static final QName _qname_LastWebAskAFriendCommentID = new QName("http://tempuri.org/", "LastWebAskAFriendCommentID");
	protected static final QName _qname_LastWebAskAFriendID = new QName("http://tempuri.org/", "LastWebAskAFriendID");
	protected static final QName _qname_NickName = new QName("http://tempuri.org/", "NickName");
	protected static final QName _qname_NumberOfPhotos = new QName("http://tempuri.org/", "NumberOfPhotos");
	protected static final QName _qname_PhotoBase64Binary = new QName("http://tempuri.org/", "PhotoBase64Binary");
	protected static final QName _qname_PhotoBase64String = new QName("http://tempuri.org/", "PhotoBase64String");
	protected static final QName _qname_PrivateAAFQuestion = new QName("http://tempuri.org/", "PrivateAAFQuestion");
	protected static final QName _qname_Question = new QName("http://tempuri.org/", "Question");
	protected static final QName _qname_ResponseType = new QName("http://tempuri.org/", "ResponseType");
	protected static final QName _qname_ResponseValues = new QName("http://tempuri.org/", "ResponseValues");
	protected static final QName _qname_SubmitQuestion = new QName("http://tempuri.org/", "SubmitQuestion");
	protected static final QName _qname_SubmitQuestionResponse = new QName("http://tempuri.org/", "SubmitQuestionResponse");
	protected static final QName _qname_SubmitQuestionResult = new QName("http://tempuri.org/", "SubmitQuestionResult");
	protected static final QName _qname_Text = new QName("http://tempuri.org/", "Text");
	protected static final QName _qname_URL = new QName("http://tempuri.org/", "URL");
	protected static final QName _qname_WebAskAFriendCommentID = new QName("http://tempuri.org/", "WebAskAFriendCommentID");
	protected static final QName _qname_WebAskAFriendID = new QName("http://tempuri.org/", "WebAskAFriendID");
	protected static final QName _qname_WebAskAFriendIDs = new QName("http://tempuri.org/", "WebAskAFriendIDs");
	protected static final QName _qname_WebLastAskAFriendQuestionIDs = new QName("http://tempuri.org/", "WebLastAskAFriendQuestionIDs");
	protected static final QName _qname_WebMemberID = new QName("http://tempuri.org/", "WebMemberID");
	protected static final QName _qname_WebPassword = new QName("http://tempuri.org/", "WebPassword");
	protected static final QName _qname_int = new QName("http://tempuri.org/", "int");
	protected static final QName _qname_string = new QName("http://tempuri.org/", "string");
	protected static final Element _type_SubmitQuestion;
	protected static final Element _type_SubmitQuestionResponse;
	protected static final Element _type_AttachPhoto;
	protected static final Element _type_AttachPhotoResponse;
	protected static final Element _type_CompleteQuestion;
	protected static final Element _type_CompleteQuestionResponse;
	protected static final Element _type_GetPrivateAAFQuestion;
	protected static final Element _type_GetPrivateAAFQuestionResponse;
	protected static final Element _type_GetMyAAFQuestions;
	protected static final Element _type_GetMyAAFQuestionsResponse;
	protected static final Element _type_GetNewAAFQuestionCommentIDs;
	protected static final Element _type_GetNewAAFQuestionCommentIDsResponse;
	protected static final Element _type_GetAAFResponse;
	protected static final Element _type_GetAAFResponseResponse;
	protected static final Element _type_GetAAFComments;
	protected static final Element _type_GetAAFCommentsResponse;
	static {
		// Create all of the Type's that this stub uses, once.
		Element _type_WebMemberID;
		_type_WebMemberID = new Element(_qname_WebMemberID, Type.STRING, 0, 1, false);
		Element _type_WebPassword;
		_type_WebPassword = new Element(_qname_WebPassword, Type.STRING, 0, 1, false);
		Element _type_Question;
		_type_Question = new Element(_qname_Question, Type.STRING, 0, 1, false);
		Element _type_NumberOfPhotos;
		_type_NumberOfPhotos = new Element(_qname_NumberOfPhotos, Type.INT);
		Element _type_ResponseType;
		_type_ResponseType = new Element(_qname_ResponseType, Type.INT);
		Element _type_string;
		_type_string = new Element(_qname_string, Type.STRING, 0, -1, true);
		ComplexType _complexType_arrayOfString;
		_complexType_arrayOfString = new ComplexType();
		_complexType_arrayOfString.elements = new Element[1];
		_complexType_arrayOfString.elements[0] = _type_string;
		Element _type_CustomResponses;
		_type_CustomResponses = new Element(_qname_CustomResponses, _complexType_arrayOfString, 0, 1, false);
		Element _type_Duration;
		_type_Duration = new Element(_qname_Duration, Type.INT);
		Element _type_IsPrivate;
		_type_IsPrivate = new Element(_qname_IsPrivate, Type.BOOLEAN);
		ComplexType _complexType_submitQuestion;
		_complexType_submitQuestion = new ComplexType();
		_complexType_submitQuestion.elements = new Element[8];
		_complexType_submitQuestion.elements[0] = _type_WebMemberID;
		_complexType_submitQuestion.elements[1] = _type_WebPassword;
		_complexType_submitQuestion.elements[2] = _type_Question;
		_complexType_submitQuestion.elements[3] = _type_NumberOfPhotos;
		_complexType_submitQuestion.elements[4] = _type_ResponseType;
		_complexType_submitQuestion.elements[5] = _type_CustomResponses;
		_complexType_submitQuestion.elements[6] = _type_Duration;
		_complexType_submitQuestion.elements[7] = _type_IsPrivate;
		_type_SubmitQuestion = new Element(_qname_SubmitQuestion, _complexType_submitQuestion);
		Element _type_AdvertURL;
		_type_AdvertURL = new Element(_qname_AdvertURL, Type.STRING, 0, 1, false);
		Element _type_AdvertImage;
		_type_AdvertImage = new Element(_qname_AdvertImage, Type.STRING, 0, 1, false);
		Element _type_WebAskAFriendID;
		_type_WebAskAFriendID = new Element(_qname_WebAskAFriendID, Type.STRING, 0, 1, false);
		ComplexType _complexType_askAFriendConfirm;
		_complexType_askAFriendConfirm = new ComplexType();
		_complexType_askAFriendConfirm.elements = new Element[3];
		_complexType_askAFriendConfirm.elements[0] = _type_AdvertURL;
		_complexType_askAFriendConfirm.elements[1] = _type_AdvertImage;
		_complexType_askAFriendConfirm.elements[2] = _type_WebAskAFriendID;
		Element _type_SubmitQuestionResult;
		_type_SubmitQuestionResult = new Element(_qname_SubmitQuestionResult, _complexType_askAFriendConfirm, 0, 1, false);
		ComplexType _complexType_submitQuestionResponse;
		_complexType_submitQuestionResponse = new ComplexType();
		_complexType_submitQuestionResponse.elements = new Element[1];
		_complexType_submitQuestionResponse.elements[0] = _type_SubmitQuestionResult;
		_type_SubmitQuestionResponse = new Element(_qname_SubmitQuestionResponse, _complexType_submitQuestionResponse);
		Element _type_IndexOrder;
		_type_IndexOrder = new Element(_qname_IndexOrder, Type.INT);
		Element _type_PhotoBase64String;
		_type_PhotoBase64String = new Element(_qname_PhotoBase64String, Type.STRING, 0, 1, false);
		ComplexType _complexType_attachPhoto;
		_complexType_attachPhoto = new ComplexType();
		_complexType_attachPhoto.elements = new Element[5];
		_complexType_attachPhoto.elements[0] = _type_WebMemberID;
		_complexType_attachPhoto.elements[1] = _type_WebPassword;
		_complexType_attachPhoto.elements[2] = _type_WebAskAFriendID;
		_complexType_attachPhoto.elements[3] = _type_IndexOrder;
		_complexType_attachPhoto.elements[4] = _type_PhotoBase64String;
		_type_AttachPhoto = new Element(_qname_AttachPhoto, _complexType_attachPhoto);
		ComplexType _complexType_attachPhotoResponse;
		_complexType_attachPhotoResponse = new ComplexType();
		_complexType_attachPhotoResponse.elements = new Element[0];
		_type_AttachPhotoResponse = new Element(_qname_AttachPhotoResponse, _complexType_attachPhotoResponse);
		ComplexType _complexType_completeQuestion;
		_complexType_completeQuestion = new ComplexType();
		_complexType_completeQuestion.elements = new Element[3];
		_complexType_completeQuestion.elements[0] = _type_WebMemberID;
		_complexType_completeQuestion.elements[1] = _type_WebPassword;
		_complexType_completeQuestion.elements[2] = _type_WebAskAFriendID;
		_type_CompleteQuestion = new Element(_qname_CompleteQuestion, _complexType_completeQuestion);
		_type_CompleteQuestionResponse = new Element(_qname_CompleteQuestionResponse, _complexType_attachPhotoResponse);
		ComplexType _complexType_getPrivateAAFQuestion;
		_complexType_getPrivateAAFQuestion = new ComplexType();
		_complexType_getPrivateAAFQuestion.elements = new Element[2];
		_complexType_getPrivateAAFQuestion.elements[0] = _type_WebMemberID;
		_complexType_getPrivateAAFQuestion.elements[1] = _type_WebPassword;
		_type_GetPrivateAAFQuestion = new Element(_qname_GetPrivateAAFQuestion, _complexType_getPrivateAAFQuestion);
		Element _type_NickName;
		_type_NickName = new Element(_qname_NickName, Type.STRING, 0, 1, false);
		Element _type_URL;
		_type_URL = new Element(_qname_URL, Type.STRING, 0, 1, false);
		Element _type_DateTimePosted;
		_type_DateTimePosted = new Element(_qname_DateTimePosted, Type.STRING, 0, 1, false);
		ComplexType _complexType_privateAAFQuestion;
		_complexType_privateAAFQuestion = new ComplexType();
		_complexType_privateAAFQuestion.elements = new Element[4];
		_complexType_privateAAFQuestion.elements[0] = _type_NickName;
		_complexType_privateAAFQuestion.elements[1] = _type_Question;
		_complexType_privateAAFQuestion.elements[2] = _type_URL;
		_complexType_privateAAFQuestion.elements[3] = _type_DateTimePosted;
		Element _type_PrivateAAFQuestion;
		_type_PrivateAAFQuestion = new Element(_qname_PrivateAAFQuestion, _complexType_privateAAFQuestion, 0, -1, true);
		ComplexType _complexType_arrayOfPrivateAAFQuestion;
		_complexType_arrayOfPrivateAAFQuestion = new ComplexType();
		_complexType_arrayOfPrivateAAFQuestion.elements = new Element[1];
		_complexType_arrayOfPrivateAAFQuestion.elements[0] = _type_PrivateAAFQuestion;
		Element _type_GetPrivateAAFQuestionResult;
		_type_GetPrivateAAFQuestionResult = new Element(_qname_GetPrivateAAFQuestionResult, _complexType_arrayOfPrivateAAFQuestion, 0, 1, false);
		ComplexType _complexType_getPrivateAAFQuestionResponse;
		_complexType_getPrivateAAFQuestionResponse = new ComplexType();
		_complexType_getPrivateAAFQuestionResponse.elements = new Element[1];
		_complexType_getPrivateAAFQuestionResponse.elements[0] = _type_GetPrivateAAFQuestionResult;
		_type_GetPrivateAAFQuestionResponse = new Element(_qname_GetPrivateAAFQuestionResponse, _complexType_getPrivateAAFQuestionResponse);
		Element _type_LastWebAskAFriendID;
		_type_LastWebAskAFriendID = new Element(_qname_LastWebAskAFriendID, Type.STRING, 0, 1, false);
		ComplexType _complexType_getMyAAFQuestions;
		_complexType_getMyAAFQuestions = new ComplexType();
		_complexType_getMyAAFQuestions.elements = new Element[3];
		_complexType_getMyAAFQuestions.elements[0] = _type_WebMemberID;
		_complexType_getMyAAFQuestions.elements[1] = _type_WebPassword;
		_complexType_getMyAAFQuestions.elements[2] = _type_LastWebAskAFriendID;
		_type_GetMyAAFQuestions = new Element(_qname_GetMyAAFQuestions, _complexType_getMyAAFQuestions);
		ComplexType _complexType_askAFriendQuestion;
		_complexType_askAFriendQuestion = new ComplexType();
		_complexType_askAFriendQuestion.elements = new Element[2];
		_complexType_askAFriendQuestion.elements[0] = _type_WebAskAFriendID;
		_complexType_askAFriendQuestion.elements[1] = _type_Question;
		Element _type_AskAFriendQuestion;
		_type_AskAFriendQuestion = new Element(_qname_AskAFriendQuestion, _complexType_askAFriendQuestion, 0, -1, true);
		ComplexType _complexType_arrayOfAskAFriendQuestion;
		_complexType_arrayOfAskAFriendQuestion = new ComplexType();
		_complexType_arrayOfAskAFriendQuestion.elements = new Element[1];
		_complexType_arrayOfAskAFriendQuestion.elements[0] = _type_AskAFriendQuestion;
		Element _type_GetMyAAFQuestionsResult;
		_type_GetMyAAFQuestionsResult = new Element(_qname_GetMyAAFQuestionsResult, _complexType_arrayOfAskAFriendQuestion, 0, 1, false);
		ComplexType _complexType_getMyAAFQuestionsResponse;
		_complexType_getMyAAFQuestionsResponse = new ComplexType();
		_complexType_getMyAAFQuestionsResponse.elements = new Element[1];
		_complexType_getMyAAFQuestionsResponse.elements[0] = _type_GetMyAAFQuestionsResult;
		_type_GetMyAAFQuestionsResponse = new Element(_qname_GetMyAAFQuestionsResponse, _complexType_getMyAAFQuestionsResponse);
		Element _type_WebAskAFriendIDs;
		_type_WebAskAFriendIDs = new Element(_qname_WebAskAFriendIDs, _complexType_arrayOfString, 0, 1, false);
		Element _type_WebLastAskAFriendQuestionIDs;
		_type_WebLastAskAFriendQuestionIDs = new Element(_qname_WebLastAskAFriendQuestionIDs, _complexType_arrayOfString, 0, 1, false);
		ComplexType _complexType_getNewAAFQuestionCommentIDs;
		_complexType_getNewAAFQuestionCommentIDs = new ComplexType();
		_complexType_getNewAAFQuestionCommentIDs.elements = new Element[4];
		_complexType_getNewAAFQuestionCommentIDs.elements[0] = _type_WebMemberID;
		_complexType_getNewAAFQuestionCommentIDs.elements[1] = _type_WebPassword;
		_complexType_getNewAAFQuestionCommentIDs.elements[2] = _type_WebAskAFriendIDs;
		_complexType_getNewAAFQuestionCommentIDs.elements[3] = _type_WebLastAskAFriendQuestionIDs;
		_type_GetNewAAFQuestionCommentIDs = new Element(_qname_GetNewAAFQuestionCommentIDs, _complexType_getNewAAFQuestionCommentIDs);
		Element _type_GetNewAAFQuestionCommentIDsResult;
		_type_GetNewAAFQuestionCommentIDsResult = new Element(_qname_GetNewAAFQuestionCommentIDsResult, _complexType_arrayOfString, 0, 1, false);
		ComplexType _complexType_getNewAAFQuestionCommentIDsResponse;
		_complexType_getNewAAFQuestionCommentIDsResponse = new ComplexType();
		_complexType_getNewAAFQuestionCommentIDsResponse.elements = new Element[1];
		_complexType_getNewAAFQuestionCommentIDsResponse.elements[0] = _type_GetNewAAFQuestionCommentIDsResult;
		_type_GetNewAAFQuestionCommentIDsResponse = new Element(_qname_GetNewAAFQuestionCommentIDsResponse, _complexType_getNewAAFQuestionCommentIDsResponse);
		_type_GetAAFResponse = new Element(_qname_GetAAFResponse, _complexType_completeQuestion);
		Element _type_PhotoBase64Binary;
		_type_PhotoBase64Binary = new Element(_qname_PhotoBase64Binary, Type.STRING, 0, 1, false);
		Element _type_int;
		_type_int = new Element(_qname_int, Type.INT, 0, -1, false);
		ComplexType _complexType_arrayOfInt;
		_complexType_arrayOfInt = new ComplexType();
		_complexType_arrayOfInt.elements = new Element[1];
		_complexType_arrayOfInt.elements[0] = _type_int;
		Element _type_ResponseValues;
		_type_ResponseValues = new Element(_qname_ResponseValues, _complexType_arrayOfInt, 0, 1, false);
		Element _type_Average;
		_type_Average = new Element(_qname_Average, Type.DOUBLE);
		ComplexType _complexType_askAFriendResponse;
		_complexType_askAFriendResponse = new ComplexType();
		_complexType_askAFriendResponse.elements = new Element[7];
		_complexType_askAFriendResponse.elements[0] = _type_WebAskAFriendID;
		_complexType_askAFriendResponse.elements[1] = _type_Question;
		_complexType_askAFriendResponse.elements[2] = _type_PhotoBase64Binary;
		_complexType_askAFriendResponse.elements[3] = _type_ResponseValues;
		_complexType_askAFriendResponse.elements[4] = _type_Average;
		_complexType_askAFriendResponse.elements[5] = _type_ResponseType;
		_complexType_askAFriendResponse.elements[6] = _type_CustomResponses;
		Element _type_GetAAFResponseResult;
		_type_GetAAFResponseResult = new Element(_qname_GetAAFResponseResult, _complexType_askAFriendResponse, 0, 1, false);
		ComplexType _complexType_getAAFResponseResponse;
		_complexType_getAAFResponseResponse = new ComplexType();
		_complexType_getAAFResponseResponse.elements = new Element[1];
		_complexType_getAAFResponseResponse.elements[0] = _type_GetAAFResponseResult;
		_type_GetAAFResponseResponse = new Element(_qname_GetAAFResponseResponse, _complexType_getAAFResponseResponse);
		Element _type_LastWebAskAFriendCommentID;
		_type_LastWebAskAFriendCommentID = new Element(_qname_LastWebAskAFriendCommentID, Type.STRING, 0, 1, false);
		ComplexType _complexType_getAAFComments;
		_complexType_getAAFComments = new ComplexType();
		_complexType_getAAFComments.elements = new Element[4];
		_complexType_getAAFComments.elements[0] = _type_WebMemberID;
		_complexType_getAAFComments.elements[1] = _type_WebPassword;
		_complexType_getAAFComments.elements[2] = _type_WebAskAFriendID;
		_complexType_getAAFComments.elements[3] = _type_LastWebAskAFriendCommentID;
		_type_GetAAFComments = new Element(_qname_GetAAFComments, _complexType_getAAFComments);
		Element _type_WebAskAFriendCommentID;
		_type_WebAskAFriendCommentID = new Element(_qname_WebAskAFriendCommentID, Type.STRING, 0, 1, false);
		Element _type_Text;
		_type_Text = new Element(_qname_Text, Type.STRING, 0, 1, false);
		ComplexType _complexType_askAFriendComment;
		_complexType_askAFriendComment = new ComplexType();
		_complexType_askAFriendComment.elements = new Element[5];
		_complexType_askAFriendComment.elements[0] = _type_NickName;
		_complexType_askAFriendComment.elements[1] = _type_WebMemberID;
		_complexType_askAFriendComment.elements[2] = _type_WebAskAFriendCommentID;
		_complexType_askAFriendComment.elements[3] = _type_Text;
		_complexType_askAFriendComment.elements[4] = _type_DateTimePosted;
		Element _type_AskAFriendComment;
		_type_AskAFriendComment = new Element(_qname_AskAFriendComment, _complexType_askAFriendComment, 0, -1, true);
		ComplexType _complexType_arrayOfAskAFriendComment;
		_complexType_arrayOfAskAFriendComment = new ComplexType();
		_complexType_arrayOfAskAFriendComment.elements = new Element[1];
		_complexType_arrayOfAskAFriendComment.elements[0] = _type_AskAFriendComment;
		Element _type_GetAAFCommentsResult;
		_type_GetAAFCommentsResult = new Element(_qname_GetAAFCommentsResult, _complexType_arrayOfAskAFriendComment, 0, 1, false);
		ComplexType _complexType_getAAFCommentsResponse;
		_complexType_getAAFCommentsResponse = new ComplexType();
		_complexType_getAAFCommentsResponse.elements = new Element[1];
		_complexType_getAAFCommentsResponse.elements[0] = _type_GetAAFCommentsResult;
		_type_GetAAFCommentsResponse = new Element(_qname_GetAAFCommentsResponse, _complexType_getAAFCommentsResponse);
	}

}
