// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.genetibase.askafriend.common.network.stub;


public class GetMyAAFQuestionsResponse {
    protected com.genetibase.askafriend.common.network.stub.ArrayOfAskAFriendQuestion getMyAAFQuestionsResult;
    
    public GetMyAAFQuestionsResponse() {
    }
    
    public GetMyAAFQuestionsResponse(com.genetibase.askafriend.common.network.stub.ArrayOfAskAFriendQuestion getMyAAFQuestionsResult) {
        this.getMyAAFQuestionsResult = getMyAAFQuestionsResult;
    }
    
    public com.genetibase.askafriend.common.network.stub.ArrayOfAskAFriendQuestion getGetMyAAFQuestionsResult() {
        return getMyAAFQuestionsResult;
    }
    
    public void setGetMyAAFQuestionsResult(com.genetibase.askafriend.common.network.stub.ArrayOfAskAFriendQuestion getMyAAFQuestionsResult) {
        this.getMyAAFQuestionsResult = getMyAAFQuestionsResult;
    }
}
