// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.genetibase.askafriend.common.network.stub;


public class GetMyAAFQuestions {
    protected java.lang.String webMemberID;
    protected java.lang.String webPassword;
    protected java.lang.String lastWebAskAFriendID;
    
    public GetMyAAFQuestions() {
    }
    
    public GetMyAAFQuestions(java.lang.String webMemberID, java.lang.String webPassword, java.lang.String lastWebAskAFriendID) {
        this.webMemberID = webMemberID;
        this.webPassword = webPassword;
        this.lastWebAskAFriendID = lastWebAskAFriendID;
    }
    
    public java.lang.String getWebMemberID() {
        return webMemberID;
    }
    
    public void setWebMemberID(java.lang.String webMemberID) {
        this.webMemberID = webMemberID;
    }
    
    public java.lang.String getWebPassword() {
        return webPassword;
    }
    
    public void setWebPassword(java.lang.String webPassword) {
        this.webPassword = webPassword;
    }
    
    public java.lang.String getLastWebAskAFriendID() {
        return lastWebAskAFriendID;
    }
    
    public void setLastWebAskAFriendID(java.lang.String lastWebAskAFriendID) {
        this.lastWebAskAFriendID = lastWebAskAFriendID;
    }
}
