//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Next2Friends.GeoMessage.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Next2Friends.GeoMessage.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad credentials. The member with the specified webMemberId and password does not exist..
        /// </summary>
        internal static string Argument_BadCredentials {
            get {
                return ResourceManager.GetString("Argument_BadCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoMessage.MeasureUnits value should be either 1 for Feets or 2 for Meters..
        /// </summary>
        internal static string Argument_BadMeasureUnits {
            get {
                return ResourceManager.GetString("Argument_BadMeasureUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identifier of the message creator does not match the identifier of the user that is intending to edit the message..
        /// </summary>
        internal static string Argument_BadMessageEditor {
            get {
                return ResourceManager.GetString("Argument_BadMessageEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identifier of the message creator does not match the identifier of the user that is intending to remove the message..
        /// </summary>
        internal static string Argument_BadMessageRemover {
            get {
                return ResourceManager.GetString("Argument_BadMessageRemover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoMessage.MessageType value should be either 1 for EntersTheArea, 2 for LeavesTheArea, or the combination of both..
        /// </summary>
        internal static string Argument_BadMessageType {
            get {
                return ResourceManager.GetString("Argument_BadMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the CurrentLocation property on message instance cannot be null..
        /// </summary>
        internal static string Argument_CurrentLocationIsNull {
            get {
                return ResourceManager.GetString("Argument_CurrentLocationIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to insert a new record into the {0} table..
        /// </summary>
        internal static string Argument_InsertIntoFailed {
            get {
                return ResourceManager.GetString("Argument_InsertIntoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user with the specified webMemberID = {0} does not exist..
        /// </summary>
        internal static string Argument_MemberNotExist {
            get {
                return ResourceManager.GetString("Argument_MemberNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message with the specified messageID does not exist..
        /// </summary>
        internal static string Argument_MessageNotExist {
            get {
                return ResourceManager.GetString("Argument_MessageNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified table does not contain any properties marked with [SqlParameter] attribute..
        /// </summary>
        internal static string Argument_NoSqlParameterProps {
            get {
                return ResourceManager.GetString("Argument_NoSqlParameterProps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property {0} is marked as being not nullable but its value is null..
        /// </summary>
        internal static string Argument_NotNullablePropIsNull {
            get {
                return ResourceManager.GetString("Argument_NotNullablePropIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified table should be marked with [SqlTable] attribute..
        /// </summary>
        internal static string Argument_NotSqlTable {
            get {
                return ResourceManager.GetString("Argument_NotSqlTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the CurrentLocation.QualifiedCoordinates property on message instance cannot be null..
        /// </summary>
        internal static string Argument_QualifiedCoordinatesIsNull {
            get {
                return ResourceManager.GetString("Argument_QualifiedCoordinatesIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the Receivers property on message instance cannot be null..
        /// </summary>
        internal static string Argument_ReceiversIsNull {
            get {
                return ResourceManager.GetString("Argument_ReceiversIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to insert a new record into the {0} table..
        /// </summary>
        internal static string InvalidOperation_InsertRecord {
            get {
                return ResourceManager.GetString("InvalidOperation_InsertRecord", resourceCulture);
            }
        }
    }
}
