/* soapH.h
   Generated by gSOAP 2.7.10 from askafriend.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_double
#define SOAP_TYPE_double (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_double(struct soap*, double *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_double(struct soap*, const double *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_double(struct soap*, const char*, int, const double *, const char*);
SOAP_FMAC3 double * SOAP_FMAC4 soap_get_double(struct soap*, double *, const char*, const char*);
SOAP_FMAC3 double * SOAP_FMAC4 soap_in_double(struct soap*, const char*, double *, const char*);

#ifndef SOAP_TYPE_bool
#define SOAP_TYPE_bool (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_bool(struct soap*, bool *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_bool(struct soap*, const bool *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_bool(struct soap*, const char*, int, const bool *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_bool2s(struct soap*, bool);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_get_bool(struct soap*, bool *, const char*, const char*);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_in_bool(struct soap*, const char*, bool *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2bool(struct soap*, const char*, bool *);

#ifndef SOAP_TYPE_StringArray
#define SOAP_TYPE_StringArray (33)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_StringArray(struct soap*, const char*, int, const StringArray *, const char*);
SOAP_FMAC3 StringArray * SOAP_FMAC4 soap_get_StringArray(struct soap*, StringArray *, const char*, const char*);
SOAP_FMAC3 StringArray * SOAP_FMAC4 soap_in_StringArray(struct soap*, const char*, StringArray *, const char*);
SOAP_FMAC5 StringArray * SOAP_FMAC6 soap_new_StringArray(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_StringArray(struct soap*, StringArray*);
SOAP_FMAC3 StringArray * SOAP_FMAC4 soap_instantiate_StringArray(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_StringArray(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetAAFCommentsResponse
#define SOAP_TYPE__ns1__GetAAFCommentsResponse (32)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetAAFCommentsResponse(struct soap*, const char*, int, const _ns1__GetAAFCommentsResponse *, const char*);
SOAP_FMAC3 _ns1__GetAAFCommentsResponse * SOAP_FMAC4 soap_get__ns1__GetAAFCommentsResponse(struct soap*, _ns1__GetAAFCommentsResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__GetAAFCommentsResponse * SOAP_FMAC4 soap_in__ns1__GetAAFCommentsResponse(struct soap*, const char*, _ns1__GetAAFCommentsResponse *, const char*);
SOAP_FMAC5 _ns1__GetAAFCommentsResponse * SOAP_FMAC6 soap_new__ns1__GetAAFCommentsResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__GetAAFCommentsResponse(struct soap*, _ns1__GetAAFCommentsResponse*);
SOAP_FMAC3 _ns1__GetAAFCommentsResponse * SOAP_FMAC4 soap_instantiate__ns1__GetAAFCommentsResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__GetAAFCommentsResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetAAFComments
#define SOAP_TYPE__ns1__GetAAFComments (31)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetAAFComments(struct soap*, const char*, int, const _ns1__GetAAFComments *, const char*);
SOAP_FMAC3 _ns1__GetAAFComments * SOAP_FMAC4 soap_get__ns1__GetAAFComments(struct soap*, _ns1__GetAAFComments *, const char*, const char*);
SOAP_FMAC3 _ns1__GetAAFComments * SOAP_FMAC4 soap_in__ns1__GetAAFComments(struct soap*, const char*, _ns1__GetAAFComments *, const char*);
SOAP_FMAC5 _ns1__GetAAFComments * SOAP_FMAC6 soap_new__ns1__GetAAFComments(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__GetAAFComments(struct soap*, _ns1__GetAAFComments*);
SOAP_FMAC3 _ns1__GetAAFComments * SOAP_FMAC4 soap_instantiate__ns1__GetAAFComments(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__GetAAFComments(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetAAFResponseResponse
#define SOAP_TYPE__ns1__GetAAFResponseResponse (30)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetAAFResponseResponse(struct soap*, const char*, int, const _ns1__GetAAFResponseResponse *, const char*);
SOAP_FMAC3 _ns1__GetAAFResponseResponse * SOAP_FMAC4 soap_get__ns1__GetAAFResponseResponse(struct soap*, _ns1__GetAAFResponseResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__GetAAFResponseResponse * SOAP_FMAC4 soap_in__ns1__GetAAFResponseResponse(struct soap*, const char*, _ns1__GetAAFResponseResponse *, const char*);
SOAP_FMAC5 _ns1__GetAAFResponseResponse * SOAP_FMAC6 soap_new__ns1__GetAAFResponseResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__GetAAFResponseResponse(struct soap*, _ns1__GetAAFResponseResponse*);
SOAP_FMAC3 _ns1__GetAAFResponseResponse * SOAP_FMAC4 soap_instantiate__ns1__GetAAFResponseResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__GetAAFResponseResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetAAFResponse
#define SOAP_TYPE__ns1__GetAAFResponse (29)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetAAFResponse(struct soap*, const char*, int, const _ns1__GetAAFResponse *, const char*);
SOAP_FMAC3 _ns1__GetAAFResponse * SOAP_FMAC4 soap_get__ns1__GetAAFResponse(struct soap*, _ns1__GetAAFResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__GetAAFResponse * SOAP_FMAC4 soap_in__ns1__GetAAFResponse(struct soap*, const char*, _ns1__GetAAFResponse *, const char*);
SOAP_FMAC5 _ns1__GetAAFResponse * SOAP_FMAC6 soap_new__ns1__GetAAFResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__GetAAFResponse(struct soap*, _ns1__GetAAFResponse*);
SOAP_FMAC3 _ns1__GetAAFResponse * SOAP_FMAC4 soap_instantiate__ns1__GetAAFResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__GetAAFResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetNewAAFQuestionCommentIDsResponse
#define SOAP_TYPE__ns1__GetNewAAFQuestionCommentIDsResponse (28)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetNewAAFQuestionCommentIDsResponse(struct soap*, const char*, int, const _ns1__GetNewAAFQuestionCommentIDsResponse *, const char*);
SOAP_FMAC3 _ns1__GetNewAAFQuestionCommentIDsResponse * SOAP_FMAC4 soap_get__ns1__GetNewAAFQuestionCommentIDsResponse(struct soap*, _ns1__GetNewAAFQuestionCommentIDsResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__GetNewAAFQuestionCommentIDsResponse * SOAP_FMAC4 soap_in__ns1__GetNewAAFQuestionCommentIDsResponse(struct soap*, const char*, _ns1__GetNewAAFQuestionCommentIDsResponse *, const char*);
SOAP_FMAC5 _ns1__GetNewAAFQuestionCommentIDsResponse * SOAP_FMAC6 soap_new__ns1__GetNewAAFQuestionCommentIDsResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__GetNewAAFQuestionCommentIDsResponse(struct soap*, _ns1__GetNewAAFQuestionCommentIDsResponse*);
SOAP_FMAC3 _ns1__GetNewAAFQuestionCommentIDsResponse * SOAP_FMAC4 soap_instantiate__ns1__GetNewAAFQuestionCommentIDsResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__GetNewAAFQuestionCommentIDsResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetNewAAFQuestionCommentIDs
#define SOAP_TYPE__ns1__GetNewAAFQuestionCommentIDs (27)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetNewAAFQuestionCommentIDs(struct soap*, const char*, int, const _ns1__GetNewAAFQuestionCommentIDs *, const char*);
SOAP_FMAC3 _ns1__GetNewAAFQuestionCommentIDs * SOAP_FMAC4 soap_get__ns1__GetNewAAFQuestionCommentIDs(struct soap*, _ns1__GetNewAAFQuestionCommentIDs *, const char*, const char*);
SOAP_FMAC3 _ns1__GetNewAAFQuestionCommentIDs * SOAP_FMAC4 soap_in__ns1__GetNewAAFQuestionCommentIDs(struct soap*, const char*, _ns1__GetNewAAFQuestionCommentIDs *, const char*);
SOAP_FMAC5 _ns1__GetNewAAFQuestionCommentIDs * SOAP_FMAC6 soap_new__ns1__GetNewAAFQuestionCommentIDs(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__GetNewAAFQuestionCommentIDs(struct soap*, _ns1__GetNewAAFQuestionCommentIDs*);
SOAP_FMAC3 _ns1__GetNewAAFQuestionCommentIDs * SOAP_FMAC4 soap_instantiate__ns1__GetNewAAFQuestionCommentIDs(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__GetNewAAFQuestionCommentIDs(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetMyAAFQuestionsResponse
#define SOAP_TYPE__ns1__GetMyAAFQuestionsResponse (26)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetMyAAFQuestionsResponse(struct soap*, const char*, int, const _ns1__GetMyAAFQuestionsResponse *, const char*);
SOAP_FMAC3 _ns1__GetMyAAFQuestionsResponse * SOAP_FMAC4 soap_get__ns1__GetMyAAFQuestionsResponse(struct soap*, _ns1__GetMyAAFQuestionsResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__GetMyAAFQuestionsResponse * SOAP_FMAC4 soap_in__ns1__GetMyAAFQuestionsResponse(struct soap*, const char*, _ns1__GetMyAAFQuestionsResponse *, const char*);
SOAP_FMAC5 _ns1__GetMyAAFQuestionsResponse * SOAP_FMAC6 soap_new__ns1__GetMyAAFQuestionsResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__GetMyAAFQuestionsResponse(struct soap*, _ns1__GetMyAAFQuestionsResponse*);
SOAP_FMAC3 _ns1__GetMyAAFQuestionsResponse * SOAP_FMAC4 soap_instantiate__ns1__GetMyAAFQuestionsResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__GetMyAAFQuestionsResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetMyAAFQuestions
#define SOAP_TYPE__ns1__GetMyAAFQuestions (25)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetMyAAFQuestions(struct soap*, const char*, int, const _ns1__GetMyAAFQuestions *, const char*);
SOAP_FMAC3 _ns1__GetMyAAFQuestions * SOAP_FMAC4 soap_get__ns1__GetMyAAFQuestions(struct soap*, _ns1__GetMyAAFQuestions *, const char*, const char*);
SOAP_FMAC3 _ns1__GetMyAAFQuestions * SOAP_FMAC4 soap_in__ns1__GetMyAAFQuestions(struct soap*, const char*, _ns1__GetMyAAFQuestions *, const char*);
SOAP_FMAC5 _ns1__GetMyAAFQuestions * SOAP_FMAC6 soap_new__ns1__GetMyAAFQuestions(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__GetMyAAFQuestions(struct soap*, _ns1__GetMyAAFQuestions*);
SOAP_FMAC3 _ns1__GetMyAAFQuestions * SOAP_FMAC4 soap_instantiate__ns1__GetMyAAFQuestions(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__GetMyAAFQuestions(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetPrivateAAFQuestionResponse
#define SOAP_TYPE__ns1__GetPrivateAAFQuestionResponse (24)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetPrivateAAFQuestionResponse(struct soap*, const char*, int, const _ns1__GetPrivateAAFQuestionResponse *, const char*);
SOAP_FMAC3 _ns1__GetPrivateAAFQuestionResponse * SOAP_FMAC4 soap_get__ns1__GetPrivateAAFQuestionResponse(struct soap*, _ns1__GetPrivateAAFQuestionResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__GetPrivateAAFQuestionResponse * SOAP_FMAC4 soap_in__ns1__GetPrivateAAFQuestionResponse(struct soap*, const char*, _ns1__GetPrivateAAFQuestionResponse *, const char*);
SOAP_FMAC5 _ns1__GetPrivateAAFQuestionResponse * SOAP_FMAC6 soap_new__ns1__GetPrivateAAFQuestionResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__GetPrivateAAFQuestionResponse(struct soap*, _ns1__GetPrivateAAFQuestionResponse*);
SOAP_FMAC3 _ns1__GetPrivateAAFQuestionResponse * SOAP_FMAC4 soap_instantiate__ns1__GetPrivateAAFQuestionResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__GetPrivateAAFQuestionResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetPrivateAAFQuestion
#define SOAP_TYPE__ns1__GetPrivateAAFQuestion (23)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetPrivateAAFQuestion(struct soap*, const char*, int, const _ns1__GetPrivateAAFQuestion *, const char*);
SOAP_FMAC3 _ns1__GetPrivateAAFQuestion * SOAP_FMAC4 soap_get__ns1__GetPrivateAAFQuestion(struct soap*, _ns1__GetPrivateAAFQuestion *, const char*, const char*);
SOAP_FMAC3 _ns1__GetPrivateAAFQuestion * SOAP_FMAC4 soap_in__ns1__GetPrivateAAFQuestion(struct soap*, const char*, _ns1__GetPrivateAAFQuestion *, const char*);
SOAP_FMAC5 _ns1__GetPrivateAAFQuestion * SOAP_FMAC6 soap_new__ns1__GetPrivateAAFQuestion(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__GetPrivateAAFQuestion(struct soap*, _ns1__GetPrivateAAFQuestion*);
SOAP_FMAC3 _ns1__GetPrivateAAFQuestion * SOAP_FMAC4 soap_instantiate__ns1__GetPrivateAAFQuestion(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__GetPrivateAAFQuestion(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__CompleteQuestionResponse
#define SOAP_TYPE__ns1__CompleteQuestionResponse (22)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__CompleteQuestionResponse(struct soap*, const char*, int, const _ns1__CompleteQuestionResponse *, const char*);
SOAP_FMAC3 _ns1__CompleteQuestionResponse * SOAP_FMAC4 soap_get__ns1__CompleteQuestionResponse(struct soap*, _ns1__CompleteQuestionResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__CompleteQuestionResponse * SOAP_FMAC4 soap_in__ns1__CompleteQuestionResponse(struct soap*, const char*, _ns1__CompleteQuestionResponse *, const char*);
SOAP_FMAC5 _ns1__CompleteQuestionResponse * SOAP_FMAC6 soap_new__ns1__CompleteQuestionResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__CompleteQuestionResponse(struct soap*, _ns1__CompleteQuestionResponse*);
SOAP_FMAC3 _ns1__CompleteQuestionResponse * SOAP_FMAC4 soap_instantiate__ns1__CompleteQuestionResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__CompleteQuestionResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__CompleteQuestion
#define SOAP_TYPE__ns1__CompleteQuestion (21)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__CompleteQuestion(struct soap*, const char*, int, const _ns1__CompleteQuestion *, const char*);
SOAP_FMAC3 _ns1__CompleteQuestion * SOAP_FMAC4 soap_get__ns1__CompleteQuestion(struct soap*, _ns1__CompleteQuestion *, const char*, const char*);
SOAP_FMAC3 _ns1__CompleteQuestion * SOAP_FMAC4 soap_in__ns1__CompleteQuestion(struct soap*, const char*, _ns1__CompleteQuestion *, const char*);
SOAP_FMAC5 _ns1__CompleteQuestion * SOAP_FMAC6 soap_new__ns1__CompleteQuestion(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__CompleteQuestion(struct soap*, _ns1__CompleteQuestion*);
SOAP_FMAC3 _ns1__CompleteQuestion * SOAP_FMAC4 soap_instantiate__ns1__CompleteQuestion(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__CompleteQuestion(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__AttachPhotoResponse
#define SOAP_TYPE__ns1__AttachPhotoResponse (20)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__AttachPhotoResponse(struct soap*, const char*, int, const _ns1__AttachPhotoResponse *, const char*);
SOAP_FMAC3 _ns1__AttachPhotoResponse * SOAP_FMAC4 soap_get__ns1__AttachPhotoResponse(struct soap*, _ns1__AttachPhotoResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__AttachPhotoResponse * SOAP_FMAC4 soap_in__ns1__AttachPhotoResponse(struct soap*, const char*, _ns1__AttachPhotoResponse *, const char*);
SOAP_FMAC5 _ns1__AttachPhotoResponse * SOAP_FMAC6 soap_new__ns1__AttachPhotoResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__AttachPhotoResponse(struct soap*, _ns1__AttachPhotoResponse*);
SOAP_FMAC3 _ns1__AttachPhotoResponse * SOAP_FMAC4 soap_instantiate__ns1__AttachPhotoResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__AttachPhotoResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__AttachPhoto
#define SOAP_TYPE__ns1__AttachPhoto (19)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__AttachPhoto(struct soap*, const char*, int, const _ns1__AttachPhoto *, const char*);
SOAP_FMAC3 _ns1__AttachPhoto * SOAP_FMAC4 soap_get__ns1__AttachPhoto(struct soap*, _ns1__AttachPhoto *, const char*, const char*);
SOAP_FMAC3 _ns1__AttachPhoto * SOAP_FMAC4 soap_in__ns1__AttachPhoto(struct soap*, const char*, _ns1__AttachPhoto *, const char*);
SOAP_FMAC5 _ns1__AttachPhoto * SOAP_FMAC6 soap_new__ns1__AttachPhoto(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__AttachPhoto(struct soap*, _ns1__AttachPhoto*);
SOAP_FMAC3 _ns1__AttachPhoto * SOAP_FMAC4 soap_instantiate__ns1__AttachPhoto(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__AttachPhoto(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__SubmitQuestionResponse
#define SOAP_TYPE__ns1__SubmitQuestionResponse (18)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__SubmitQuestionResponse(struct soap*, const char*, int, const _ns1__SubmitQuestionResponse *, const char*);
SOAP_FMAC3 _ns1__SubmitQuestionResponse * SOAP_FMAC4 soap_get__ns1__SubmitQuestionResponse(struct soap*, _ns1__SubmitQuestionResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__SubmitQuestionResponse * SOAP_FMAC4 soap_in__ns1__SubmitQuestionResponse(struct soap*, const char*, _ns1__SubmitQuestionResponse *, const char*);
SOAP_FMAC5 _ns1__SubmitQuestionResponse * SOAP_FMAC6 soap_new__ns1__SubmitQuestionResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__SubmitQuestionResponse(struct soap*, _ns1__SubmitQuestionResponse*);
SOAP_FMAC3 _ns1__SubmitQuestionResponse * SOAP_FMAC4 soap_instantiate__ns1__SubmitQuestionResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__SubmitQuestionResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__SubmitQuestion
#define SOAP_TYPE__ns1__SubmitQuestion (17)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__SubmitQuestion(struct soap*, const char*, int, const _ns1__SubmitQuestion *, const char*);
SOAP_FMAC3 _ns1__SubmitQuestion * SOAP_FMAC4 soap_get__ns1__SubmitQuestion(struct soap*, _ns1__SubmitQuestion *, const char*, const char*);
SOAP_FMAC3 _ns1__SubmitQuestion * SOAP_FMAC4 soap_in__ns1__SubmitQuestion(struct soap*, const char*, _ns1__SubmitQuestion *, const char*);
SOAP_FMAC5 _ns1__SubmitQuestion * SOAP_FMAC6 soap_new__ns1__SubmitQuestion(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__SubmitQuestion(struct soap*, _ns1__SubmitQuestion*);
SOAP_FMAC3 _ns1__SubmitQuestion * SOAP_FMAC4 soap_instantiate__ns1__SubmitQuestion(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__SubmitQuestion(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__AskAFriendComment
#define SOAP_TYPE_ns1__AskAFriendComment (16)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__AskAFriendComment(struct soap*, const char*, int, const ns1__AskAFriendComment *, const char*);
SOAP_FMAC3 ns1__AskAFriendComment * SOAP_FMAC4 soap_get_ns1__AskAFriendComment(struct soap*, ns1__AskAFriendComment *, const char*, const char*);
SOAP_FMAC3 ns1__AskAFriendComment * SOAP_FMAC4 soap_in_ns1__AskAFriendComment(struct soap*, const char*, ns1__AskAFriendComment *, const char*);
SOAP_FMAC5 ns1__AskAFriendComment * SOAP_FMAC6 soap_new_ns1__AskAFriendComment(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__AskAFriendComment(struct soap*, ns1__AskAFriendComment*);
SOAP_FMAC3 ns1__AskAFriendComment * SOAP_FMAC4 soap_instantiate_ns1__AskAFriendComment(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__AskAFriendComment(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__ArrayOfAskAFriendComment
#define SOAP_TYPE_ns1__ArrayOfAskAFriendComment (15)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ArrayOfAskAFriendComment(struct soap*, const char*, int, const ns1__ArrayOfAskAFriendComment *, const char*);
SOAP_FMAC3 ns1__ArrayOfAskAFriendComment * SOAP_FMAC4 soap_get_ns1__ArrayOfAskAFriendComment(struct soap*, ns1__ArrayOfAskAFriendComment *, const char*, const char*);
SOAP_FMAC3 ns1__ArrayOfAskAFriendComment * SOAP_FMAC4 soap_in_ns1__ArrayOfAskAFriendComment(struct soap*, const char*, ns1__ArrayOfAskAFriendComment *, const char*);
SOAP_FMAC5 ns1__ArrayOfAskAFriendComment * SOAP_FMAC6 soap_new_ns1__ArrayOfAskAFriendComment(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__ArrayOfAskAFriendComment(struct soap*, ns1__ArrayOfAskAFriendComment*);
SOAP_FMAC3 ns1__ArrayOfAskAFriendComment * SOAP_FMAC4 soap_instantiate_ns1__ArrayOfAskAFriendComment(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__ArrayOfAskAFriendComment(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__ArrayOfInt
#define SOAP_TYPE_ns1__ArrayOfInt (14)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ArrayOfInt(struct soap*, const char*, int, const ns1__ArrayOfInt *, const char*);
SOAP_FMAC3 ns1__ArrayOfInt * SOAP_FMAC4 soap_get_ns1__ArrayOfInt(struct soap*, ns1__ArrayOfInt *, const char*, const char*);
SOAP_FMAC3 ns1__ArrayOfInt * SOAP_FMAC4 soap_in_ns1__ArrayOfInt(struct soap*, const char*, ns1__ArrayOfInt *, const char*);
SOAP_FMAC5 ns1__ArrayOfInt * SOAP_FMAC6 soap_new_ns1__ArrayOfInt(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__ArrayOfInt(struct soap*, ns1__ArrayOfInt*);
SOAP_FMAC3 ns1__ArrayOfInt * SOAP_FMAC4 soap_instantiate_ns1__ArrayOfInt(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__ArrayOfInt(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__AskAFriendResponse
#define SOAP_TYPE_ns1__AskAFriendResponse (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__AskAFriendResponse(struct soap*, const char*, int, const ns1__AskAFriendResponse *, const char*);
SOAP_FMAC3 ns1__AskAFriendResponse * SOAP_FMAC4 soap_get_ns1__AskAFriendResponse(struct soap*, ns1__AskAFriendResponse *, const char*, const char*);
SOAP_FMAC3 ns1__AskAFriendResponse * SOAP_FMAC4 soap_in_ns1__AskAFriendResponse(struct soap*, const char*, ns1__AskAFriendResponse *, const char*);
SOAP_FMAC5 ns1__AskAFriendResponse * SOAP_FMAC6 soap_new_ns1__AskAFriendResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__AskAFriendResponse(struct soap*, ns1__AskAFriendResponse*);
SOAP_FMAC3 ns1__AskAFriendResponse * SOAP_FMAC4 soap_instantiate_ns1__AskAFriendResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__AskAFriendResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__AskAFriendQuestion
#define SOAP_TYPE_ns1__AskAFriendQuestion (12)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__AskAFriendQuestion(struct soap*, const char*, int, const ns1__AskAFriendQuestion *, const char*);
SOAP_FMAC3 ns1__AskAFriendQuestion * SOAP_FMAC4 soap_get_ns1__AskAFriendQuestion(struct soap*, ns1__AskAFriendQuestion *, const char*, const char*);
SOAP_FMAC3 ns1__AskAFriendQuestion * SOAP_FMAC4 soap_in_ns1__AskAFriendQuestion(struct soap*, const char*, ns1__AskAFriendQuestion *, const char*);
SOAP_FMAC5 ns1__AskAFriendQuestion * SOAP_FMAC6 soap_new_ns1__AskAFriendQuestion(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__AskAFriendQuestion(struct soap*, ns1__AskAFriendQuestion*);
SOAP_FMAC3 ns1__AskAFriendQuestion * SOAP_FMAC4 soap_instantiate_ns1__AskAFriendQuestion(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__AskAFriendQuestion(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__ArrayOfAskAFriendQuestion
#define SOAP_TYPE_ns1__ArrayOfAskAFriendQuestion (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ArrayOfAskAFriendQuestion(struct soap*, const char*, int, const ns1__ArrayOfAskAFriendQuestion *, const char*);
SOAP_FMAC3 ns1__ArrayOfAskAFriendQuestion * SOAP_FMAC4 soap_get_ns1__ArrayOfAskAFriendQuestion(struct soap*, ns1__ArrayOfAskAFriendQuestion *, const char*, const char*);
SOAP_FMAC3 ns1__ArrayOfAskAFriendQuestion * SOAP_FMAC4 soap_in_ns1__ArrayOfAskAFriendQuestion(struct soap*, const char*, ns1__ArrayOfAskAFriendQuestion *, const char*);
SOAP_FMAC5 ns1__ArrayOfAskAFriendQuestion * SOAP_FMAC6 soap_new_ns1__ArrayOfAskAFriendQuestion(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__ArrayOfAskAFriendQuestion(struct soap*, ns1__ArrayOfAskAFriendQuestion*);
SOAP_FMAC3 ns1__ArrayOfAskAFriendQuestion * SOAP_FMAC4 soap_instantiate_ns1__ArrayOfAskAFriendQuestion(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__ArrayOfAskAFriendQuestion(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__PrivateAAFQuestion
#define SOAP_TYPE_ns1__PrivateAAFQuestion (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__PrivateAAFQuestion(struct soap*, const char*, int, const ns1__PrivateAAFQuestion *, const char*);
SOAP_FMAC3 ns1__PrivateAAFQuestion * SOAP_FMAC4 soap_get_ns1__PrivateAAFQuestion(struct soap*, ns1__PrivateAAFQuestion *, const char*, const char*);
SOAP_FMAC3 ns1__PrivateAAFQuestion * SOAP_FMAC4 soap_in_ns1__PrivateAAFQuestion(struct soap*, const char*, ns1__PrivateAAFQuestion *, const char*);
SOAP_FMAC5 ns1__PrivateAAFQuestion * SOAP_FMAC6 soap_new_ns1__PrivateAAFQuestion(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__PrivateAAFQuestion(struct soap*, ns1__PrivateAAFQuestion*);
SOAP_FMAC3 ns1__PrivateAAFQuestion * SOAP_FMAC4 soap_instantiate_ns1__PrivateAAFQuestion(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__PrivateAAFQuestion(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__ArrayOfPrivateAAFQuestion
#define SOAP_TYPE_ns1__ArrayOfPrivateAAFQuestion (9)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ArrayOfPrivateAAFQuestion(struct soap*, const char*, int, const ns1__ArrayOfPrivateAAFQuestion *, const char*);
SOAP_FMAC3 ns1__ArrayOfPrivateAAFQuestion * SOAP_FMAC4 soap_get_ns1__ArrayOfPrivateAAFQuestion(struct soap*, ns1__ArrayOfPrivateAAFQuestion *, const char*, const char*);
SOAP_FMAC3 ns1__ArrayOfPrivateAAFQuestion * SOAP_FMAC4 soap_in_ns1__ArrayOfPrivateAAFQuestion(struct soap*, const char*, ns1__ArrayOfPrivateAAFQuestion *, const char*);
SOAP_FMAC5 ns1__ArrayOfPrivateAAFQuestion * SOAP_FMAC6 soap_new_ns1__ArrayOfPrivateAAFQuestion(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__ArrayOfPrivateAAFQuestion(struct soap*, ns1__ArrayOfPrivateAAFQuestion*);
SOAP_FMAC3 ns1__ArrayOfPrivateAAFQuestion * SOAP_FMAC4 soap_instantiate_ns1__ArrayOfPrivateAAFQuestion(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__ArrayOfPrivateAAFQuestion(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__AskAFriendConfirm
#define SOAP_TYPE_ns1__AskAFriendConfirm (8)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__AskAFriendConfirm(struct soap*, const char*, int, const ns1__AskAFriendConfirm *, const char*);
SOAP_FMAC3 ns1__AskAFriendConfirm * SOAP_FMAC4 soap_get_ns1__AskAFriendConfirm(struct soap*, ns1__AskAFriendConfirm *, const char*, const char*);
SOAP_FMAC3 ns1__AskAFriendConfirm * SOAP_FMAC4 soap_in_ns1__AskAFriendConfirm(struct soap*, const char*, ns1__AskAFriendConfirm *, const char*);
SOAP_FMAC5 ns1__AskAFriendConfirm * SOAP_FMAC6 soap_new_ns1__AskAFriendConfirm(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__AskAFriendConfirm(struct soap*, ns1__AskAFriendConfirm*);
SOAP_FMAC3 ns1__AskAFriendConfirm * SOAP_FMAC4 soap_instantiate_ns1__AskAFriendConfirm(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__AskAFriendConfirm(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__ArrayOfString
#define SOAP_TYPE_ns1__ArrayOfString (7)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ArrayOfString(struct soap*, const char*, int, const ns1__ArrayOfString *, const char*);
SOAP_FMAC3 ns1__ArrayOfString * SOAP_FMAC4 soap_get_ns1__ArrayOfString(struct soap*, ns1__ArrayOfString *, const char*, const char*);
SOAP_FMAC3 ns1__ArrayOfString * SOAP_FMAC4 soap_in_ns1__ArrayOfString(struct soap*, const char*, ns1__ArrayOfString *, const char*);
SOAP_FMAC5 ns1__ArrayOfString * SOAP_FMAC6 soap_new_ns1__ArrayOfString(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__ArrayOfString(struct soap*, ns1__ArrayOfString*);
SOAP_FMAC3 ns1__ArrayOfString * SOAP_FMAC4 soap_instantiate_ns1__ArrayOfString(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__ArrayOfString(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (107)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Fault * SOAP_FMAC6 soap_new_SOAP_ENV__Fault(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (106)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Reason * SOAP_FMAC6 soap_new_SOAP_ENV__Reason(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (103)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Detail * SOAP_FMAC6 soap_new_SOAP_ENV__Detail(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (101)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Code * SOAP_FMAC6 soap_new_SOAP_ENV__Code(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (100)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Header * SOAP_FMAC6 soap_new_SOAP_ENV__Header(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE___ns4__GetAAFComments
#define SOAP_TYPE___ns4__GetAAFComments (99)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns4__GetAAFComments(struct soap*, struct __ns4__GetAAFComments *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns4__GetAAFComments(struct soap*, const struct __ns4__GetAAFComments *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns4__GetAAFComments(struct soap*, const struct __ns4__GetAAFComments *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns4__GetAAFComments(struct soap*, const char*, int, const struct __ns4__GetAAFComments *, const char*);
SOAP_FMAC3 struct __ns4__GetAAFComments * SOAP_FMAC4 soap_get___ns4__GetAAFComments(struct soap*, struct __ns4__GetAAFComments *, const char*, const char*);
SOAP_FMAC3 struct __ns4__GetAAFComments * SOAP_FMAC4 soap_in___ns4__GetAAFComments(struct soap*, const char*, struct __ns4__GetAAFComments *, const char*);
SOAP_FMAC5 struct __ns4__GetAAFComments * SOAP_FMAC6 soap_new___ns4__GetAAFComments(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns4__GetAAFComments(struct soap*, struct __ns4__GetAAFComments*);
SOAP_FMAC3 struct __ns4__GetAAFComments * SOAP_FMAC4 soap_instantiate___ns4__GetAAFComments(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns4__GetAAFComments(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns4__GetAAFResponse
#define SOAP_TYPE___ns4__GetAAFResponse (97)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns4__GetAAFResponse(struct soap*, struct __ns4__GetAAFResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns4__GetAAFResponse(struct soap*, const struct __ns4__GetAAFResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns4__GetAAFResponse(struct soap*, const struct __ns4__GetAAFResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns4__GetAAFResponse(struct soap*, const char*, int, const struct __ns4__GetAAFResponse *, const char*);
SOAP_FMAC3 struct __ns4__GetAAFResponse * SOAP_FMAC4 soap_get___ns4__GetAAFResponse(struct soap*, struct __ns4__GetAAFResponse *, const char*, const char*);
SOAP_FMAC3 struct __ns4__GetAAFResponse * SOAP_FMAC4 soap_in___ns4__GetAAFResponse(struct soap*, const char*, struct __ns4__GetAAFResponse *, const char*);
SOAP_FMAC5 struct __ns4__GetAAFResponse * SOAP_FMAC6 soap_new___ns4__GetAAFResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns4__GetAAFResponse(struct soap*, struct __ns4__GetAAFResponse*);
SOAP_FMAC3 struct __ns4__GetAAFResponse * SOAP_FMAC4 soap_instantiate___ns4__GetAAFResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns4__GetAAFResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns4__GetNewAAFQuestionCommentIDs
#define SOAP_TYPE___ns4__GetNewAAFQuestionCommentIDs (95)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns4__GetNewAAFQuestionCommentIDs(struct soap*, struct __ns4__GetNewAAFQuestionCommentIDs *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns4__GetNewAAFQuestionCommentIDs(struct soap*, const struct __ns4__GetNewAAFQuestionCommentIDs *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns4__GetNewAAFQuestionCommentIDs(struct soap*, const struct __ns4__GetNewAAFQuestionCommentIDs *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns4__GetNewAAFQuestionCommentIDs(struct soap*, const char*, int, const struct __ns4__GetNewAAFQuestionCommentIDs *, const char*);
SOAP_FMAC3 struct __ns4__GetNewAAFQuestionCommentIDs * SOAP_FMAC4 soap_get___ns4__GetNewAAFQuestionCommentIDs(struct soap*, struct __ns4__GetNewAAFQuestionCommentIDs *, const char*, const char*);
SOAP_FMAC3 struct __ns4__GetNewAAFQuestionCommentIDs * SOAP_FMAC4 soap_in___ns4__GetNewAAFQuestionCommentIDs(struct soap*, const char*, struct __ns4__GetNewAAFQuestionCommentIDs *, const char*);
SOAP_FMAC5 struct __ns4__GetNewAAFQuestionCommentIDs * SOAP_FMAC6 soap_new___ns4__GetNewAAFQuestionCommentIDs(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns4__GetNewAAFQuestionCommentIDs(struct soap*, struct __ns4__GetNewAAFQuestionCommentIDs*);
SOAP_FMAC3 struct __ns4__GetNewAAFQuestionCommentIDs * SOAP_FMAC4 soap_instantiate___ns4__GetNewAAFQuestionCommentIDs(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns4__GetNewAAFQuestionCommentIDs(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns4__GetMyAAFQuestions
#define SOAP_TYPE___ns4__GetMyAAFQuestions (93)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns4__GetMyAAFQuestions(struct soap*, struct __ns4__GetMyAAFQuestions *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns4__GetMyAAFQuestions(struct soap*, const struct __ns4__GetMyAAFQuestions *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns4__GetMyAAFQuestions(struct soap*, const struct __ns4__GetMyAAFQuestions *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns4__GetMyAAFQuestions(struct soap*, const char*, int, const struct __ns4__GetMyAAFQuestions *, const char*);
SOAP_FMAC3 struct __ns4__GetMyAAFQuestions * SOAP_FMAC4 soap_get___ns4__GetMyAAFQuestions(struct soap*, struct __ns4__GetMyAAFQuestions *, const char*, const char*);
SOAP_FMAC3 struct __ns4__GetMyAAFQuestions * SOAP_FMAC4 soap_in___ns4__GetMyAAFQuestions(struct soap*, const char*, struct __ns4__GetMyAAFQuestions *, const char*);
SOAP_FMAC5 struct __ns4__GetMyAAFQuestions * SOAP_FMAC6 soap_new___ns4__GetMyAAFQuestions(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns4__GetMyAAFQuestions(struct soap*, struct __ns4__GetMyAAFQuestions*);
SOAP_FMAC3 struct __ns4__GetMyAAFQuestions * SOAP_FMAC4 soap_instantiate___ns4__GetMyAAFQuestions(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns4__GetMyAAFQuestions(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns4__GetPrivateAAFQuestion
#define SOAP_TYPE___ns4__GetPrivateAAFQuestion (91)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns4__GetPrivateAAFQuestion(struct soap*, struct __ns4__GetPrivateAAFQuestion *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns4__GetPrivateAAFQuestion(struct soap*, const struct __ns4__GetPrivateAAFQuestion *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns4__GetPrivateAAFQuestion(struct soap*, const struct __ns4__GetPrivateAAFQuestion *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns4__GetPrivateAAFQuestion(struct soap*, const char*, int, const struct __ns4__GetPrivateAAFQuestion *, const char*);
SOAP_FMAC3 struct __ns4__GetPrivateAAFQuestion * SOAP_FMAC4 soap_get___ns4__GetPrivateAAFQuestion(struct soap*, struct __ns4__GetPrivateAAFQuestion *, const char*, const char*);
SOAP_FMAC3 struct __ns4__GetPrivateAAFQuestion * SOAP_FMAC4 soap_in___ns4__GetPrivateAAFQuestion(struct soap*, const char*, struct __ns4__GetPrivateAAFQuestion *, const char*);
SOAP_FMAC5 struct __ns4__GetPrivateAAFQuestion * SOAP_FMAC6 soap_new___ns4__GetPrivateAAFQuestion(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns4__GetPrivateAAFQuestion(struct soap*, struct __ns4__GetPrivateAAFQuestion*);
SOAP_FMAC3 struct __ns4__GetPrivateAAFQuestion * SOAP_FMAC4 soap_instantiate___ns4__GetPrivateAAFQuestion(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns4__GetPrivateAAFQuestion(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns4__CompleteQuestion
#define SOAP_TYPE___ns4__CompleteQuestion (89)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns4__CompleteQuestion(struct soap*, struct __ns4__CompleteQuestion *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns4__CompleteQuestion(struct soap*, const struct __ns4__CompleteQuestion *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns4__CompleteQuestion(struct soap*, const struct __ns4__CompleteQuestion *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns4__CompleteQuestion(struct soap*, const char*, int, const struct __ns4__CompleteQuestion *, const char*);
SOAP_FMAC3 struct __ns4__CompleteQuestion * SOAP_FMAC4 soap_get___ns4__CompleteQuestion(struct soap*, struct __ns4__CompleteQuestion *, const char*, const char*);
SOAP_FMAC3 struct __ns4__CompleteQuestion * SOAP_FMAC4 soap_in___ns4__CompleteQuestion(struct soap*, const char*, struct __ns4__CompleteQuestion *, const char*);
SOAP_FMAC5 struct __ns4__CompleteQuestion * SOAP_FMAC6 soap_new___ns4__CompleteQuestion(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns4__CompleteQuestion(struct soap*, struct __ns4__CompleteQuestion*);
SOAP_FMAC3 struct __ns4__CompleteQuestion * SOAP_FMAC4 soap_instantiate___ns4__CompleteQuestion(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns4__CompleteQuestion(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns4__AttachPhoto
#define SOAP_TYPE___ns4__AttachPhoto (87)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns4__AttachPhoto(struct soap*, struct __ns4__AttachPhoto *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns4__AttachPhoto(struct soap*, const struct __ns4__AttachPhoto *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns4__AttachPhoto(struct soap*, const struct __ns4__AttachPhoto *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns4__AttachPhoto(struct soap*, const char*, int, const struct __ns4__AttachPhoto *, const char*);
SOAP_FMAC3 struct __ns4__AttachPhoto * SOAP_FMAC4 soap_get___ns4__AttachPhoto(struct soap*, struct __ns4__AttachPhoto *, const char*, const char*);
SOAP_FMAC3 struct __ns4__AttachPhoto * SOAP_FMAC4 soap_in___ns4__AttachPhoto(struct soap*, const char*, struct __ns4__AttachPhoto *, const char*);
SOAP_FMAC5 struct __ns4__AttachPhoto * SOAP_FMAC6 soap_new___ns4__AttachPhoto(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns4__AttachPhoto(struct soap*, struct __ns4__AttachPhoto*);
SOAP_FMAC3 struct __ns4__AttachPhoto * SOAP_FMAC4 soap_instantiate___ns4__AttachPhoto(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns4__AttachPhoto(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns4__SubmitQuestion
#define SOAP_TYPE___ns4__SubmitQuestion (85)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns4__SubmitQuestion(struct soap*, struct __ns4__SubmitQuestion *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns4__SubmitQuestion(struct soap*, const struct __ns4__SubmitQuestion *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns4__SubmitQuestion(struct soap*, const struct __ns4__SubmitQuestion *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns4__SubmitQuestion(struct soap*, const char*, int, const struct __ns4__SubmitQuestion *, const char*);
SOAP_FMAC3 struct __ns4__SubmitQuestion * SOAP_FMAC4 soap_get___ns4__SubmitQuestion(struct soap*, struct __ns4__SubmitQuestion *, const char*, const char*);
SOAP_FMAC3 struct __ns4__SubmitQuestion * SOAP_FMAC4 soap_in___ns4__SubmitQuestion(struct soap*, const char*, struct __ns4__SubmitQuestion *, const char*);
SOAP_FMAC5 struct __ns4__SubmitQuestion * SOAP_FMAC6 soap_new___ns4__SubmitQuestion(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns4__SubmitQuestion(struct soap*, struct __ns4__SubmitQuestion*);
SOAP_FMAC3 struct __ns4__SubmitQuestion * SOAP_FMAC4 soap_instantiate___ns4__SubmitQuestion(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns4__SubmitQuestion(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns3__GetAAFComments
#define SOAP_TYPE___ns3__GetAAFComments (83)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__GetAAFComments(struct soap*, struct __ns3__GetAAFComments *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__GetAAFComments(struct soap*, const struct __ns3__GetAAFComments *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__GetAAFComments(struct soap*, const struct __ns3__GetAAFComments *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__GetAAFComments(struct soap*, const char*, int, const struct __ns3__GetAAFComments *, const char*);
SOAP_FMAC3 struct __ns3__GetAAFComments * SOAP_FMAC4 soap_get___ns3__GetAAFComments(struct soap*, struct __ns3__GetAAFComments *, const char*, const char*);
SOAP_FMAC3 struct __ns3__GetAAFComments * SOAP_FMAC4 soap_in___ns3__GetAAFComments(struct soap*, const char*, struct __ns3__GetAAFComments *, const char*);
SOAP_FMAC5 struct __ns3__GetAAFComments * SOAP_FMAC6 soap_new___ns3__GetAAFComments(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns3__GetAAFComments(struct soap*, struct __ns3__GetAAFComments*);
SOAP_FMAC3 struct __ns3__GetAAFComments * SOAP_FMAC4 soap_instantiate___ns3__GetAAFComments(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns3__GetAAFComments(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns3__GetAAFResponse
#define SOAP_TYPE___ns3__GetAAFResponse (79)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__GetAAFResponse(struct soap*, struct __ns3__GetAAFResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__GetAAFResponse(struct soap*, const struct __ns3__GetAAFResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__GetAAFResponse(struct soap*, const struct __ns3__GetAAFResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__GetAAFResponse(struct soap*, const char*, int, const struct __ns3__GetAAFResponse *, const char*);
SOAP_FMAC3 struct __ns3__GetAAFResponse * SOAP_FMAC4 soap_get___ns3__GetAAFResponse(struct soap*, struct __ns3__GetAAFResponse *, const char*, const char*);
SOAP_FMAC3 struct __ns3__GetAAFResponse * SOAP_FMAC4 soap_in___ns3__GetAAFResponse(struct soap*, const char*, struct __ns3__GetAAFResponse *, const char*);
SOAP_FMAC5 struct __ns3__GetAAFResponse * SOAP_FMAC6 soap_new___ns3__GetAAFResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns3__GetAAFResponse(struct soap*, struct __ns3__GetAAFResponse*);
SOAP_FMAC3 struct __ns3__GetAAFResponse * SOAP_FMAC4 soap_instantiate___ns3__GetAAFResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns3__GetAAFResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns3__GetNewAAFQuestionCommentIDs
#define SOAP_TYPE___ns3__GetNewAAFQuestionCommentIDs (75)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__GetNewAAFQuestionCommentIDs(struct soap*, struct __ns3__GetNewAAFQuestionCommentIDs *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__GetNewAAFQuestionCommentIDs(struct soap*, const struct __ns3__GetNewAAFQuestionCommentIDs *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__GetNewAAFQuestionCommentIDs(struct soap*, const struct __ns3__GetNewAAFQuestionCommentIDs *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__GetNewAAFQuestionCommentIDs(struct soap*, const char*, int, const struct __ns3__GetNewAAFQuestionCommentIDs *, const char*);
SOAP_FMAC3 struct __ns3__GetNewAAFQuestionCommentIDs * SOAP_FMAC4 soap_get___ns3__GetNewAAFQuestionCommentIDs(struct soap*, struct __ns3__GetNewAAFQuestionCommentIDs *, const char*, const char*);
SOAP_FMAC3 struct __ns3__GetNewAAFQuestionCommentIDs * SOAP_FMAC4 soap_in___ns3__GetNewAAFQuestionCommentIDs(struct soap*, const char*, struct __ns3__GetNewAAFQuestionCommentIDs *, const char*);
SOAP_FMAC5 struct __ns3__GetNewAAFQuestionCommentIDs * SOAP_FMAC6 soap_new___ns3__GetNewAAFQuestionCommentIDs(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns3__GetNewAAFQuestionCommentIDs(struct soap*, struct __ns3__GetNewAAFQuestionCommentIDs*);
SOAP_FMAC3 struct __ns3__GetNewAAFQuestionCommentIDs * SOAP_FMAC4 soap_instantiate___ns3__GetNewAAFQuestionCommentIDs(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns3__GetNewAAFQuestionCommentIDs(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns3__GetMyAAFQuestions
#define SOAP_TYPE___ns3__GetMyAAFQuestions (71)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__GetMyAAFQuestions(struct soap*, struct __ns3__GetMyAAFQuestions *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__GetMyAAFQuestions(struct soap*, const struct __ns3__GetMyAAFQuestions *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__GetMyAAFQuestions(struct soap*, const struct __ns3__GetMyAAFQuestions *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__GetMyAAFQuestions(struct soap*, const char*, int, const struct __ns3__GetMyAAFQuestions *, const char*);
SOAP_FMAC3 struct __ns3__GetMyAAFQuestions * SOAP_FMAC4 soap_get___ns3__GetMyAAFQuestions(struct soap*, struct __ns3__GetMyAAFQuestions *, const char*, const char*);
SOAP_FMAC3 struct __ns3__GetMyAAFQuestions * SOAP_FMAC4 soap_in___ns3__GetMyAAFQuestions(struct soap*, const char*, struct __ns3__GetMyAAFQuestions *, const char*);
SOAP_FMAC5 struct __ns3__GetMyAAFQuestions * SOAP_FMAC6 soap_new___ns3__GetMyAAFQuestions(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns3__GetMyAAFQuestions(struct soap*, struct __ns3__GetMyAAFQuestions*);
SOAP_FMAC3 struct __ns3__GetMyAAFQuestions * SOAP_FMAC4 soap_instantiate___ns3__GetMyAAFQuestions(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns3__GetMyAAFQuestions(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns3__GetPrivateAAFQuestion
#define SOAP_TYPE___ns3__GetPrivateAAFQuestion (67)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__GetPrivateAAFQuestion(struct soap*, struct __ns3__GetPrivateAAFQuestion *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__GetPrivateAAFQuestion(struct soap*, const struct __ns3__GetPrivateAAFQuestion *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__GetPrivateAAFQuestion(struct soap*, const struct __ns3__GetPrivateAAFQuestion *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__GetPrivateAAFQuestion(struct soap*, const char*, int, const struct __ns3__GetPrivateAAFQuestion *, const char*);
SOAP_FMAC3 struct __ns3__GetPrivateAAFQuestion * SOAP_FMAC4 soap_get___ns3__GetPrivateAAFQuestion(struct soap*, struct __ns3__GetPrivateAAFQuestion *, const char*, const char*);
SOAP_FMAC3 struct __ns3__GetPrivateAAFQuestion * SOAP_FMAC4 soap_in___ns3__GetPrivateAAFQuestion(struct soap*, const char*, struct __ns3__GetPrivateAAFQuestion *, const char*);
SOAP_FMAC5 struct __ns3__GetPrivateAAFQuestion * SOAP_FMAC6 soap_new___ns3__GetPrivateAAFQuestion(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns3__GetPrivateAAFQuestion(struct soap*, struct __ns3__GetPrivateAAFQuestion*);
SOAP_FMAC3 struct __ns3__GetPrivateAAFQuestion * SOAP_FMAC4 soap_instantiate___ns3__GetPrivateAAFQuestion(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns3__GetPrivateAAFQuestion(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns3__CompleteQuestion
#define SOAP_TYPE___ns3__CompleteQuestion (63)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__CompleteQuestion(struct soap*, struct __ns3__CompleteQuestion *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__CompleteQuestion(struct soap*, const struct __ns3__CompleteQuestion *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__CompleteQuestion(struct soap*, const struct __ns3__CompleteQuestion *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__CompleteQuestion(struct soap*, const char*, int, const struct __ns3__CompleteQuestion *, const char*);
SOAP_FMAC3 struct __ns3__CompleteQuestion * SOAP_FMAC4 soap_get___ns3__CompleteQuestion(struct soap*, struct __ns3__CompleteQuestion *, const char*, const char*);
SOAP_FMAC3 struct __ns3__CompleteQuestion * SOAP_FMAC4 soap_in___ns3__CompleteQuestion(struct soap*, const char*, struct __ns3__CompleteQuestion *, const char*);
SOAP_FMAC5 struct __ns3__CompleteQuestion * SOAP_FMAC6 soap_new___ns3__CompleteQuestion(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns3__CompleteQuestion(struct soap*, struct __ns3__CompleteQuestion*);
SOAP_FMAC3 struct __ns3__CompleteQuestion * SOAP_FMAC4 soap_instantiate___ns3__CompleteQuestion(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns3__CompleteQuestion(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns3__AttachPhoto
#define SOAP_TYPE___ns3__AttachPhoto (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__AttachPhoto(struct soap*, struct __ns3__AttachPhoto *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__AttachPhoto(struct soap*, const struct __ns3__AttachPhoto *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__AttachPhoto(struct soap*, const struct __ns3__AttachPhoto *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__AttachPhoto(struct soap*, const char*, int, const struct __ns3__AttachPhoto *, const char*);
SOAP_FMAC3 struct __ns3__AttachPhoto * SOAP_FMAC4 soap_get___ns3__AttachPhoto(struct soap*, struct __ns3__AttachPhoto *, const char*, const char*);
SOAP_FMAC3 struct __ns3__AttachPhoto * SOAP_FMAC4 soap_in___ns3__AttachPhoto(struct soap*, const char*, struct __ns3__AttachPhoto *, const char*);
SOAP_FMAC5 struct __ns3__AttachPhoto * SOAP_FMAC6 soap_new___ns3__AttachPhoto(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns3__AttachPhoto(struct soap*, struct __ns3__AttachPhoto*);
SOAP_FMAC3 struct __ns3__AttachPhoto * SOAP_FMAC4 soap_instantiate___ns3__AttachPhoto(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns3__AttachPhoto(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns3__SubmitQuestion
#define SOAP_TYPE___ns3__SubmitQuestion (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__SubmitQuestion(struct soap*, struct __ns3__SubmitQuestion *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__SubmitQuestion(struct soap*, const struct __ns3__SubmitQuestion *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__SubmitQuestion(struct soap*, const struct __ns3__SubmitQuestion *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__SubmitQuestion(struct soap*, const char*, int, const struct __ns3__SubmitQuestion *, const char*);
SOAP_FMAC3 struct __ns3__SubmitQuestion * SOAP_FMAC4 soap_get___ns3__SubmitQuestion(struct soap*, struct __ns3__SubmitQuestion *, const char*, const char*);
SOAP_FMAC3 struct __ns3__SubmitQuestion * SOAP_FMAC4 soap_in___ns3__SubmitQuestion(struct soap*, const char*, struct __ns3__SubmitQuestion *, const char*);
SOAP_FMAC5 struct __ns3__SubmitQuestion * SOAP_FMAC6 soap_new___ns3__SubmitQuestion(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns3__SubmitQuestion(struct soap*, struct __ns3__SubmitQuestion*);
SOAP_FMAC3 struct __ns3__SubmitQuestion * SOAP_FMAC4 soap_instantiate___ns3__SubmitQuestion(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns3__SubmitQuestion(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (109)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (108)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (102)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerTo_ns1__GetAAFCommentsResponse
#define SOAP_TYPE_PointerTo_ns1__GetAAFCommentsResponse (81)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetAAFCommentsResponse(struct soap*, _ns1__GetAAFCommentsResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetAAFCommentsResponse(struct soap*, _ns1__GetAAFCommentsResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetAAFCommentsResponse(struct soap*, const char *, int, _ns1__GetAAFCommentsResponse *const*, const char *);
SOAP_FMAC3 _ns1__GetAAFCommentsResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetAAFCommentsResponse(struct soap*, _ns1__GetAAFCommentsResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__GetAAFCommentsResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetAAFCommentsResponse(struct soap*, const char*, _ns1__GetAAFCommentsResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__GetAAFComments
#define SOAP_TYPE_PointerTo_ns1__GetAAFComments (80)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetAAFComments(struct soap*, _ns1__GetAAFComments *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetAAFComments(struct soap*, _ns1__GetAAFComments *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetAAFComments(struct soap*, const char *, int, _ns1__GetAAFComments *const*, const char *);
SOAP_FMAC3 _ns1__GetAAFComments ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetAAFComments(struct soap*, _ns1__GetAAFComments **, const char*, const char*);
SOAP_FMAC3 _ns1__GetAAFComments ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetAAFComments(struct soap*, const char*, _ns1__GetAAFComments **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__GetAAFResponseResponse
#define SOAP_TYPE_PointerTo_ns1__GetAAFResponseResponse (77)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetAAFResponseResponse(struct soap*, _ns1__GetAAFResponseResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetAAFResponseResponse(struct soap*, _ns1__GetAAFResponseResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetAAFResponseResponse(struct soap*, const char *, int, _ns1__GetAAFResponseResponse *const*, const char *);
SOAP_FMAC3 _ns1__GetAAFResponseResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetAAFResponseResponse(struct soap*, _ns1__GetAAFResponseResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__GetAAFResponseResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetAAFResponseResponse(struct soap*, const char*, _ns1__GetAAFResponseResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__GetAAFResponse
#define SOAP_TYPE_PointerTo_ns1__GetAAFResponse (76)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetAAFResponse(struct soap*, _ns1__GetAAFResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetAAFResponse(struct soap*, _ns1__GetAAFResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetAAFResponse(struct soap*, const char *, int, _ns1__GetAAFResponse *const*, const char *);
SOAP_FMAC3 _ns1__GetAAFResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetAAFResponse(struct soap*, _ns1__GetAAFResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__GetAAFResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetAAFResponse(struct soap*, const char*, _ns1__GetAAFResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__GetNewAAFQuestionCommentIDsResponse
#define SOAP_TYPE_PointerTo_ns1__GetNewAAFQuestionCommentIDsResponse (73)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetNewAAFQuestionCommentIDsResponse(struct soap*, _ns1__GetNewAAFQuestionCommentIDsResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetNewAAFQuestionCommentIDsResponse(struct soap*, _ns1__GetNewAAFQuestionCommentIDsResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetNewAAFQuestionCommentIDsResponse(struct soap*, const char *, int, _ns1__GetNewAAFQuestionCommentIDsResponse *const*, const char *);
SOAP_FMAC3 _ns1__GetNewAAFQuestionCommentIDsResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetNewAAFQuestionCommentIDsResponse(struct soap*, _ns1__GetNewAAFQuestionCommentIDsResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__GetNewAAFQuestionCommentIDsResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetNewAAFQuestionCommentIDsResponse(struct soap*, const char*, _ns1__GetNewAAFQuestionCommentIDsResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__GetNewAAFQuestionCommentIDs
#define SOAP_TYPE_PointerTo_ns1__GetNewAAFQuestionCommentIDs (72)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetNewAAFQuestionCommentIDs(struct soap*, _ns1__GetNewAAFQuestionCommentIDs *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetNewAAFQuestionCommentIDs(struct soap*, _ns1__GetNewAAFQuestionCommentIDs *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetNewAAFQuestionCommentIDs(struct soap*, const char *, int, _ns1__GetNewAAFQuestionCommentIDs *const*, const char *);
SOAP_FMAC3 _ns1__GetNewAAFQuestionCommentIDs ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetNewAAFQuestionCommentIDs(struct soap*, _ns1__GetNewAAFQuestionCommentIDs **, const char*, const char*);
SOAP_FMAC3 _ns1__GetNewAAFQuestionCommentIDs ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetNewAAFQuestionCommentIDs(struct soap*, const char*, _ns1__GetNewAAFQuestionCommentIDs **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__GetMyAAFQuestionsResponse
#define SOAP_TYPE_PointerTo_ns1__GetMyAAFQuestionsResponse (69)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetMyAAFQuestionsResponse(struct soap*, _ns1__GetMyAAFQuestionsResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetMyAAFQuestionsResponse(struct soap*, _ns1__GetMyAAFQuestionsResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetMyAAFQuestionsResponse(struct soap*, const char *, int, _ns1__GetMyAAFQuestionsResponse *const*, const char *);
SOAP_FMAC3 _ns1__GetMyAAFQuestionsResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetMyAAFQuestionsResponse(struct soap*, _ns1__GetMyAAFQuestionsResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__GetMyAAFQuestionsResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetMyAAFQuestionsResponse(struct soap*, const char*, _ns1__GetMyAAFQuestionsResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__GetMyAAFQuestions
#define SOAP_TYPE_PointerTo_ns1__GetMyAAFQuestions (68)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetMyAAFQuestions(struct soap*, _ns1__GetMyAAFQuestions *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetMyAAFQuestions(struct soap*, _ns1__GetMyAAFQuestions *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetMyAAFQuestions(struct soap*, const char *, int, _ns1__GetMyAAFQuestions *const*, const char *);
SOAP_FMAC3 _ns1__GetMyAAFQuestions ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetMyAAFQuestions(struct soap*, _ns1__GetMyAAFQuestions **, const char*, const char*);
SOAP_FMAC3 _ns1__GetMyAAFQuestions ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetMyAAFQuestions(struct soap*, const char*, _ns1__GetMyAAFQuestions **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__GetPrivateAAFQuestionResponse
#define SOAP_TYPE_PointerTo_ns1__GetPrivateAAFQuestionResponse (65)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetPrivateAAFQuestionResponse(struct soap*, _ns1__GetPrivateAAFQuestionResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetPrivateAAFQuestionResponse(struct soap*, _ns1__GetPrivateAAFQuestionResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetPrivateAAFQuestionResponse(struct soap*, const char *, int, _ns1__GetPrivateAAFQuestionResponse *const*, const char *);
SOAP_FMAC3 _ns1__GetPrivateAAFQuestionResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetPrivateAAFQuestionResponse(struct soap*, _ns1__GetPrivateAAFQuestionResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__GetPrivateAAFQuestionResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetPrivateAAFQuestionResponse(struct soap*, const char*, _ns1__GetPrivateAAFQuestionResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__GetPrivateAAFQuestion
#define SOAP_TYPE_PointerTo_ns1__GetPrivateAAFQuestion (64)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetPrivateAAFQuestion(struct soap*, _ns1__GetPrivateAAFQuestion *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetPrivateAAFQuestion(struct soap*, _ns1__GetPrivateAAFQuestion *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetPrivateAAFQuestion(struct soap*, const char *, int, _ns1__GetPrivateAAFQuestion *const*, const char *);
SOAP_FMAC3 _ns1__GetPrivateAAFQuestion ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetPrivateAAFQuestion(struct soap*, _ns1__GetPrivateAAFQuestion **, const char*, const char*);
SOAP_FMAC3 _ns1__GetPrivateAAFQuestion ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetPrivateAAFQuestion(struct soap*, const char*, _ns1__GetPrivateAAFQuestion **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__CompleteQuestionResponse
#define SOAP_TYPE_PointerTo_ns1__CompleteQuestionResponse (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__CompleteQuestionResponse(struct soap*, _ns1__CompleteQuestionResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__CompleteQuestionResponse(struct soap*, _ns1__CompleteQuestionResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__CompleteQuestionResponse(struct soap*, const char *, int, _ns1__CompleteQuestionResponse *const*, const char *);
SOAP_FMAC3 _ns1__CompleteQuestionResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__CompleteQuestionResponse(struct soap*, _ns1__CompleteQuestionResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__CompleteQuestionResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__CompleteQuestionResponse(struct soap*, const char*, _ns1__CompleteQuestionResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__CompleteQuestion
#define SOAP_TYPE_PointerTo_ns1__CompleteQuestion (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__CompleteQuestion(struct soap*, _ns1__CompleteQuestion *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__CompleteQuestion(struct soap*, _ns1__CompleteQuestion *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__CompleteQuestion(struct soap*, const char *, int, _ns1__CompleteQuestion *const*, const char *);
SOAP_FMAC3 _ns1__CompleteQuestion ** SOAP_FMAC4 soap_get_PointerTo_ns1__CompleteQuestion(struct soap*, _ns1__CompleteQuestion **, const char*, const char*);
SOAP_FMAC3 _ns1__CompleteQuestion ** SOAP_FMAC4 soap_in_PointerTo_ns1__CompleteQuestion(struct soap*, const char*, _ns1__CompleteQuestion **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__AttachPhotoResponse
#define SOAP_TYPE_PointerTo_ns1__AttachPhotoResponse (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__AttachPhotoResponse(struct soap*, _ns1__AttachPhotoResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__AttachPhotoResponse(struct soap*, _ns1__AttachPhotoResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__AttachPhotoResponse(struct soap*, const char *, int, _ns1__AttachPhotoResponse *const*, const char *);
SOAP_FMAC3 _ns1__AttachPhotoResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__AttachPhotoResponse(struct soap*, _ns1__AttachPhotoResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__AttachPhotoResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__AttachPhotoResponse(struct soap*, const char*, _ns1__AttachPhotoResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__AttachPhoto
#define SOAP_TYPE_PointerTo_ns1__AttachPhoto (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__AttachPhoto(struct soap*, _ns1__AttachPhoto *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__AttachPhoto(struct soap*, _ns1__AttachPhoto *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__AttachPhoto(struct soap*, const char *, int, _ns1__AttachPhoto *const*, const char *);
SOAP_FMAC3 _ns1__AttachPhoto ** SOAP_FMAC4 soap_get_PointerTo_ns1__AttachPhoto(struct soap*, _ns1__AttachPhoto **, const char*, const char*);
SOAP_FMAC3 _ns1__AttachPhoto ** SOAP_FMAC4 soap_in_PointerTo_ns1__AttachPhoto(struct soap*, const char*, _ns1__AttachPhoto **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__SubmitQuestionResponse
#define SOAP_TYPE_PointerTo_ns1__SubmitQuestionResponse (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__SubmitQuestionResponse(struct soap*, _ns1__SubmitQuestionResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__SubmitQuestionResponse(struct soap*, _ns1__SubmitQuestionResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__SubmitQuestionResponse(struct soap*, const char *, int, _ns1__SubmitQuestionResponse *const*, const char *);
SOAP_FMAC3 _ns1__SubmitQuestionResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__SubmitQuestionResponse(struct soap*, _ns1__SubmitQuestionResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__SubmitQuestionResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__SubmitQuestionResponse(struct soap*, const char*, _ns1__SubmitQuestionResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__SubmitQuestion
#define SOAP_TYPE_PointerTo_ns1__SubmitQuestion (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__SubmitQuestion(struct soap*, _ns1__SubmitQuestion *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__SubmitQuestion(struct soap*, _ns1__SubmitQuestion *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__SubmitQuestion(struct soap*, const char *, int, _ns1__SubmitQuestion *const*, const char *);
SOAP_FMAC3 _ns1__SubmitQuestion ** SOAP_FMAC4 soap_get_PointerTo_ns1__SubmitQuestion(struct soap*, _ns1__SubmitQuestion **, const char*, const char*);
SOAP_FMAC3 _ns1__SubmitQuestion ** SOAP_FMAC4 soap_in_PointerTo_ns1__SubmitQuestion(struct soap*, const char*, _ns1__SubmitQuestion **, const char*);

#ifndef SOAP_TYPE_PointerTons1__ArrayOfAskAFriendComment
#define SOAP_TYPE_PointerTons1__ArrayOfAskAFriendComment (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ArrayOfAskAFriendComment(struct soap*, ns1__ArrayOfAskAFriendComment *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ArrayOfAskAFriendComment(struct soap*, ns1__ArrayOfAskAFriendComment *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ArrayOfAskAFriendComment(struct soap*, const char *, int, ns1__ArrayOfAskAFriendComment *const*, const char *);
SOAP_FMAC3 ns1__ArrayOfAskAFriendComment ** SOAP_FMAC4 soap_get_PointerTons1__ArrayOfAskAFriendComment(struct soap*, ns1__ArrayOfAskAFriendComment **, const char*, const char*);
SOAP_FMAC3 ns1__ArrayOfAskAFriendComment ** SOAP_FMAC4 soap_in_PointerTons1__ArrayOfAskAFriendComment(struct soap*, const char*, ns1__ArrayOfAskAFriendComment **, const char*);

#ifndef SOAP_TYPE_PointerTons1__AskAFriendResponse
#define SOAP_TYPE_PointerTons1__AskAFriendResponse (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__AskAFriendResponse(struct soap*, ns1__AskAFriendResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__AskAFriendResponse(struct soap*, ns1__AskAFriendResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__AskAFriendResponse(struct soap*, const char *, int, ns1__AskAFriendResponse *const*, const char *);
SOAP_FMAC3 ns1__AskAFriendResponse ** SOAP_FMAC4 soap_get_PointerTons1__AskAFriendResponse(struct soap*, ns1__AskAFriendResponse **, const char*, const char*);
SOAP_FMAC3 ns1__AskAFriendResponse ** SOAP_FMAC4 soap_in_PointerTons1__AskAFriendResponse(struct soap*, const char*, ns1__AskAFriendResponse **, const char*);

#ifndef SOAP_TYPE_PointerTons1__ArrayOfAskAFriendQuestion
#define SOAP_TYPE_PointerTons1__ArrayOfAskAFriendQuestion (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ArrayOfAskAFriendQuestion(struct soap*, ns1__ArrayOfAskAFriendQuestion *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ArrayOfAskAFriendQuestion(struct soap*, ns1__ArrayOfAskAFriendQuestion *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ArrayOfAskAFriendQuestion(struct soap*, const char *, int, ns1__ArrayOfAskAFriendQuestion *const*, const char *);
SOAP_FMAC3 ns1__ArrayOfAskAFriendQuestion ** SOAP_FMAC4 soap_get_PointerTons1__ArrayOfAskAFriendQuestion(struct soap*, ns1__ArrayOfAskAFriendQuestion **, const char*, const char*);
SOAP_FMAC3 ns1__ArrayOfAskAFriendQuestion ** SOAP_FMAC4 soap_in_PointerTons1__ArrayOfAskAFriendQuestion(struct soap*, const char*, ns1__ArrayOfAskAFriendQuestion **, const char*);

#ifndef SOAP_TYPE_PointerTons1__ArrayOfPrivateAAFQuestion
#define SOAP_TYPE_PointerTons1__ArrayOfPrivateAAFQuestion (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ArrayOfPrivateAAFQuestion(struct soap*, ns1__ArrayOfPrivateAAFQuestion *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ArrayOfPrivateAAFQuestion(struct soap*, ns1__ArrayOfPrivateAAFQuestion *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ArrayOfPrivateAAFQuestion(struct soap*, const char *, int, ns1__ArrayOfPrivateAAFQuestion *const*, const char *);
SOAP_FMAC3 ns1__ArrayOfPrivateAAFQuestion ** SOAP_FMAC4 soap_get_PointerTons1__ArrayOfPrivateAAFQuestion(struct soap*, ns1__ArrayOfPrivateAAFQuestion **, const char*, const char*);
SOAP_FMAC3 ns1__ArrayOfPrivateAAFQuestion ** SOAP_FMAC4 soap_in_PointerTons1__ArrayOfPrivateAAFQuestion(struct soap*, const char*, ns1__ArrayOfPrivateAAFQuestion **, const char*);

#ifndef SOAP_TYPE_PointerTons1__AskAFriendConfirm
#define SOAP_TYPE_PointerTons1__AskAFriendConfirm (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__AskAFriendConfirm(struct soap*, ns1__AskAFriendConfirm *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__AskAFriendConfirm(struct soap*, ns1__AskAFriendConfirm *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__AskAFriendConfirm(struct soap*, const char *, int, ns1__AskAFriendConfirm *const*, const char *);
SOAP_FMAC3 ns1__AskAFriendConfirm ** SOAP_FMAC4 soap_get_PointerTons1__AskAFriendConfirm(struct soap*, ns1__AskAFriendConfirm **, const char*, const char*);
SOAP_FMAC3 ns1__AskAFriendConfirm ** SOAP_FMAC4 soap_in_PointerTons1__AskAFriendConfirm(struct soap*, const char*, ns1__AskAFriendConfirm **, const char*);

#ifndef SOAP_TYPE_PointerToPointerTons1__AskAFriendComment
#define SOAP_TYPE_PointerToPointerTons1__AskAFriendComment (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerTons1__AskAFriendComment(struct soap*, ns1__AskAFriendComment **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerTons1__AskAFriendComment(struct soap*, ns1__AskAFriendComment **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerTons1__AskAFriendComment(struct soap*, const char *, int, ns1__AskAFriendComment **const*, const char *);
SOAP_FMAC3 ns1__AskAFriendComment *** SOAP_FMAC4 soap_get_PointerToPointerTons1__AskAFriendComment(struct soap*, ns1__AskAFriendComment ***, const char*, const char*);
SOAP_FMAC3 ns1__AskAFriendComment *** SOAP_FMAC4 soap_in_PointerToPointerTons1__AskAFriendComment(struct soap*, const char*, ns1__AskAFriendComment ***, const char*);

#ifndef SOAP_TYPE_PointerTons1__AskAFriendComment
#define SOAP_TYPE_PointerTons1__AskAFriendComment (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__AskAFriendComment(struct soap*, ns1__AskAFriendComment *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__AskAFriendComment(struct soap*, ns1__AskAFriendComment *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__AskAFriendComment(struct soap*, const char *, int, ns1__AskAFriendComment *const*, const char *);
SOAP_FMAC3 ns1__AskAFriendComment ** SOAP_FMAC4 soap_get_PointerTons1__AskAFriendComment(struct soap*, ns1__AskAFriendComment **, const char*, const char*);
SOAP_FMAC3 ns1__AskAFriendComment ** SOAP_FMAC4 soap_in_PointerTons1__AskAFriendComment(struct soap*, const char*, ns1__AskAFriendComment **, const char*);

#ifndef SOAP_TYPE_PointerToint
#define SOAP_TYPE_PointerToint (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToint(struct soap*, int *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToint(struct soap*, int *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToint(struct soap*, const char *, int, int *const*, const char *);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_get_PointerToint(struct soap*, int **, const char*, const char*);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_in_PointerToint(struct soap*, const char*, int **, const char*);

#ifndef SOAP_TYPE_PointerTons1__ArrayOfString
#define SOAP_TYPE_PointerTons1__ArrayOfString (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ArrayOfString(struct soap*, ns1__ArrayOfString *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ArrayOfString(struct soap*, ns1__ArrayOfString *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ArrayOfString(struct soap*, const char *, int, ns1__ArrayOfString *const*, const char *);
SOAP_FMAC3 ns1__ArrayOfString ** SOAP_FMAC4 soap_get_PointerTons1__ArrayOfString(struct soap*, ns1__ArrayOfString **, const char*, const char*);
SOAP_FMAC3 ns1__ArrayOfString ** SOAP_FMAC4 soap_in_PointerTons1__ArrayOfString(struct soap*, const char*, ns1__ArrayOfString **, const char*);

#ifndef SOAP_TYPE_PointerTons1__ArrayOfInt
#define SOAP_TYPE_PointerTons1__ArrayOfInt (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ArrayOfInt(struct soap*, ns1__ArrayOfInt *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ArrayOfInt(struct soap*, ns1__ArrayOfInt *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ArrayOfInt(struct soap*, const char *, int, ns1__ArrayOfInt *const*, const char *);
SOAP_FMAC3 ns1__ArrayOfInt ** SOAP_FMAC4 soap_get_PointerTons1__ArrayOfInt(struct soap*, ns1__ArrayOfInt **, const char*, const char*);
SOAP_FMAC3 ns1__ArrayOfInt ** SOAP_FMAC4 soap_in_PointerTons1__ArrayOfInt(struct soap*, const char*, ns1__ArrayOfInt **, const char*);

#ifndef SOAP_TYPE_PointerToPointerTons1__AskAFriendQuestion
#define SOAP_TYPE_PointerToPointerTons1__AskAFriendQuestion (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerTons1__AskAFriendQuestion(struct soap*, ns1__AskAFriendQuestion **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerTons1__AskAFriendQuestion(struct soap*, ns1__AskAFriendQuestion **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerTons1__AskAFriendQuestion(struct soap*, const char *, int, ns1__AskAFriendQuestion **const*, const char *);
SOAP_FMAC3 ns1__AskAFriendQuestion *** SOAP_FMAC4 soap_get_PointerToPointerTons1__AskAFriendQuestion(struct soap*, ns1__AskAFriendQuestion ***, const char*, const char*);
SOAP_FMAC3 ns1__AskAFriendQuestion *** SOAP_FMAC4 soap_in_PointerToPointerTons1__AskAFriendQuestion(struct soap*, const char*, ns1__AskAFriendQuestion ***, const char*);

#ifndef SOAP_TYPE_PointerTons1__AskAFriendQuestion
#define SOAP_TYPE_PointerTons1__AskAFriendQuestion (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__AskAFriendQuestion(struct soap*, ns1__AskAFriendQuestion *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__AskAFriendQuestion(struct soap*, ns1__AskAFriendQuestion *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__AskAFriendQuestion(struct soap*, const char *, int, ns1__AskAFriendQuestion *const*, const char *);
SOAP_FMAC3 ns1__AskAFriendQuestion ** SOAP_FMAC4 soap_get_PointerTons1__AskAFriendQuestion(struct soap*, ns1__AskAFriendQuestion **, const char*, const char*);
SOAP_FMAC3 ns1__AskAFriendQuestion ** SOAP_FMAC4 soap_in_PointerTons1__AskAFriendQuestion(struct soap*, const char*, ns1__AskAFriendQuestion **, const char*);

#ifndef SOAP_TYPE_PointerToPointerTons1__PrivateAAFQuestion
#define SOAP_TYPE_PointerToPointerTons1__PrivateAAFQuestion (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerTons1__PrivateAAFQuestion(struct soap*, ns1__PrivateAAFQuestion **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerTons1__PrivateAAFQuestion(struct soap*, ns1__PrivateAAFQuestion **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerTons1__PrivateAAFQuestion(struct soap*, const char *, int, ns1__PrivateAAFQuestion **const*, const char *);
SOAP_FMAC3 ns1__PrivateAAFQuestion *** SOAP_FMAC4 soap_get_PointerToPointerTons1__PrivateAAFQuestion(struct soap*, ns1__PrivateAAFQuestion ***, const char*, const char*);
SOAP_FMAC3 ns1__PrivateAAFQuestion *** SOAP_FMAC4 soap_in_PointerToPointerTons1__PrivateAAFQuestion(struct soap*, const char*, ns1__PrivateAAFQuestion ***, const char*);

#ifndef SOAP_TYPE_PointerTons1__PrivateAAFQuestion
#define SOAP_TYPE_PointerTons1__PrivateAAFQuestion (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__PrivateAAFQuestion(struct soap*, ns1__PrivateAAFQuestion *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__PrivateAAFQuestion(struct soap*, ns1__PrivateAAFQuestion *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__PrivateAAFQuestion(struct soap*, const char *, int, ns1__PrivateAAFQuestion *const*, const char *);
SOAP_FMAC3 ns1__PrivateAAFQuestion ** SOAP_FMAC4 soap_get_PointerTons1__PrivateAAFQuestion(struct soap*, ns1__PrivateAAFQuestion **, const char*, const char*);
SOAP_FMAC3 ns1__PrivateAAFQuestion ** SOAP_FMAC4 soap_in_PointerTons1__PrivateAAFQuestion(struct soap*, const char*, ns1__PrivateAAFQuestion **, const char*);

#ifndef SOAP_TYPE_PointerTostring
#define SOAP_TYPE_PointerTostring (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostring(struct soap*, char **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostring(struct soap*, char **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostring(struct soap*, const char *, int, char **const*, const char *);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_get_PointerTostring(struct soap*, char ***, const char*, const char*);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_in_PointerTostring(struct soap*, const char*, char ***, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#endif

/* End of soapH.h */
