//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TD.rc
//
#define IDS_TEXT_POINT                  1
#define IDS_SEL_TEXT_POINT              2
#define IDS_TEXT_PARAMS                 3
#define IDS_DIM_PARAM                   4
#define IDS_TA_CENTER                   5
#define IDS_TA_LEFT                     6
#define IDS_F_POINT                     7
#define IDS_ENTER_F_POINT               8
#define IDS_S_POINT                     9
#define IDS_ENTER_S_POINT               10
#define IDS_L_POINT                     11
#define IDS_ENTER_L_POINT               12
#define IDS_ERROR_POINT_IS_EQ           13
#define IDS_REDACTION                   14
#define IDS_TOOLTIP_FIVETH              15
#define IDS_STBAR_FIVETH                16
#define IDS_TA_RIGHT                    17
#define IDS_LIN_STYLE                   18
#define IDS_TEXT_ALIGN                  19
#define IDS_TEXT_ORIENT                 20
#define IDS_TEXT_ORINT_H                21
#define IDS_TEXT_ORINT_V                22
#define IDS_EDIT_TEXT_STYLE             23
#define IDS_ENTER_NEW_STYLE             24
#define IDS_ENTER_NEW_TEXT              25
#define IDS_DIM_ST_PARALL               26
#define IDS_DIM_ST_POINTS               27
#define IDS_DIM_ST_OPT                  28
#define IDS_PRECIS                      29
#define IDS_OBJECT                      30
#define IDR_TOOLBAR                     4020
#define IDC_PREVIEW_FRAME               4037
#define IDC_SYM_HEIGHT_EDIT             4040
#define IDC_SYM_ANGLE_EDIT              4041
#define IDC_LIST1                       4044
#define IDC_SYMB_PROPOPT_EDIT           4045
#define IDC_SYMB_SPACE_EDIT             4047
#define IDC_LINES_SPACE_EDIT            4049
#define IDC_LD_RAZM_LIN_CHECK           4060
#define IDC_LD_LEFT_DIM_CHECK           4061
#define IDC_LD_RIGHT_DIM_CHECK          4062
#define IDC_LD_VINOS_EDIT               4063
#define IDC_LD_VINOS_STATIC             4064
#define IDC_LD_LEFT_END_OUT_CHECK       4065
#define IDC_LD_LEFT_END_STATIC          4066
#define IDC_LD_LEFT_END_TYPE_COMBO      4067
#define IDC_LD_RIGHT_END_OUT_CHECK      4068
#define IDC_LD_RIGHT_END_STATIC         4069
#define IDC_LD_RIGHT_END_TYPE_COMBO     4070
#define IDC_LD_END_SIZE_STATIC          4071
#define IDC_LD_END_SIZE_EDIT            4072
#define IDC_LIN_STYLE                   4075
#define IDC_RADIO2                      4076
#define IDB_TOOLBAR32_BMP               4077
#define IDC_RADIO3                      4077
#define IDC_RADIO4                      4078
#define IDD_TEXT_PARAMS_DLG             4079
#define IDC_RADIO5                      4079
#define IDC_LEFT_END_STATIC             4080
#define IDC_RIGHT_END_STATIC            4081
#define IDC_CHECK1                      4082
#define IDC_LIN_DIM_AUTO_ARR            4082
#define IDC_EDIT1                       4083
#define IDC_TEXT_TEXT_EDIT              4083
#define IDC_LIN_DIM_AUTO_ARR2           4083
#define IDC_LIN_DIM_INVERT              4083
#define IDB_BITMAP1                     4086
#define IDD_LINEAR_DIM_DLG              4087
#define IDB_BITMAP2                     4088
#define IDB_BITMAP3                     4089
#define IDB_BITMAP4                     4090
#define IDB_BITMAP5                     4091
#define IDB_BITMAP6                     4092
#define IDB_BITMAP7                     4093
#define IDB_BITMAP8                     4094
#define IDB_BITMAP9                     4095
#define IDB_BITMAP10                    4096
#define IDB_BITMAP11                    4097
#define IDB_BITMAP12                    4098
#define IDB_BITMAP13                    4099
#define IDB_BITMAP14                    4100
#define IDB_BITMAP15                    4101
#define IDB_BITMAP16                    4102
#define IDB_BITMAP17                    4103
#define IDB_BITMAP18                    4104
#define IDB_BITMAP19                    4105
#define IDB_BITMAP20                    4106
#define IDB_BITMAP21                    4107
#define IDB_BITMAP22                    4108
#define IDB_BITMAP23                    4109
#define IDB_BITMAP24                    4110
#define IDB_BITMAP25                    4111
#define IDB_BITMAP26                    4112
#define IDB_BITMAP27                    4113
#define IDB_BITMAP28                    4114
#define IDB_BITMAP29                    4115
#define IDB_BITMAP30                    4116
#define IDB_BITMAP31                    4117
#define IDB_BITMAP32                    4118
#define IDD_TEXT_TEXT_DLG               4120
#define IDB_TEXT32                      4121
#define IDB_BITMAP34                    4122
#define IDB_ANG32                       4122
#define IDB_BITMAP35                    4123
#define IDB_DIAM32                      4123
#define IDB_BITMAP36                    4124
#define IDB_LINEAR32                    4124
#define IDB_BITMAP37                    4125
#define IDB_RAD32                       4125
#define ID_BUTTON_0                     32783
#define ID_BUTTON_1                     32784
#define ID_BUTTON_2                     32785
#define ID_BUTTON_3                     32786
#define ID_BUTTON_4                     32787
#define ID_BUTTON_5                     32788
#define ID_BUTTON_6                     32789
#define ID_BUTTON_7                     32790
#define ID_BUTTON_8                     32791
#define ID_BUTTON32793                  32793
#define IDS_MENU_STRING                 33775
#define IDS_STBAR_ZERO                  33776
#define IDS_TOOLTIP_ZERO                33777
#define IDS_STBAR_FIRST                 33778
#define IDS_STBAR_SECOND                33779
#define IDS_TOOLTIP_FIRST               33780
#define IDS_TOOLTIP_SECOND              33781
#define IDS_STBAR_THIRD                 33786
#define IDS_STBAR_FOURTH                33787
#define IDS_TOOLTIP_THIRD               33788
#define IDS_TOOLTIP_FOURTH              33789

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        4126
#define _APS_NEXT_COMMAND_VALUE         32797
#define _APS_NEXT_CONTROL_VALUE         4084
#define _APS_NEXT_SYMED_VALUE           4000
#endif
#endif
