#ifndef __RT_MATERIALS__
#define __RT_MATERIALS__
#include "sgCore/rtEngine.h"


typedef  enum
{
	MATERIAL_GLASS_1    = 1,
	MATERIAL_GLASS_2 ,
	MATERIAL_GLASS_3 ,
	MATERIAL_GLASS_4 ,
	MATERIAL_GLASS_5 ,
	MATERIAL_GLASS_6 ,
	MATERIAL_GLASS_7 ,
	MATERIAL_GLASS_8 ,
	MATERIAL_GLASS_9 ,
	MATERIAL_GLASS_10  ,
	MATERIAL_GLASS_11  ,
	MATERIAL_GLASS_12  ,
	MATERIAL_METALL_BRONZE_1 ,
	MATERIAL_METALL_BRONZE_2 ,
	MATERIAL_METALL_BRONZE_3 ,
	MATERIAL_METALL_BRONZE_4 ,
	MATERIAL_METALL_BRONZE_5 ,
	MATERIAL_METALL_BRONZE_6 ,
	MATERIAL_METALL_BRONZE_7 ,
	MATERIAL_METALL_BRONZE_8 ,
	MATERIAL_METALL_BRONZE_9 ,
	MATERIAL_METALL_BRONZE_10 ,
	MATERIAL_METALL_BRONZE_11 ,
	MATERIAL_METALL_BRONZE_12 ,
	MATERIAL_METALL_BRONZE_13 ,
	MATERIAL_METALL_BRONZE_14 ,
	MATERIAL_METALL_BRONZE_15 ,
	MATERIAL_METALL_BRONZE_16 ,
	MATERIAL_METALL_BRONZE_17 ,
	MATERIAL_METALL_BRONZE_18 ,
	MATERIAL_METALL_BRONZE_19 ,
	MATERIAL_METALL_BRONZE_20 ,
	MATERIAL_METALL_BRONZE_21 ,
	MATERIAL_METALL_BRONZE_22 ,
	MATERIAL_METALL_BRONZE_23 ,
	MATERIAL_METALL_BRONZE_24 ,
	MATERIAL_METALL_BRONZE_25 ,
	MATERIAL_METALL_CHROME_1 ,
	MATERIAL_METALL_CHROME_2 ,
	MATERIAL_METALL_CHROME_3 ,
	MATERIAL_METALL_CHROME_4 ,
	MATERIAL_METALL_CHROME_5 ,
	MATERIAL_METALL_CHROME_6 ,
	MATERIAL_METALL_CHROME_7 ,
	MATERIAL_METALL_CHROME_8 ,
	MATERIAL_METALL_CHROME_9 ,
	MATERIAL_METALL_CHROME_10 ,
	MATERIAL_METALL_CHROME_11 ,
	MATERIAL_METALL_CHROME_12 ,
	MATERIAL_METALL_CHROME_13 ,
	MATERIAL_METALL_CHROME_14 ,
	MATERIAL_METALL_CHROME_15 ,
	MATERIAL_METALL_CHROME_16 ,
	MATERIAL_METALL_CHROME_17  ,
	MATERIAL_METALL_CHROME_18  ,
	MATERIAL_METALL_CHROME_19  ,
	MATERIAL_METALL_CHROME_20  ,
	MATERIAL_METALL_CHROME_21  ,
	MATERIAL_METALL_CHROME_22  ,
	MATERIAL_METALL_CHROME_23  ,
	MATERIAL_METALL_CHROME_24  ,
	MATERIAL_METALL_CHROME_25  ,
	MATERIAL_METALL_SILVER_1  ,
	MATERIAL_METALL_SILVER_2  ,
	MATERIAL_METALL_SILVER_3  ,
	MATERIAL_METALL_SILVER_4  ,
	MATERIAL_METALL_SILVER_5  ,
	MATERIAL_METALL_SILVER_6  ,
	MATERIAL_METALL_SILVER_7  ,
	MATERIAL_METALL_SILVER_8  ,
	MATERIAL_METALL_SILVER_9  ,
	MATERIAL_METALL_SILVER_10  ,
	MATERIAL_METALL_SILVER_11  ,
	MATERIAL_METALL_SILVER_12  ,
	MATERIAL_METALL_SILVER_13  ,
	MATERIAL_METALL_SILVER_14  ,
	MATERIAL_METALL_SILVER_15  ,
	MATERIAL_METALL_SILVER_16  ,
	MATERIAL_METALL_SILVER_17  ,
	MATERIAL_METALL_SILVER_18  ,
	MATERIAL_METALL_SILVER_19  ,
	MATERIAL_METALL_SILVER_20  ,
	MATERIAL_METALL_SILVER_21  ,
	MATERIAL_METALL_SILVER_22  ,
	MATERIAL_METALL_SILVER_23  ,
	MATERIAL_METALL_SILVER_24  ,
	MATERIAL_METALL_SILVER_25  ,
	MATERIAL_METALL_GOLD_1  ,
	MATERIAL_METALL_GOLD_2  ,
	MATERIAL_METALL_GOLD_3  ,
	MATERIAL_METALL_GOLD_4  ,
	MATERIAL_METALL_GOLD_5  ,
	MATERIAL_METALL_GOLD_6  ,
	MATERIAL_METALL_GOLD_7  ,
	MATERIAL_METALL_GOLD_8  ,
	MATERIAL_METALL_GOLD_9  ,
	MATERIAL_METALL_GOLD_10 ,
	MATERIAL_METALL_GOLD_11  ,
	MATERIAL_METALL_GOLD_12  ,
	MATERIAL_METALL_GOLD_13  ,
	MATERIAL_METALL_GOLD_14  ,
	MATERIAL_METALL_GOLD_15  ,
	MATERIAL_METALL_GOLD_16  ,
	MATERIAL_METALL_GOLD_17  ,
	MATERIAL_METALL_GOLD_18  ,
	MATERIAL_METALL_GOLD_19  ,
	MATERIAL_METALL_GOLD_20  ,
	MATERIAL_METALL_GOLD_21  ,
	MATERIAL_METALL_GOLD_22  ,
	MATERIAL_METALL_GOLD_23  ,
	MATERIAL_METALL_GOLD_24  ,
	MATERIAL_METALL_GOLD_25  ,

	MATERIAL_GRANITE_1  ,
	MATERIAL_GRANITE_2  ,
	MATERIAL_GRANITE_3  ,
	MATERIAL_GRANITE_4  ,
	MATERIAL_GRANITE_5  ,
	MATERIAL_GRANITE_6  ,
	MATERIAL_GRANITE_7  ,
	MATERIAL_GRANITE_8  ,
	MATERIAL_GRANITE_9  ,
	MATERIAL_GRANITE_10 ,
	MATERIAL_GRANITE_11 ,
	MATERIAL_GRANITE_12 ,
	MATERIAL_GRANITE_13 ,
	MATERIAL_GRANITE_14 ,
	MATERIAL_GRANITE_15 ,
	MATERIAL_GRANITE_16 ,

	MATERIAL_WOOD_1  ,
	MATERIAL_WOOD_2  ,
	MATERIAL_WOOD_3 ,
	MATERIAL_WOOD_4  ,
	MATERIAL_WOOD_5 ,
	MATERIAL_WOOD_6 ,
	MATERIAL_WOOD_7 ,
	MATERIAL_WOOD_8 ,
	MATERIAL_WOOD_9  ,
	MATERIAL_WOOD_10 ,

	MATERIAL_IMAGE_1  ,
	MATERIAL_IMAGE_2  ,
	MATERIAL_IMAGE_3  
} MATERIALS_NUMBERS;

void CreateMaterials(int iMaterial);

rtCMaterial*   GetMaterial(int ind, 
						   float def_red = 1.0f,
						   float def_green = 0.0f, 
						   float def_blue = 0.0f, 
						   float def_alpha = 0.0f);

bool           IsImageMaterial(int ind);

void           SetMaterialToObject(sgCObject* ob, int mat_ind);

class CMatLibrary
{
	std::vector<rtCMaterial*>  m_materials;
public:
	void AddMaterial (void *bitBitMap, int iSizeX, int iSizeY);
	void Delete();
    void Create(int iMaterial);
	~CMatLibrary();
	rtCMaterial*   GetMaterial(size_t mat_ind);
};
extern CMatLibrary mat_library;


#endif